### ISSUE TITLE
[Discussion] Re-write all APIs

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/GeolocatorPlugin#10]
What would be your ideal Geolocator plugin?

I would love to re-think the entire API. Thoughts?

**Comment by srkrathore** [comment]
Hi James, any particular reason you want to rewrite it again ? I think the current one work fine. In fact have a suggestion for a few new plugins like
1) Custom Font Selector
2) SearchBar with Custom Icon
3) Maps with Maps App selector where instead of platform specific maps we can open map of our own choice google maps (if available). 

Regards
S Ravi Kumar

**Comment by aviabdg** [comment]
Xamarin.Forms support for iOS and Android included.

3 modes:
1. A one-shot mode async mode which can be awaited, where you want to get one coordinate for one location. You set a threshold of time and accuracy, and the result is returned when one of the two is reached. -- get me one coordinate -> stop at deadline
2. A one-location continuous async mode with events and/or a returned object with bindable properties. You want to get one coordinate for one location, you can turn it on and leave it on, keeping the GPS on until you are happy with the returned coordinate and accuracy, and then turn it off again. -- get me one coordinate, I continue until it's good enough, and I want feedback on progress -> continue until accuracy reached
3. A continuous async mode with events and/or bindable properties. The GPS can be turned on/off at will (suspend/resume or in background), any change in location is registered, timestamped and stored by the Geolocation manager. If there is no coordinate update, or GPS signal is lost, you can query the last known coordinate. As a bonus there could be 2 timestamps, when a coordinate was first found, and when it was most recently found (how long the device has not moved). Bonus 2 would be to set thresholds on the sensitivity of changes before they are stored as the new coordinate. Bonus 3 would be for the Geolocation manager to store not only the last, but a (limited?) history of coordinates. -- get me any change in coordinate/orientation/accuracy/etc. as I am moving about and/or tracking my movements and/or getting multiple locations, I want to get a result at any time I want, even if there is no current coordinate (timestamp) -> continuous tracking

This is what we are looking for in geolocation, hope this is of any use to you.

**Comment by aviabdg** [comment]
Would also be really great if it could optionally interface with an external bluetooth GPS module and use that as a source instead of the internal GPS.

**Comment by bokmadsen** [comment]
How about combining this plugin with the Geofence plugin https://github.com/domaven/xamarin-plugins/tree/master/Geofence.
In a current project I need both the current location and fences setup

**Comment by ericleigh007** [comment]
Hi James,
Thanks for asking.
How about full background support?  Not saying it is easy, but when yoiu're asking the king of plugins....
