### ISSUE TITLE
IOS location permissions doesn't ask at app installation/after installation

### ISSUE THREAD

**Issue by ashwinmca2009** [jamesmontemagno/GeolocatorPlugin#100]
## Bug Information

Version Number of Plugin: 3.0.4.0
Device Tested On: IOS Device IPhone 5, IPhone 6s & IPAD
Simulator Tested On: IPhone 5, 5S, 6, 7
Version of VS : 2015 & 2017
Version of Xamarin : 2.3.4.247
Versions of other things you are using:

### Steps to reproduce the Behavior
Install the app in various physical devices (IPhone 5, 5s, 6s, iPad 2 MC770LL/A) 

### Expected Behavior
Location permission dialog to be asked while app installation. 

### Actual Behaviour

**At IPhone 5s, App is working fine**

Location & Notification permissions dialog asked at the app installation.
Under the app settings, Location & Notification permission settings are updated. 

**At iPad 2 MC770LL/A app is not working as expected**.

Notification permission dialog asked at the app installation but location permission is not asked.
Under the app settings, Notification permission settings is updated but location permission is not updated.

After app installation, splash screen appeared and automatically minimised. We are unable to continue access the app pages. 

### Code snippet
 ```
locator = CrossGeolocator.Current;

                locator.DesiredAccuracy = 50;

                if (this.locator == null)
                    return;

                var position = await locator.GetPositionAsync(timeoutMilliseconds: 10000);

                var lati = position.Latitude;
                var longi = position.Longitude;
                double[] latlong = new double[] { lati, longi };
                MessagingCenter.Send<double[]>(latlong, "getLoc");

                locator.StartListeningAsync(0, 0, true);
                locator.PositionChanged += locator_PositionChanged;
```

**Comment by jamesmontemagno** [comment]
I recommend usage of the Permissions plugin to make sure you have correct locations as I will only ask once and if the user says no then you need to direct them to the settings page.
