### ISSUE TITLE
Getting Location on Android Emulator more then once

### ISSUE THREAD

**Issue by MarcoLLeite** [jamesmontemagno/GeolocatorPlugin#102]
## Bug Information
Version Number of Plugin: 3.0.4.0
Simulator Tested On: Android 7.1.1 & Android 6.0
Version of VS: 2017 Update 2

### Steps to reproduce the Behavior
When I run the Android Emulator and get the location on the first time it works just fine.
If I try to get the location for the second, third and so on times, I get an Exception: 
"System.Threading.Tasks.TaskCanceledException"
(https://gist.github.com/MarcoLLeite/80fda91dd7790495f591c5305ea571dd)

When I restart the emulator it works again for the first time and then the problem comes back.

The permissions for ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION are set.

I found someone on stackoverflow with the same problem but there is no clear solution: 
(https://stackoverflow.com/questions/43307447/xamarin-xlabs-geolocator-not-working-on-android/44629595#44629595)

### Expected Behavior
Get Latitude and Longitude

### Actual Behavior
Exception thrown

### Code 

                var locator = CrossGeolocator.Current;

                locator.DesiredAccuracy = LocationPositionDesiredAccuracy; //100 is new default

                var position = await locator.GetPositionAsync(timeoutMilliseconds: LocationPositionTimeout);

                LocationLatitudeEditor.Text = position.Latitude.ToString();
                LocationLongitudeEditor.Text = position.Longitude.ToString();

**Comment by jamesmontemagno** [comment]
You have to go into the emulators settings and press Send. It is the emulator, not the code.

**Comment by MarcoLLeite** [comment]
Thank you 👍
