### ISSUE TITLE
IsShowingUser showing correct postion CrossGeolocator.Current positon is jumping around on the map, why?

### ISSUE THREAD

**Issue by StanleyBroo** [jamesmontemagno/GeolocatorPlugin#103]
Android 5.1 LGK7 Device

IsShowingUser is always showing correct postion  on map
but the CrossGeolocator jumps around on the map until user starts walking around, why is that and how can I solve it? ..even when user walks around, the postion sometimes jumps away 300-500 meters and back again (but the IsShowing user is stable and in correct place)

I guess the question is how can I tap into the IsShowingUser "position" which seems reliable.

**Comment by jamesmontemagno** [comment]
Without filling out the form properly I can not help.
