### ISSUE TITLE
UWP Throw exception in StartListeningAsync

### ISSUE THREAD

**Issue by TFreudi1** [jamesmontemagno/GeolocatorPlugin#104]
Version Number of Plugin:3.04
Device Tested On:Windows 10 Mobile
Simulator Tested On:Windows 10 Mobile Emulator
Version of VS: VS2017 15.2 26430.13
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
Put somewhere in the shared Code:
CrossGeolocator.Current.StartListeningAsync(0, 0, false);
Start debugging UWP project

### Expected Behavior
Start listening for GPS as it does perfectly in iOS and Android

### Actual Behavior
Exception thrown:
You must set the MovementThreshold property or the ReportInterval property before adding event handlers

### Code snippet
Full code Snippet:
CrossGeolocator.Current.DesiredAccuracy = 0;
CrossGeolocator.Current.StartListeningAsync(0, 0, false);
CrossGeolocator.Current.PositionChanged += Current_PositionChanged;

**Comment by jamesmontemagno** [comment]
I am not able to reproduce this in the latest version... double check 4.0 and open a new one if necessary...

These are both set before:

```
         loc.ReportInterval = (uint)minTime.TotalMilliseconds;
            loc.MovementThreshold = minDistance;
            loc.PositionChanged += OnLocatorPositionChanged;
            loc.StatusChanged += OnLocatorStatusChanged;
```

**Comment by TFreudi1** [comment]
I use Version 4.0.1 and create a new simple UWP project and the problem persist.
WinRT information: You must set the MovementThreshold property or the ReportInterval property before adding event handlers.
Here is a simple project to test:
[GeolocatorTest.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/1121998/GeolocatorTest.zip)

**Comment by jamesmontemagno** [comment]
You need to await on the StartListeningAsync

```
protected async override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            try
            {
                CrossGeolocator.Current.DesiredAccuracy = 0;
                await CrossGeolocator.Current.GetPositionAsync(TimeSpan.FromSeconds(10));
                await CrossGeolocator.Current.StartListeningAsync(TimeSpan.Zero, 0, false);
                CrossGeolocator.Current.PositionChanged += Current_PositionChanged;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }
```

is what I changed it to, works great.

**Comment by TFreudi1** [comment]
I dont know what I'm doing wrong I put your code in my sample project (GeolocatorTest.zip in the Message above) and still get the same error. This time at home I 'd never use your nuget-package on that PC so can't be a wrong nuget, it also says 4.0.1
![grafik](https://user-images.githubusercontent.com/4739177/27840806-7354268a-60fc-11e7-94f4-60adfafa178a.png)

**Comment by TFreudi1** [comment]
![grafik](https://user-images.githubusercontent.com/4739177/27840870-f5c1ab24-60fc-11e7-8edf-812cdddfe0c9.png)

**Comment by jamesmontemagno** [comment]
So, looks like your issue in more testing is that 0 isn't valid for the minimumDistance.

Set it to 1:

await CrossGeolocator.Current.StartListeningAsync(TimeSpan.Zero, 1, false);

**Comment by jamesmontemagno** [comment]
This is a good blog as to what is happening:
https://blogs.windows.com/buildingapps/2012/12/03/geoposition-advanced-tracking-scenarios-for-windows-phone-8/#81dhJ7lK83WcPgT2.97

Basically you have to use one or the other, but it must be one of them and they both can't be 0. II will add some logic in here.

**Comment by TFreudi1** [comment]
Wow , Thanks James thats the solution!
