### ISSUE TITLE
README various errors

### ISSUE THREAD

**Issue by biapar** [jamesmontemagno/GeolocatorPlugin#105]
In the readme there are various errors. For example:

Correct form:
 `
var myposition = crosslocator.GetPositionAsync(timeoutMilliseconds: 10000);

            map.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(myposition.Result.Latitude, myposition.Result.Longitude),
                                             Distance.FromMiles(1))`

Not correct : myposition.Longitude 

Now, must be access to Result attribute to read various position info

**Comment by jamesmontemagno** [comment]
You need to await on it.

If you do a .Result then you will lock your user interface.

**Comment by biapar** [comment]
Thx
