### ISSUE TITLE
How to check if GPS is on?

### ISSUE THREAD

**Issue by biapar** [jamesmontemagno/GeolocatorPlugin#107]
How to check if GPS is on?
I see if is off the application crash. So I switch on the GPS and the application goes on.

**Comment by devapalanisamy** [comment]
It is happening for UWP currently. I have to check for iOS and Android.

**Comment by biapar** [comment]
@devapalanisamy I confirm you that happen. I think that I can avoid at least the crash with a try catch...

**Comment by jamesmontemagno** [comment]
You should always try/catch getting the location. The plugin makes standard calls. Please fill out the issue accurately for me to help or they will be closed immediately.

**Comment by biapar** [comment]
I see that the application crash if gps is off. So how to check if gps is on and avoid the error?

**Comment by jamesmontemagno** [comment]
You would need to provide more context as to what device, what os, what is your code, literally anything to help me here. Open a new bug with that information that should be filled out when you do "new issue"

**Comment by biapar** [comment]
I solved in this manner:

` try
            {

                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);

                if (status != PermissionStatus.Granted)
                {
                    if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                    {
                        await DisplayAlert("Need location", "Gunna need that location", "OK");
                    }

                    var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                    status = results[Permission.Location];
                }


                if (status == PermissionStatus.Granted)
                {
               
                    var myposition = await crosslocator.GetPositionAsync(timeoutMilliseconds: 10000);

                    if (myposition != null)
                    {

                        MyMap.Pins.Add(new Pin
                        {
                            Label = "Io",
                            Position = new Position(myposition.Latitude, myposition.Longitude),
                            Type = PinType.Generic
                        });

                        MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(myposition.Latitude, myposition.Longitude), Distance.FromMiles(1)));
                    }





                }
                else if (status != PermissionStatus.Unknown)
                {
                    await DisplayAlert("Location Denied", "Can not continue, try again.", "OK");
                }


            }
            catch (Exception ex)
            {

                await DisplayAlert("Location Error", ex.Message, "OK");
            }`
