### ISSUE TITLE
"A task was canceled" Error

### ISSUE THREAD

**Issue by angelobelchior** [jamesmontemagno/GeolocatorPlugin#108]
Error "A task was canceled" when trying to get geolocation using the "Geolocator" plugin

## Bug Information

[Stack Trace: https://gist.github.com/angelobelchior/5df61d4cb55dbd317b6664c8a9adeed0](https://gist.github.com/angelobelchior/5df61d4cb55dbd317b6664c8a9adeed0)

Version Number of Plugin:
Plugin.Geolocator: **3.0.4.0 Runtime Version v4.0.30319**
Plugin.Geolocator.Abstractions: **3.0.4.0 Runtime Version v4.0.30319**
Device Tested On: **Lenovo Vibe B Dual Chip Android 6.0**
Simulator Tested On: 
Android Emulator **25.2.5-3567187** 
Android Version **6.0 (Marshmallow) - API 23 (Rev 1)**
Version of VS:  **Visual Studio Enterprise 2017 Version 15.2 (26430.13)**
Version of Xamarin: **4.5.0.486**
Versions of other things you are using:
Xamarin.Android SDK: **7.3.1.2**
Xamarin.iOS and Xamarin.Mac SDK: **10.10.0.37**

### Steps to reproduce the Behavior
- Install and configure GeolocatorPlugin follow de default instructions
- Invoke GetPositionAsync Method with timeoutMilliseconds equals to 10000

### Expected Behavior
- Get the current position.

### Actual Behavior
A task was canceled Exception

### Code snippet
```csharp                    
            var locator = CrossGeolocator.Current;
            if (locator.IsGeolocationAvailable && locator.IsGeolocationEnabled)
            {
                 locator.DesiredAccuracy = 100;
                 var position = await locator.GetPositionAsync(timeoutMilliseconds: 10000);
                 if (position != null)
                     return new Tuple<double, double>(position.Latitude, position.Longitude)
              }
```

### Screenshotst
![error](https://user-images.githubusercontent.com/4245518/27396314-110e6364-5689-11e7-8aee-75134f94ad2a.png)

**Comment by jamesmontemagno** [comment]
This means it has timed out. Ensure that you either extend your task length, ensure the gps is on, or on emulator you send it over.

**Comment by WellingtonSilva1992** [comment]
Same problem here. I edited the task length and the error continues. Thanks for help James

**Comment by gcwei** [comment]
I'm experiencing the same issue. Cannot get location. Timeout. 

Using Plugin.Geolocator: 3.0.4.0.
Tested on iOS and Android. Both catch exception.

**Comment by frank10gm** [comment]
Hi,
I'm experiencing the same issue.

**Comment by yangshuxin199393** [comment]
I have the same problem

**Comment by frank10gm** [comment]
found solution

**Comment by mattman624** [comment]
@frank10gm Could you share your solution?

**Comment by Dev-Reynz** [comment]
..experiencing the same issue..

**Comment by shreesalunke** [comment]
Hi Everyone

i am new to xamarin android i am facing problem to get current gps location
run time permissions are implemented successfully xam.plugin.geolocator works on android 7.1 and above and its also works below 6.0 android but getting problem with android 6.0 to 7.0 android os the position always return null on 6.0 and 7.0 but works great above 7.1 please help me i am facing this issue  from 1 month and trying to resolve from last one moth but did not get success

 var locator = CrossGeolocator.Current;
if (locator.IsGeolocationEnabled)
                {
                    // Allow ten seconds for geo-location determination.                    
                    position = await locator.GetPositionAsync(TimeSpan.FromSeconds(10));
                }

                latitude = string.Format("Lat: {0}", position.Latitude);
                longitude = string.Format("Lat: {0}", position.Longitude);

**Comment by shreesalunke** [comment]
target Version Android 8.0
Minimum Android Version Android 4.1
Compile using Android 8.0

please help.....

**Comment by zchpit** [comment]
shreesalunke -> you should set:
Minimum Android Version Android 6.0 (API 23)

Prefered version
Minimum Android Version Android 7.1 (API 25)

**Comment by GeoffreyFook** [comment]
Hey my doooooods. I also struggled with this for a while. It's only a problem on the emulator, even if your sometimes you have to explicitly send it a location in order for it to work. Set a location and press send as shown below

![image](https://user-images.githubusercontent.com/39644464/45705423-da238d00-bb79-11e8-90e4-b05862e70a53.png)

**Comment by rcunniffe** [comment]
@jamesmontemagno same issues but for storage. `await CrossPermissions.Current.RequestPermissionsAsync(Permission.Storage);` > `Exception:

System.Threading.Tasks.TaskCanceledException: A task was canceled.`

**Comment by taublast** [comment]
This is a very wierd behavour on Android 6 real device i just faced: 

- asked for permissions, 
- permissions granted, 
- then android is asking if i want to increase accuracy to use mobile network along with gps, i said No

then no matter the task length i'm setting, it just exits on timeout with this A task was canceled.

Went to android gps settings, have set increase accuracy to use not only gps but network data too, and it suddenly worked.
Problem is locator is obviously reporting gps is avalable, gps is on, but the device is failing to get position.
The only workaround im seeing atm is to show a user warning on such fail, proposing to increase accuracy in gps settings, and to open system gps settings for user.

**Comment by taublast** [comment]
Just in case anyone needs, opening system gps settings from app:
android:
```
        using Plugin.CurrentActivity;
        //---------------------------------------------------------
        public void OpenGPSSettings()
        //---------------------------------------------------------
        {
            var intent = new Intent(Android.Provider.Settings.ActionLocationSourceSettings);
            CrossCurrentActivity.Current.Activity.StartActivity(intent);
        }
```
ios:
```
        //---------------------------------------------------------
        public void OpenGPSSettings()
        //---------------------------------------------------------
        {
            var url = new NSUrl($"prefs:root=NOTIFICATIONS_ID&path={NSBundle.MainBundle.BundleIdentifier}");
            var res = UIApplication.SharedApplication.OpenUrl(url);
            if (!res)
            {
                url = new NSUrl("app-settings:");
                res = UIApplication.SharedApplication.OpenUrl(url);
            }
        }
```
