### ISSUE TITLE
GetPositionAsync does not return a position on device

### ISSUE THREAD

**Issue by chriszirkel** [jamesmontemagno/GeolocatorPlugin#11]
## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: OnePlus ONE E1003 Android 5.1 API 22
Simulator Tested On: -

### Expected Behavior
Get position
### Actual Behavior
A call of the method GetPositionAsync from my Xamarin.Forms PCL does not return a position and ends with timeout. An increase of the timeout and DesiredAccuracy, or completely remove it does not work. On the other hand, no problems on the Emulator.

### Steps to reproduce the Behavior
            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;

                if (locator.IsGeolocationAvailable && locator.IsGeolocationEnabled)
                {
                    var position = await locator.GetPositionAsync();

                    Latitude.Text = position.Latitude.ToString();
                    Longitude.Text = position.Longitude.ToString();
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Unable to get location, may need to increase timeout: " + ex);
            }

**Comment by jamesmontemagno** [comment]
Have you tried it without:  if (locator.IsGeolocationAvailable && locator.IsGeolocationEnabled) 

I believe this doesn't take the new permissions into effect. Let me know as it works on my devices here.

**Comment by chriszirkel** [comment]
I debugged through it and both properties are true, so the GetPositionAsync method was called.

**Comment by jamesmontemagno** [comment]
Do you have location enabled on your device?

Can you download: https://play.google.com/store/apps/details?id=com.refractored.testappforms and see if the location part works?

**Comment by chriszirkel** [comment]
I testet it again after I removed the application completely from my phone and now it's working, even if it takes some more time to get the location than it in your example app.

You can close this issue, I think I testes wrong or with too less timeout.

Thanks for your help! :)

**Comment by marceloraposo** [comment]
It did not work for me.
Can you help me?

Thank you
