### ISSUE TITLE
Calling StartListeningAsync a second time crashes WinPhone8

### ISSUE THREAD

**Issue by psyon** [jamesmontemagno/GeolocatorPlugin#111]
In the view that displays coordinates, I call StartListeningAsync() in OnAppearing, and StopListeningAsync on OnDisappearing.  The first time the view is loaded, the GeoLocator starts up fine.  The second time the view is loaded though, an exception is thrown.  After some testing, it seems the exception is thrown if you call StartListeningAsync again after calling StopListeningAsync.  This only affects Windows Phone 8, and isn't an issue on iOS or Android.

## Bug Information

Version Number of Plugin: 3.0.4
Device Tested On: Nokia Lumia 530
Simulator Tested On: 
Version of VS: 2015
Version of Xamarin: 4.5.0.486
Versions of other things you are using:

### Steps to reproduce the Behavior

await CrossGeolocation.Current.StartListeningAsync(1000,0);
await CrossGeolocation.Current.StopListeningAsync();
await CrossGeolocation.Current.StartListeningAsync(1000,0);

### Expected Behavior

Locator should start, then stop, then start again.

### Actual Behavior

Exception thrown: 'System.Exception' in Plugin.Geolocator.ni.DLL

**Comment by jamesmontemagno** [comment]
I no longer support Windows 8 device and only UWP going forward.
