### ISSUE TITLE
[Feature Request] Api Key's configuration

### ISSUE THREAD

**Issue by rcrodriguezf** [jamesmontemagno/GeolocatorPlugin#113]
Hi James.

Specifically, are 3 questions:
1. In this plugin, you use the commons free web services of some providers like google, bing maps or another one?
2. If you use any web services, I suppose that you’re using API keys to build queries and consume the web services? 
3. If you’re using some API Key, it’s possible to change the API Key or made it configurable?

I hope you can help me with these doubts.

Regards.

**Comment by jaydeeveloper** [comment]
This plugin use the device hardware, it's not a map component.

Regards.

**Comment by jamesmontemagno** [comment]
You only need it for UWP reverse geolocation and nothing else: https://github.com/jamesmontemagno/GeolocatorPlugin#reverse-geocoding

**Comment by rcrodriguezf** [comment]
Thank you for your answers  @jaydeeveloper and @jamesmontemagno. Actually I don't use the reverse geolocation, but I'll consider the key if I need to use it.
Regards.
