### ISSUE TITLE
UWP side

### ISSUE THREAD

**Issue by Emixam23** [jamesmontemagno/GeolocatorPlugin#114]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Screenshotst

Hey James !

First, I would like to thank you for the work/packages you gave :)

I'm using this package in order to get my own location, however, I'm facing 2 problems.. and before, it was working, but not anymore..

So first, on Android, I don't see my location on the map like before, the user's location point isn't shown, this is weird, but I don't know if it comes from your package, however, it works, I get the location data.
Second, on UWP, it was working before and now, it throws an exception, I think I got an update of your package...

    Unable to get location, may need to increase timeout: Plugin.Geolocator.Abstractions.GeolocationException: A geolocation error occured: Unauthorized ---> System.UnauthorizedAccessException: Access is denied.

    Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.
    --- End of inner exception stack trace ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at NightLine.Sources.Controls.CustomMap.<GetPosition>d__100.MoveNext()`

It's written by a `try/catch` ->

    public class CustomMap : Map
    {
         // ....

        #region User Location

        /// <summary>
        /// The current location of the user.
        /// </summary>
        public static readonly BindableProperty UserLocationProperty =
            BindableProperty.Create(nameof(UserLocation), typeof(Position), typeof(CustomMap), new Position());

        /// <summary>
        /// Assessor for UserLocation property.
        /// </summary>
        public Position UserLocation
        {
            get { return (Position)GetValue(UserLocationProperty); }
            private set { SetValue(UserLocationProperty, value); }
        }

        /// <summary>
        /// Get the current position of the user.
        /// </summary>
        /// <returns>The current location of the user.</returns>
        public async static Task<Position> GetPosition()
        {
            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;

                var position = await locator.GetPositionAsync(TimeSpan.FromSeconds(10));
                if (position != null)
                    return new Position(position.Latitude, position.Longitude);
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Unable to get location, may need to increase timeout: " + ex);
            }

            var cached = await CrossGeolocator.Current.GetLastKnownLocationAsync();
            if (cached == null)
                return new Position();

            Debug.WriteLine("Position Status: {0}", cached.Timestamp);
            Debug.WriteLine("Position Latitude: {0}", cached.Latitude);
            Debug.WriteLine("Position Longitude: {0}", cached.Longitude);
            
            return (new Position());
        }

        #endregion User Location

        // ...
    }

Any idea? Did I do something wrong?

**Comment by jamesmontemagno** [comment]
It says it right in the actual exception... did you read through that:

Unable to get location, may need to increase timeout: Plugin.Geolocator.Abstractions.GeolocationException: A geolocation error occured: Unauthorized ---> System.UnauthorizedAccessException: Access is denied.

Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.

^^^^ Add: ID_CAP_LOCATION to your UWP app

**Comment by Emixam23** [comment]
Hey James !

So I checked and everything is good on the dev part, however, the computer location was checked on (off) on some points...

Thank for your help

Best,

Max

**Comment by MartinAngeleri** [comment]
Got the same issue and came here looking for a solution. Then, reading jame's reply, realized that may be permissions were not set at hardware level. So double checked on my phone (Settings/Applications/MyApplication/Permissions) and effectively 'Location' checkbox was not enabled. It was just that, maybe because on dev mode, my phone doesnt ask for permissions.
Thanks Jamens for this amazing plugin, and ty too Emixam23 for this thread.
Cheers!
