### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by gmeredith** [jamesmontemagno/GeolocatorPlugin#117]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: Compile Issue
Simulator Tested On: Compile issue
Version of VS: 2015 update 3
Version of Xamarin: 4.5.0.486
Versions of other things you are using:

### Steps to reproduce the Behavior
This is a compile issue. I get the following error when I compile. I have removed and re-installed the plug in and the same error.

Failed to resolve "System.Threading.Tasks.Task`1<Plugin.Geolocator.Abstractions.Position> Plugin.Geolocator.Abstractions.IGeolocator::GetPositionAsync(System.Int32,System.Nullable`1<System.Threading.CancellationToken>,System.Boolean)" reference from "Plugin.Geolocator.Abstractions, Version=3.0.4.0, Culture=neutral, PublicKeyToken=null"

**Comment by jamesmontemagno** [comment]
Did you update all of your nugets in all your projects?

**Comment by gmeredith** [comment]
James,
I think that is my issue. I noticed “multiple versions installed” in nugget on my PCL. Recompiling now.

Glen Meredith

**Comment by gmeredith** [comment]
That was it James. Thanks for the quick response. You can totally delete this one if you want/can.
Glen
