### ISSUE TITLE
Add Forward Geocoding

### ISSUE THREAD

**Issue by TonyLugg** [jamesmontemagno/GeolocatorPlugin#118]
The plugin would be perfect if it also had forward geocoding.

**Comment by jamesmontemagno** [comment]
Describe? what would the api look like and what would it do?

**Comment by TonyLugg** [comment]
It is just a regular geocode, converting an address to a lat/lng.  For example, pass in "Houston, TX", and return the lat/lng coordinate of the center of Houston.

**Comment by TonyLugg** [comment]
Xamarin Forms Maps supports both geocoding and reverse geocoding, as do all the platforms.  Can you add it to your plugin.  I'm having trouble with the UWP geocoder implementation in XF Maps, but I can't switch to yours unless you add regular geocoding.

**Comment by jamesmontemagno** [comment]
It's on my backlog

**Comment by TonyLugg** [comment]
This issue is closed but I don't see it in the latest release docs.  Did you decide not to add this feature?

**Comment by jamesmontemagno** [comment]
because i implemented it, hasn't been released yet
