### ISSUE TITLE
Invalid Toolchain

### ISSUE THREAD

**Issue by eliseoglb** [jamesmontemagno/GeolocatorPlugin#119]
I'm using the geolocator plugin in iOS and works fine in debug mode but when I try upload to appstore show this message:

Invalid Toolchain - New apps and app updates must be built with the public (GM) versions of Xcode 6 or later, macOS, and iOS SDK. Don't submit apps built with beta software including beta macOS builds.

**Comment by jamesmontemagno** [comment]
Are you building against iOS 11 SDK?
