### ISSUE TITLE
Facing problem with accuracy

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/GeolocatorPlugin#121]
I am using this plugin for my xamarin forms project. After getting device location in my android app storing into database and again when I compare with the master data with device location standing in the same place but I am getting device output always 1 point different with master data but it should be same as I am in the same location. Below is some output:

From database:
Lat: 23.364
Long: 85.349

From Device:
Lat: 23.363
Long: 85.350

Here I am taking only 3 decimal places and my accuracy's code is below:

```
var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = 50;
var position = await locator.GetPositionAsync(TimeSpan.FromSeconds(1));

```

Why I can't get the accurate value from mobile device using this plugin or code?

**Comment by jamesmontemagno** [comment]
Have you tried more than 3 decimals... for coordinates you need at least 5 or 6

**Comment by ShahriatHossain** [comment]
@jamesmontemagno I had tried with the full decimals in the first time but that doesn't work and tried with 3 decimals also doesn't work, I will try again with 5 or 6 according to your suggestion but what should be the  accuracy setting then? current one is 50.

**Comment by jamesmontemagno** [comment]
Accuracy is just how accurate within X meters do you want it to be... So do you want it to be withing 1 meter then set to 1.

Right now you are saying within 50 meters. I hope that clears it up.

**Comment by smaperkings** [comment]
I have set my accuracy to 2 but I always obtain 19 when I get my position. Here is the code I used:

`public async static Task<Position> getCurrentLocation()
        {
            Position position = null;
            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 2;

                position = await locator.GetLastKnownLocationAsync();

                if (position != null)
                {
                    //got a cahched position, so let's use it.
                    //position = await locator.GetPositionAsync(TimeSpan.FromSeconds(2), null, true);
                    return position;
                }

                if (!locator.IsGeolocationAvailable || !locator.IsGeolocationEnabled)
                {
                    //not available or enabled
                    return null;
                }

                position = await locator.GetPositionAsync(TimeSpan.FromSeconds(2), null, true);

            }
            catch (Exception ex)
            {
                Debug.WriteLine("Unable to get location: " + ex);
            }

            if (position == null)
                return null;

            var output = string.Format("Time: {0} \nLat: {1} \nLong: {2} \nAltitude: {3} \nAltitude Accuracy: {4} \nAccuracy: {5} \nHeading: {6} \nSpeed: {7}",
                    position.Timestamp, position.Latitude, position.Longitude,
                    position.Altitude, position.AltitudeAccuracy, position.Accuracy, position.Heading, position.Speed);

            Debug.WriteLine(output);
            return position;

        }`
When I then get the attributes of my position object like this:
` public static async Task setCurrentLocation(Object context)
        {
            var position = await getCurrentLocation();
            if (position != null)
            {
                timestamp = (long)position.Timestamp.Millisecond;
                longitude = (double)position.Longitude;
                latitude = (double)position.Latitude;
                speed = (float)position.Speed;
                altitude = (double)position.Altitude;
                heading = (float)position.Heading;
                accuracy = (float)position.Accuracy;
                altitudeAccuracy = (float)position.AltitudeAccuracy;
            }

        }`,
I always get an accuracy of 19. What could be the problem?
