### ISSUE TITLE
missing reference for Plugin.CurrentActivity

### ISSUE THREAD

**Issue by asulwer** [jamesmontemagno/GeolocatorPlugin#122]
missing reference when i install via Nuget for Plugin.Activity v 1.0.1 for xamarin android project

## Bug Information

Version Number of Plugin: v1.0.1
Device Tested On: will not compile
Simulator Tested On: will not compile
Version of VS: 2017 pro
Version of Xamarin: 4.5.0.486

if i down grade to a previous version reference is included.  assembly is not included in packages directory

![image](https://user-images.githubusercontent.com/7673412/28947442-7c20fe10-7875-11e7-9e5a-e6aefa7d6a1f.png)
![image](https://user-images.githubusercontent.com/7673412/28947448-8ce7060e-7875-11e7-8592-0bcc0ab8df71.png)
![image](https://user-images.githubusercontent.com/7673412/28947460-9826273e-7875-11e7-843c-f2119913e6df.png)

**Comment by jamesmontemagno** [comment]
Works for me just fine, haven't ever had any issues. maybe uninstall and re-install, should be in lib folder

**Comment by asulwer** [comment]
well its not on mine and I don't have your computer.  don't be so quick to make assumptions.  as you can see from the screen shots its missing in my packages folder.  I uninstalled, reinstalled, down and upgraded, nothing pulled it down.

**Comment by asulwer** [comment]
started a new project and same thing.  only nuget package installed was Xam.Plugins.GeoLocator

**Comment by jamesmontemagno** [comment]
That is what I just did:
![image](https://user-images.githubusercontent.com/1676321/28977530-39bb3c52-78f7-11e7-8815-f4582e967df5.png)

Did you just try manually adding the dll in the lib folder?

**Comment by asulwer** [comment]
at first I thought the same thing.  the assembly is missing from the lib folder.  just the xml file is there.  I am using VS 2017 if that matters

are there android specific settings that may effect this?  something else I may have missed?

**Comment by jamesmontemagno** [comment]
Are you correctly compiling against API 25+?

![image](https://user-images.githubusercontent.com/1676321/28977747-2c89e4d8-78f8-11e7-9da6-56b42a34672c.png)


Seems like a nuget issue.

**Comment by jamesmontemagno** [comment]
What if you just try to install the Current Activity Plugin separate?

**Comment by asulwer** [comment]
I created a new project and installed just the CurrentActivity plugin and had the same issue

**Comment by asulwer** [comment]
installed a pre version of CurrentActivity first then Geolocator, now the assembly is included

**Comment by jamesmontemagno** [comment]
hmmmm there are no pre-versions... https://www.nuget.org/packages/Plugin.CurrentActivity/

Something is wrong with your NuGet for sure.. glad you go tit working though....

**Comment by asulwer** [comment]
cleared nuget cache and that solved the problem

**Comment by himanjanpati** [comment]
Hello guys, I am getting the same issue after doing all workaround that you have followed also after clearing the NuGet cache. Please suggest if you have an alternative approach to resolve the issue.

Error details.
Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity

The type 'Activity' is defined in an assembly that is not referenced. You must add a reference to assembly 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

**Comment by teejay-87** [comment]
Same for me. I went crazy... then I restarted VS and it was gone... :expressionless: :rage:

**Comment by reinierkops** [comment]
@ryanharding how did you manually added the reference? The nuget package of System.Collection has only _._ files in it?

**Comment by ryanharding** [comment]
@reinierkops I just browsed to my solutions nuget packages folder location (  ..\..\packages\System.Collections.4.3.0\ref\netstandard1.3 ) in the add references window on my android project. 

Hope that helps you.

**Comment by jamesmontemagno** [comment]
I have rolled back this updated for now.
