### ISSUE TITLE
Method not found.

### ISSUE THREAD

**Issue by rmizuuti** [jamesmontemagno/GeolocatorPlugin#124]
Just found out the plugin and I think I might be missing something out here.

I'm using the code snippet provided, as shown below, and everytime I try to run it on emulator or real device I get the error System.MissingMethodException: Method 'Plugin.Geolocator.Abstractions.IGeolocator.GetPositionAsync' not found.

I double checked the permissions and the call on the permissions plugin.

What van I be doing wrong?

CODE:

var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;
                var position = locator.GetPositionAsync(TimeSpan.FromSeconds(10)).Result;
                if (position == null)
                    return;
... show mesage to user and so on...

Seems like the exception is thrown as soon as I call GetPositionAsync method.

**Comment by jamesmontemagno** [comment]
Make sure that you have updated ALL of your nuget packages and do a clean/rebuild


Also, you really shouldn't use .Result as it is thread locking: http://motzcod.es/post/162870742532/c-sharp-developers-stop-calling-dot-result
