### ISSUE TITLE
AllowsBackgroundUpdates for iOS 10 and newer?

### ISSUE THREAD

**Issue by GAlleniTRAK** [jamesmontemagno/GeolocatorPlugin#125]
It does not appear my app will run in the background on iPhone running iOS 10.2 (it is running great on Android).  The app runs fine on the iPhone when in the foreground.  
It looks like the code specifies setting the AllowsBackgroundLocationUpdates only for iOS Version 9.  Could this be why my app will not run on my iPhone?  I am using Geolocator version 3.0.4.0 and Xamarin.Forms 4.0.30319 (due to Mac limitations) and Visuals Studio 2015 Community Edition Version 14.0.25431.01 Update 3.

**Comment by jamesmontemagno** [comment]
Checkout:

https://jamesmontemagno.github.io/GeolocatorPlugin/BackgroundUpdates.html

the version checks are for minimal versions, so if I check for 9 that code runs on 9+ OS devices.
