### ISSUE TITLE
Under iOS 'IsGeolocationEnable' and 'IsGeolocationAvailable' are always true

### ISSUE THREAD

**Issue by andreasfromch** [jamesmontemagno/GeolocatorPlugin#126]
## Bug Information
Both properties 'IsGeolocationEnable' and 'IsGeolocationAvailable' are always true under iOS. It had worked in version 4.0.0.67-alpha but doesn't in 4.0.1.

Version Number of Plugin: 4.0.1
Device Tested On: iPhone5, iPhone7
Simulator Tested On: iPhone6
Version of VS: 2017
Version of Xamarin: 4.5.0.486
Versions of other things you are using: iOS

### Steps to reproduce the Behavior
Access the properties 'IsGeolocationEnable' and 'IsGeolocationAvailable' they are always true

### Expected Behavior
The properties 'IsGeolocationEnable' and 'IsGeolocationAvailable' use the setting under 'ALLOW LOCATION ACCESS'

**Comment by jamesmontemagno** [comment]
This behavior is correct, it no longer checks if your app has permission:

```
        /// <summary>
        /// Gets if geolocation is available on device
        /// </summary>
        public bool IsGeolocationAvailable => true; //all iOS devices support Geolocation

        /// <summary>
        /// Gets if geolocation is enabled on device
        /// </summary>
        public bool IsGeolocationEnabled
        {
            get
            {         
                var status = CLLocationManager.Status;
                return CLLocationManager.LocationServicesEnabled;
            }
        }
```

All iOS devices have GPS and I check if location services are enabled or not.

**Comment by andreasfromch** [comment]
My Logfile on an iPhone 6 iOS 10.3 shows the following:

12.08.17 08:39:28,759 WARN  Permission status for Location='Denied'.
12.08.17 08:39:28,882 FATAL CrossGeolocator.Current.IsGeolocationEnabled='True'
12.08.17 08:39:39,626 WARN  Permission status for Location='Denied'.
12.08.17 08:39:39,801 FATAL Plugin.Geolocator.Abstractions.GeolocationException: A geolocation error occured: Unauthorized

CrossGeolocator.Current.IsGeolocationEnabled='True' and the Permission status from 'CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location) is not 'granted'

**Comment by jamesmontemagno** [comment]
You should use the permissions plugin to check permissions: https://github.com/jamesmontemagno/permissionsplugin
