### ISSUE TITLE
Requires unnecessary permission NSCalendarsUsageDescription

### ISSUE THREAD

**Issue by dmitry-lt** [jamesmontemagno/GeolocatorPlugin#130]
## Bug Information

Version Number of Plugin: 4
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

Build and try publishing a Xamarin iOS app that uses this plugin

### Expected Behavior

The app is successfully published

### Actual Behavior

Error: Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by jamesmontemagno** [comment]
This is a known limitation in the permission plugin.
