### ISSUE TITLE
UnauthorizedAccessException UWP when location services are disabled by policy

### ISSUE THREAD

**Issue by almudy** [jamesmontemagno/GeolocatorPlugin#133]
Hi, 

we are using the GeoLocator plugin (Ver 4.0.1) in our multi platform Xamarin Forms project. 

Capability "location" is checked in manifest and on location service enabled machines "GetPositionAsync()" works like a charm.

On some UWP machines the location services are disabled by company policy and our app is crashing with an unhandled exception. Even if the function is called in a try-catch there is an "UnauthorizedAccessException" thrown, that I cannot handle in catch-block.

Is anyone else experiencing this behavior?

Thanks for your help!

Alex

**Comment by jamesmontemagno** [comment]
Did you check to see if "IsGeolocatorAvailable" and "IsGeolocatorEnabled" ?

**Comment by jamesmontemagno** [comment]
I don't know how to really test this, but you can test the new 5.0-beta version where I do permission checks ahead of time. That should throw an exception that it isn't authorized.
