### ISSUE TITLE
Samples app for ios always returns speed 0

### ISSUE THREAD

**Issue by pedropete11** [jamesmontemagno/GeolocatorPlugin#135]
Version Number of Plugin: 4.0.1
Device Tested On: iPhone 6 10.3.3

Ran sample ios app with various parameters. lat/lng always works, but speed is always 0. Accuracy is >=65.
UNLESS: if you turn on maps, then the speed will work. Once Maps stops running, speed is always 0.

Other 'gps' store apps ("GPS Data", tried a few others but not sure if pure gps hardware) correctly show speed.
I can't figure out a way to get speed to show up.

**Comment by pedropete11** [comment]
Nevermind:
You must set the DesiredAccuracy before starting the async position updates. The default will not return speed - it must be set to a much smaller number. Try 10 in the sample app and it will work.

**Comment by amentma** [comment]
FYI: Using plugin version 4.2.0 I'm facing zero speed issue even when Locator.DesiredAccuracy set to 10, my results:

iPhone 6 with iOS 10.3.3. -> speed is always 0
iPhone 7 with iOS 10.3.3 -> speed is working well
iPhone SE with iOS 11.4 -> speed is working well
iPad Air 2 with iOS 11.4 -> speed is always 0

When I changed Locator.DesiredAccuracy to 5, iPhone 6 starts to show speed as expected. iPad show no speed, but this is wifi version and testing inside house...

**Comment by pedropete11** [comment]
I've tested with iPhone 6 and DesiredAccuracy=10 and speed is working, although updates can be slow.
From what I've seen, the air 2 does not have gps hardware unless it has cellular. Wifi only models don't have gps hardware.
Oh well - that app is using plug in 4.0.1. Hopefully, I'll get a chance to update it...
