### ISSUE TITLE
GPS background on iOS

### ISSUE THREAD

**Issue by TFreudi1** [jamesmontemagno/GeolocatorPlugin#137]
I can't get Backgroundupdates to work on iOS. After the App goes in the background it provides some postions (less than 10) and it stops than until I wake the App up.
I modified your sampelcode, add the plist.info entry for Loacationbackgrounds an change line 170 of Homepage.xaml.cs to
```
if (await CrossGeolocator.Current.StartListeningAsync(TimeSpan.FromSeconds(1), 0, false, new ListenerSettings
					{
								
 	ActivityType = ActivityType.Other,
	AllowBackgroundUpdates = true,
	DeferLocationUpdates = false,
	DeferralDistanceMeters = 0,
	
DeferralTime = TimeSpan.FromSeconds(0),
	
ListenForSignificantChanges = false,
	PauseLocationUpdatesAutomatically = false
 
}))
```
but I did'nt get background updates, in my code, which is much simpler than your sample, I replace CurrentGeolocator with simple Locationmangagercode:

```
 LocationManager = new CLLocationManager();

 if (LocationManager.RespondsToSelector(new ObjCRuntime.Selector("requestAlwaysAuthorization")))
     LocationManager.RequestAlwaysAuthorization();

            LocationManager.DistanceFilter = CLLocationDistance.FilterNone;
            LocationManager.DesiredAccuracy = 0.0;
            LocationManager.AllowsBackgroundLocationUpdates = true;
            LocationManager.LocationsUpdated += LocationManager_LocationsUpdated;
            LocationManager.StartUpdatingLocation();
```

it workes like a charme and LocationManager_LocationsUpdated is called every second even  in background.

**Comment by jamesmontemagno** [comment]
So in your case the following is set on the manager:

```
manager.PausesLocationUpdatesAutomatically = false;
manager.ActivityType = CLActivityType.Other;
manager.DesiredAccuracy = CrossGeolocator.Current.DesiredAccuracy; //defaults to 100
manager.DistanceFilter = 0;
```

So very close, can you try with these setting in your core iOS code to make sure they are matching. Looks like your Desired Accuracy is a bit different, but that is about it.

The only other thing is that we set the DistanceFilter to 0 instead of CLLocationDistance.FilterNone.... I can check to see if that makes a different at all too.
