### ISSUE TITLE
How to handle sometime GPS get NaN?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/GeolocatorPlugin#138]
How to handle sometime GPS get NaN?

**Comment by nguyenthanhliemfc** [comment]
`private void Current_PositionChanged1(object sender, global::Plugin.Geolocator.Abstractions.PositionEventArgs e)
        {
            Device.BeginInvokeOnMainThread(() => 
            {
                var position = e.Position;                
                var accuracy = position.Accuracy;
                txtRadius.Text = "Current GPS Radius: " + Math.Round(position.Accuracy,2) + " meters";
                if (txtDistance.Text != null && txtDistance.Text != "")
                {
                    txtStatus.Text = "Now you can minimize this app";                    
                }
                if (position.Accuracy <= double.Parse(Helpers.Settings.RadiusSettings))
                {                    
                    progressRing.IsRunning = false;
                    progressRing.IsVisible = false;
                    double newlong = position.Longitude;
                    double newla = position.Latitude;
                    if (Double.IsNaN(newlong) == false || Double.IsNaN(newla) == false)
                    {
                        distance += DistanceTo(firstla, firstlong, newla, newlong, 'K'); //Sometime distance return NaN
                        firstla = newla;
                        firstlong = newlong;
                        distance = Math.Round(distance, 2);
                        txtDistance.Text = distance.ToString();
                        listSeriesPoint.Add(new SeriesPoint { Group = txtGroup.Text, Longtitude = firstlong, Latitude = firstla, Ngay = DateTime.Now.ToString("yyyy-MM-dd"), Id = lastId });                        
                    }
                }
                else
                {
                    //ShowToast(new NotificationOptions()
                    //{
                    //    Title = "Accuracy lower " + accuracy + "meters",
                    //    Description = "Please move to another place!",
                    //    IsClickable = true,
                    //    WindowsOptions = new WindowsOptions() { LogoUri = "icon.png" }
                    //});
                }
            });
        }`
`static public double DistanceTo(double lat1, double lon1, double lat2, double lon2, char unit = 'K')
        {
            double rlat1 = Math.PI * lat1 / 180;
            double rlat2 = Math.PI * lat2 / 180;
            double theta = lon1 - lon2;
            double rtheta = Math.PI * theta / 180;
            double dist = Math.Sin(rlat1) * Math.Sin(rlat2) + Math.Cos(rlat1) * Math.Cos(rlat2) * Math.Cos(rtheta);
            dist = Math.Acos(dist);
            dist = dist * 180 / Math.PI;
            dist = dist * 60 * 1.1515;
            switch (unit)
            {
                case 'K': //Kilometers -> default
                    return dist * 1.609344;
                case 'N': //Nautical Miles 
                    return dist * 0.8684;
                case 'M': //Miles
                    return dist;
            }
            return dist;
        }`

**Comment by nguyenthanhliemfc** [comment]
I calculate distance of 2 point when position change and save result in a variable "distance". But sometime "distance" return NaN

**Comment by jamesmontemagno** [comment]
See: https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving.Utils/Helpers/DistanceUtils.cs
