### ISSUE TITLE
How to get position object (mainly gps Lat and Lon ) by providing string address (mainly city name) ?

### ISSUE THREAD

**Issue by agrebenyuk** [jamesmontemagno/GeolocatorPlugin#140]
Hi guys , this is just a question , not sure if this is possible to get position object (mainly gps Lat and Lon ) by providing string address (mainly city name) ?

Can you please give me an idea about how can I get it and If this is not currently supported - I would be interested if it is in your scope of work for future releases ?

Regards,
Andrey

**Comment by TonyLugg** [comment]
I've asked for the same thing but I don't think it is available.

**Comment by jamesmontemagno** [comment]
It is already implemented, not released. 

Duplicate of: https://github.com/jamesmontemagno/GeolocatorPlugin/issues/118

**Comment by agrebenyuk** [comment]
Awesome news, Thanks! Can't wait to try it out !

**Comment by agrebenyuk** [comment]
Hi Guys! , Any news about this feature , is there a plan to release it anytime soon ?

**Comment by jamesmontemagno** [comment]
You can always grab the CI feeds: https://ci.appveyor.com/nuget/geolocatorplugin 

You would want to check commit history: https://ci.appveyor.com/project/JamesMontemagno/geolocatorplugin/history
