### ISSUE TITLE
IsGeolocationAvailable and IsGeolocationEnabled returns false on Android when no permission is granted

### ISSUE THREAD

**Issue by cmeeren** [jamesmontemagno/GeolocatorPlugin#142]
## Bug Information

Version Number of Plugin: 4.0.1
Simulator Tested On: Visual Studio Emulator for Android
Version of VS: 15.3
Version of Xamarin: 4.6.0.299 (Android SDK: 7.4.0.21)
Versions of other things you are using: 

### Steps to reproduce the Behavior

In an Android app, call `CrossGeoLocator.Current.IsGeolocationAvailable` and `CrossGeoLocator.Current.IsGeolocationEnabled` without first asking for Location permission.

### Expected Behavior

Return `true` when geolocation is available on the device and enabled.

### Actual Behavior

Both returns `false` until permission is asked and granted.

The result is that it seems to be impossible to reliably determine if positioning is disabled on the device, since determining this requires first being granted the Location permission.

**Comment by jamesmontemagno** [comment]
This is the current expected behavior, it is the only way to actually query the providers for gps.

**Comment by cmeeren** [comment]
Just to be 100% sure - are the following correct?

* If Location permission (form CrossPermission) is not `Granted`, there is no way to find out whether or not GPS is disabled
* Only if Location permission is `Granted`, it actually makes sense to check `IsGeolocationAvailable` and `IsGeolocationEnabled`

**Comment by jamesmontemagno** [comment]
In it's current implementation yes.

I am working on a new implementation that uses the fused locator and someone has suggested some new code to check the enabled state or not. https://github.com/jamesmontemagno/GeolocatorPlugin/blob/android-fused/src/Geolocator.Plugin.Android/GeolocationUtils.cs#L22

This code does seem to be able to be run without permissions though.

Best is to always check permissions first before calling anything.

**Comment by cmeeren** [comment]
Thanks for the tip, that's what I'm currently doing.

Btw, I think the documentation could benefit from mentioning this expected behavior of `IsGeolocationAvailable` and `IsGeolocationEnabled`.

**Comment by jamesmontemagno** [comment]
i will update it :)
