### ISSUE TITLE
UWP app blocked - while initializing?

### ISSUE THREAD

**Issue by cmeeren** [jamesmontemagno/GeolocatorPlugin#145]
Occasionally (I don't know the exact prerequisites), the plugin will freeze the UWP app. While browsing through the code I just came across [these lines](https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin.UWP/GeolocatorImplementation.cs#L54-L58). This seems to be an incorrect implementation - the `Initializing` status, according to [the documentation](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/get-location) (Ctrl-F "Initializing"), means that it's trying to acquire a fix. It seems the lines of code I linked to interpret `Initializing` instead as the whole UWP geolocation engine initializing.

**Comment by jamesmontemagno** [comment]
Do you have a repro of when it would be blocked?

**Comment by cmeeren** [comment]
Sorry, no. Unfortunately I don't have the time to create a minimal working example. In any case, I'm implementing the specific subset of geolocation I need for my purposes now (I found that in order to use this plugin, I needed to fully understand how it worked internally in order to circumvent various odd behaviors, some of which I've reported here, which meant that it's simpler for me just to read the official docs and implement it myself.)

**Comment by jamesmontemagno** [comment]
UWP and the permissions are a bit tricky to be honest with you. I will look into some API changes though.

**Comment by jamesmontemagno** [comment]
Verified that this wont be a problem.

It is always NotInitialized unless you are listening, so really on UWP it doesn't tell you much.
