### ISSUE TITLE
No Access to 'GetPositionsForAddressAsync'

### ISSUE THREAD

**Issue by gquerbes** [jamesmontemagno/GeolocatorPlugin#146]
## Bug Information

Unable to access the GetPositionsForAddressAsync method.

Version Number of Plugin: 4.0.1
Device Tested On: Windows Desktop
Simulator Tested On: NA
Version of VS: 2017
Version of Xamarin: 2.3.4.267
Versions of other things you are using:

### Screenshotst
![image](https://user-images.githubusercontent.com/14299868/29846503-25d8a07e-8ce5-11e7-8190-e6f5cdd570e0.png)

**Comment by jamesmontemagno** [comment]
It's not released yet
