### ISSUE TITLE
Won't run on pre-Lollipop when MultiDex is enabled

### ISSUE THREAD

**Issue by drewlederman** [jamesmontemagno/GeolocatorPlugin#147]
I'm experiencing an issue similar to [this one](https://stackoverflow.com/questions/36502564/xamarin-android-multi-dex-app-with-a-custom-application-class-that-runs-on-pre-l).

My question is: What is the purpose of the `MainActivity` class added by the package? I can see that it manages `CrossCurrentActivity.Current.Activity`, however, I don't see that value actually being used anywhere. Can this class safely be removed?

Thanks.

**Comment by jamesmontemagno** [comment]
The Activity is set so plugins can get access to it. If you safely move this code into each "OnCreate" and "OnResume" of the Activities you have then you can remove it.

Seems like this should be moved to a bugzilla report though.
