### ISSUE TITLE
CrossGeolocator.Current.GetPositionAsync not returns after timeout

### ISSUE THREAD

**Issue by DarkMike82** [jamesmontemagno/GeolocatorPlugin#15]
## Bug

If location is turned on, but user skipped "Improve location accuracy" proposal - call to GetPositionAsync never returns a value. Method simply hangs.
My code is:
var results = await CrossGeolocator.Current.GetPositionAsync(1000);
Even if I use CancellationToken parameter to capture if geolocator cancels this call - nothing happens.

Version Number of Plugin: 3.0.4.0
Device Tested On: Nexus 5, Galaxy S5
### Expected Behavior

CrossGeolocator should inform app about unsuccessful request (e.g. return null, or use method in given CancellationToken)
### Actual Behavior

Method "hangs" - no result, no messages. E.g. in debugger, we simply cannot reach the code beyond this line.
### Steps to reproduce the Behavior

Turn Location Off/On (popup "Improve..." will be shown")
On "Improve location accuracy" popup, press "No"
Try to receive geo-coordinates with GetPositionAsync().

Environment/framework I've used:
Win 10, MSVS2015 with Xamarin 4.0 (Xamarin.Android 6.0)

**Comment by mrbelk** [comment]
I just experienced the same behavior. Once I turned on the "improve location accuracy" switch in the location settings, it returned as expected. This was on a Panasonic Toughpad FZ-X1.

**Comment by DarkMike82** [comment]
Yesterday I've figured some new details.
1) I have this bug on Meizu devices (Android 5.0/5.1) - possibly it is caused by some incorrect/unstandard behavior of Flyme Android (and its Security center).
2) I used CancellationToken as below
`CancellationTokenSource ctsrc = new CancellationTokenSource(2000);
var results = await CrossGeolocator.Current.GetPositionAsync(2000, ctsrc.Token);`
In this case the method returns immediately, without any delay, and the result is null.

**Comment by joanbarros** [comment]
Recently encountered this error and solved it by converting the method I was requesting the location at to async. It was not previously.

Changed the calling method from non-async to async.

No clue....

**Comment by eddnav** [comment]
This is still happening, please change this method to work as expected.

**Comment by mattman624** [comment]
I just came across this problem.

**Comment by hkilimci** [comment]
@mrbelk 's suggestion works for me. Try enabling the "improve location accuracy" from the location settings menu.

**Comment by michelleskothe** [comment]
@joanbarros 's suggestion was the one that worked for me. You have to call the method from an async method.

**Comment by ti994a7** [comment]
I also seems to work in a synchronous method if you call it in a different thread (that way the main thread is not blocked).  For example:

var position = Task.Run(() => CrossGeolocator.Current.GetPositionAsync(TimeSpan.FromSeconds(2))).Result

**Comment by tsantinho** [comment]
Hello community,
I'm using Xamarin Forms 3.2 and Geolocator plugin 4.5.0.6 and i believe that 
this issue is not resolved yet, when you are in house and you not get gps location, then you call GetPositionAsync with any timeout then plugin doesn't return any callback.

Is there anything I'm doing wrong?

I have checked "improve location accuracy" and this option is on, my device is Honeywell CT50 running Android 6.0

**Comment by desenG** [comment]
I experienced this on tablet Samsung Galaxy Tab E-1. @mrbelk 's suggestion works for me
