### ISSUE TITLE
Trouble on Android

### ISSUE THREAD

**Issue by heinst** [jamesmontemagno/GeolocatorPlugin#151]
I added the library and line in `MainActivity.cs`, but when I go to build I get `java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;`, any ideas?

**Comment by jamesmontemagno** [comment]
You need to make sure all of your support libraries are all the same number, you have miss matches. Upgrade your nugets.

**Comment by heinst** [comment]
I have them all on `23.3.0`, and the app runs, but as soon as I add the library I get that error. I cannot update them to what seems like `25.3.1` because I am using Teleriks UI elements

**Comment by jamesmontemagno** [comment]
25.3.1 is required for the latest.
