### ISSUE TITLE
DesiredAccuracy, better explenation.

### ISSUE THREAD

**Issue by D00Minik** [jamesmontemagno/GeolocatorPlugin#152]
Hi. In documentation there is only "This property tells the location managers that it is okay to be X meters off. The default is 100 meters." 
Could someone explain how this setting affect on golocalization?
 Why 100 is a default value?
What mean "that it is okay to be X meters off."?

Thank you.

**Comment by jamesmontemagno** [comment]
It tells the sensors how close you would like to be when gathering the geolocation. So if you set it really low it can take longer to actually query it, and higher means it needs to be less accurate. You can set it to whatever you would like.
