### ISSUE TITLE
IsGeolocationAvailable doesn't exist in the latest version

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/GeolocatorPlugin#155]
I have installed the latest version of this plugin and trying to follow documentation to implement the below method:

```
public bool IsLocationAvailable()
{
    if(!CrossGeolocator.IsSupported)
        return false;

    return CrossGeolocator.Current.IsGeolocationAvailable;
}
```
but IsGeolocationAvailable property is not exist in the current code base. What I am missing something here?

**Comment by prashantvc** [comment]
That's rather strange! I am not able to reproduce this issue. Could you share the full build log? 
Are you using it in a Shared/PCL project?

![image](https://user-images.githubusercontent.com/328076/30531098-a15a881e-9c69-11e7-994a-f7cb4eadadb2.png)

**Comment by jamesmontemagno** [comment]
Yes, what version are you using?

**Comment by jamesmontemagno** [comment]
If you are using the new v4 they are new async methods: https://github.com/jamesmontemagno/GeolocatorPlugin/blob/android-fused/src/Geolocator.Plugin.Abstractions/IGeolocator.cs#L41

**Comment by atinlko** [comment]
hia,
CrossGeolocator.IsSupported is returning false for me, any idea what could be causing this?
