### ISSUE TITLE
Not running on iOS 11

### ISSUE THREAD

**Issue by wallacesantos** [jamesmontemagno/GeolocatorPlugin#158]
Guys

Some of you are getting problems on iOS11? It's not running anymore in this OS. Basically, when enter on code "await CrossGeolocator.Current.StartListeningAsync(...", does not return.

## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: iPhone 7 / iOS11 (iPhone 5 / iOS 10.3.3 runs fine)
Simulator Tested On: iPhone 8 / iOS11 (iPhone 7 / iOS10 runs fine)
Version of VS: VS for Mac, 7.1.5 (Build 2)
Version of Xamarin:
.NET Core
Runtime Versions:
	1.1.1
	1.0.4
SDK Version: 1.0.3

Xamarin.iOS
Version: 11.0.0.0 (Visual Studio Enterprise)
Hash: 152b654a
Branch: xcode9
Build date: 2017-09-15 02:25:56-0400
Versions of other things you are using:

I'm using the same exact code in the sample to start the service. It runs fine on previous versions of iOS, but on version 11 the method StartListeningAsync "does not return":

public async Task StartListening()
        {
            if (CrossGeolocator.Current.IsListening)
                return;
            try
            {
                await CrossGeolocator.Current.StartListeningAsync(TimeSpan.FromSeconds(30), 10, true, new Plugin.Geolocator.Abstractions.ListenerSettings
                {
                    ActivityType = Plugin.Geolocator.Abstractions.ActivityType.Fitness,
                    AllowBackgroundUpdates = true,
                    DeferLocationUpdates = true,
                    DeferralDistanceMeters = 1,
                    DeferralTime = TimeSpan.FromSeconds(5),
                    ListenForSignificantChanges = true,
                    PauseLocationUpdatesAutomatically = false
                });
                CrossGeolocator.Current.PositionChanged += Current_PositionChanged;
            }
            catch (System.Exception ex)
            {
               ...
            }

        }
After call CrossGeolocator.Current.StartListeningAsync start to listen Location services.

Until version 11, no problem.

**Comment by wallacesantos** [comment]
Thank you @alanspires .

In fact I do not observed this new plist: NSLocationAlwaysAndWhenInUseUsageDescription.
I suggest update documentation to show that.

All the best

**Comment by eusebiu** [comment]
For me setting the Location access to "Always" in Settings/Privacy/Location services/AppName did the trick.
