### ISSUE TITLE
How to stop using geolocation on iOS?

### ISSUE THREAD

**Issue by overzealus** [jamesmontemagno/GeolocatorPlugin#159]
Hello. I'm using latest stable version from nuget, and I can't find, how to stop using geolocation, when my doesn't need it anymore?
I'm using StartListeningAsync to start usage of geolocation. When I start using geolocation, there is an arrow appearing in the top of iOS device.
When I don't need it anymore, I call StopListeningAsync, the geolocation arrow is still showing, that means, that my app is still using geolocation services.

**Comment by prashantvc** [comment]
@overzealus When you call the `StopListeningAsync` the app should should tracking gps. Could you provide following details? It will help us to troubleshoot the issue

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Code snippet

**Comment by jamesmontemagno** [comment]
I have noticed that iOS takes about 15-30 seconds to stop showing the icon.
