### ISSUE TITLE
Android: is tracking location in background supported?

### ISSUE THREAD

**Issue by opcodewriter** [jamesmontemagno/GeolocatorPlugin#16]
Android: is tracking location in background supported?

**Comment by jamesmontemagno** [comment]
Background support on Android must be done in a service that is start and stopped by your app that you will have to implement: https://github.com/Azure-Samples/MyDriving/tree/master/src/MobileApps/MyDriving

It is a future enhancement that I am looking into.

**Comment by opcodewriter** [comment]
The MyDriving example is not showing true background location tracking.
I think true background location tracking must work when app is not running at all.

**Comment by jamesmontemagno** [comment]
MyDriving actually does. You can completely close and kill the app and it works just fine :)

I implemented it and covered all scenarios.
