### ISSUE TITLE
Geolocator returns "a task was canceled" on UWP Platform.

### ISSUE THREAD

**Issue by mobiletonster** [jamesmontemagno/GeolocatorPlugin#161]
## Bug Information

Version Number of Plugin:v5.0.0-beta117 and stable 4.0.1
Device Tested On: Lumia 950, SurfaceBook
Simulator Tested On:
Version of VS: VS2017 Preview 15.4.0 Preview 2.0
Version of Xamarin: Xamarin.Forms v2.3.4.270
Versions of other things you are using:
Target Version:Windows 10 Creators Update (10.0; Build 15063)
Minimum Version:Windows 10 November Update (10.0; Build 10586)
Microsoft.NETCore.Universal v5.4.0

### Steps to reproduce the Behavior
In my Xamarin Forms application, from the home screen, I have a button which launches a new screen. The new screen calls the GetPosition() method and invokes the Geolocator code. It almost immediately throws a task canceled exception on UWP. It works fine on Android/iOS.
### Expected Behavior
Coordinates for the current location should appear.

### Actual Behavior
Task canceled exception when ```var position = await locator.GetPositionAsync(timeout: new TimeSpan(30000));``` is hit when on UWP, but works fine in iOS/Android.

### Code snippet
```
public GuestPage ()
		{
			InitializeComponent ();
            GetPosition();
        }

        public async void GetPosition()
        {
            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;
                var isEnabled = await locator.GetIsGeolocationEnabledAsync();
                var isAvailable = await locator.GetIsGeolocationAvailableAsync();
                if (isEnabled && isAvailable)
                {
                    await locator.StartListeningAsync(new TimeSpan(1000), 5000, false);
                    var position = await locator.GetPositionAsync(timeout: new TimeSpan(30000));
                    var lat = position.Latitude;
                    var lng = position.Longitude;
                    this.FindByName<Label>("Coordinates").Text = lat + " " + lng;
                    var result = await locator.StopListeningAsync();
                }
            }catch(Exception e)
            {
                var message = e.Message;
                this.FindByName<Label>("Coordinates").Text = "Unable to locate position. Details: " + e.Message;
            }
        }
```

**Comment by prashantvc** [comment]
@mobiletonster could you share the complete stacktrace from the exception? It will help us to troubleshoot the issue

**Comment by jamesmontemagno** [comment]
Also, why are you calling StartListening and StopListening? Don't do this, only call GetLocationAsync

**Comment by prashantvc** [comment]
@jamesmontemagno could we close this? Sounds like you answered it 🤔

**Comment by joaomissio** [comment]
@jamesmontemagno estou com o mesmo problema no UWP,poderia me ajudar? segue abaixo algumas informações:

**StackTrace:**
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at XamarinGitLabIssue.ViewModels.RegistrarPontoPageViewModel.<ValidarPosicaoAtual>d__14.MoveNext()

**Permissões**
No projeto UWP adicionei a permissão de ID_CAP_LOCATION conforme documentação.

**Codigo Fonte:**
`bool isMetaRecanto = true;
            double tamanhoLocal = 0.029;
            try
            {
                locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50; //Precisão GPS em metros
                var position = await locator.GetPositionAsync(timeout: new TimeSpan(30000));
                double Mylatitude = position.Latitude;
                double Mylongitude = position.Longitude;
                foreach (var item in CoordenadasMetaRecanto)
                {
                    double distanceresult = Haversine.calculate(item.Latitude, item.Longitude, Mylatitude, Mylongitude);
                    if (distanceresult > tamanhoLocal)
                    {
                        await _dialogService.DisplayAlertAsync(Constants.MyAppName, "Sua localização não permite a execução desta funcionalidade!", "OK");
                        isMetaRecanto = false;
                        break;
                    }
                }
            }
            catch (Exception ex)
            {
                isMetaRecanto = false;
                await _dialogService.DisplayAlertAsync(Constants.MyAppName, ex.Message, "OK");
            }
            return isMetaRecanto;`
