### ISSUE TITLE
What happened to AllowsBackgroundUpdates ??

### ISSUE THREAD

**Issue by ablohme** [jamesmontemagno/GeolocatorPlugin#162]
I just updated the plugin and now it throws ALOT of errors regarding AllowBackgroundUpates and that I need TIMESPAN instead of integers in some of the function???

**Comment by prashantvc** [comment]
@ablohme What are these errors are you getting? 
Could you be more specific?

**Comment by jamesmontemagno** [comment]
The API changed as it was a major version bump, please read the documentation. 

AllowBackgroundUpdates is now part of the StartListening API
