### ISSUE TITLE
Error using GetPositionAsync in iOS 10.3.2 and 11.0

### ISSUE THREAD

**Issue by rubenc57** [jamesmontemagno/GeolocatorPlugin#163]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: iPhone 6 plus iOS 10.3.2
Simulator Tested On: iPhone 6 plus iOS 11.0
Version of VS: 2015
Version of Xamarin: 4.7.9.45
Versions of other things you are using:

### Steps to reproduce the Behavior

Just use the GetPositionAsync function to reproduce the error

### Expected Behavior
position should have  my position

### Actual Behavior
in iOS 10.3.2 it return with a null, sometimes an exception
in iOS 11.0 it will stay awating forever

### Code snippet
```
var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = 50;
TimeSpan timeOut = new TimeSpan(1000);// 0);
var position = await locator.GetPositionAsync(timeOut);
```
### Screenshotst
![ios11 0](https://user-images.githubusercontent.com/20931876/30992504-68f83a92-a467-11e7-8cef-adf41e8d503b.png)
![ios10 3 2](https://user-images.githubusercontent.com/20931876/30992516-7be9b93c-a467-11e7-949f-125826ecbe3e.PNG)

**Comment by higher-faster-better** [comment]
I am having same issue in IOS 11
position = await locator.GetLastKnownLocationAsync();
It stays awaititng....

**Comment by prashantvc** [comment]
@rubenc57 @higher-faster-better 

I am not able to reproduce this issue on devices both iSO 11 and 10.3.*
Could you share device logs? It will help us to troubleshoot the issue

**Comment by higher-faster-better** [comment]
After I added NSLocationAlwaysAndWhenInUseUsageDescription to info.plist, error had done. I am getting location now.

**Comment by prashantvc** [comment]
@higher-faster-better it's a new requirement from Apple, glad to hear you figured it out.

@rubenc57 Could you try add the NSLocationAlwaysAndWhenInUseUsageDescription to info.plist? Let me know if it helps

**Comment by jamesmontemagno** [comment]
Yes, this is added to the documentation!

**Comment by rubenc57** [comment]
Sorry for the delay, I was out of my desk for the weekend
I added NSLocationAlwaysAndWhenInUseUsageDescription  and now is working... 
thanks
