### ISSUE TITLE
GetAddressByPosition doesn't work on some android devices

### ISSUE THREAD

**Issue by higher-faster-better** [jamesmontemagno/GeolocatorPlugin#164]
## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: huawei vns-l31

### Expected Behavior
Get Address based on Current location

### Actual Behavior
Failed to Get

### Code snippet
```
        public async Task<string> GetAddressByPosition(Position position)
        {
            string location = "n/a";

			try
			{
				var addresses = await locator.GetAddressesForPositionAsync(position);
				var address = addresses.FirstOrDefault();

                                if (address != null)
					location = address.Locality;
			}
			catch (Exception ex)
			{
				Debug.WriteLine("Unable to get address: " + ex);
			}

            return location;
        }
```

GetAddressesForPositionAsync function works good but failed to get address on some Android phones.
Can you please help me to have solution for this?

Thanks.

**Comment by jamesmontemagno** [comment]
What is your error? They all call the same core code and as  long as they have a geocoder then it works. If they don't have one it won't such as the emulator.

**Comment by higher-faster-better** [comment]
hey, it works on debug mode, But when I build apk for publishing, it doesn't get address.
