### ISSUE TITLE
Providers not updated when permission is revoked/enabled.

### ISSUE THREAD

**Issue by jerrak0s** [jamesmontemagno/GeolocatorPlugin#165]
## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: Motorola Moto G
Simulator Tested On: VS emulator for Android  5'' Marshmallow 6.0.0
Version of VS: 15.3.5
Version of Xamarin: 4.7.9.45

### Steps to reproduce the Behavior
I run the sample code for the plugin with all the necessary permissions described [here](https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html) but in Android plugin does not ask for location permissions at startup. They are disabled by default and I must go in app settings to enable them. In previous versions of plugin, it asked for location permissions for the app.

### Expected Behavior
Plugin should ask location permissions for application.

### Actual Behavior
In iOs and UWP plugin ask for location permissions.

**Comment by jamesmontemagno** [comment]
Did you: 
Android:
You MUST set your Target version to API 25+ and Compile against API 25+

**Comment by prashantvc** [comment]
Adding documentation link for more information. https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/docs/GettingStarted.md#android

**Comment by jerrak0s** [comment]
Target and compile versions are 25++

**Comment by jamesmontemagno** [comment]
Can you share a photo of your settings of target and compile.

**Comment by jamesmontemagno** [comment]
What code are you running?

It calls it here: https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin.Android/GeolocatorImplementation.cs#L142

and works just fine for me.

**Comment by jerrak0s** [comment]
```
  var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 100;
				locationEnabled = true;

                    if (!locator.IsGeolocationEnabled)
                    {                      
                    }
                    else
                    {
                        position = await locator.GetPositionAsync(TimeSpan.FromSeconds(10), null, true);
                        SetMapLocation(position.Latitude, position.Longitude);
                    }
                   
```

**Comment by jamesmontemagno** [comment]
it isn't a new version it is how permissions are handled and you can't get a list of providers until you have permission. So check permissions first before checking geolocation.

**Comment by jamesmontemagno** [comment]
I will put in some advancement in here, but you should always check your own permissions.

**Comment by jamesmontemagno** [comment]
I changed the name for the actual issue. Use the permission plugin to check permissions.

**Comment by brux88** [comment]
i tried, compile e target version 25+ but not work,.
I also need to update the permissions and gelocator packages to the latest version?

**Comment by jamesmontemagno** [comment]
The functionality is correct, if you don't have permission there is no way to check providers and you must check permission. 

It says right here: 
Before making any calls to the geolocator that requires the permissions, you should consider checking that the user has granted proper permission. The geolocator plugin will attempt to ask for permission, but it is not guaranteed.

Use the permissions plugin to check the permissions :)
