### ISSUE TITLE
iOS 11 - GetPositionAsync fails in V4.1.0

### ISSUE THREAD

**Issue by philmoz** [jamesmontemagno/GeolocatorPlugin#167]
## Bug Information
In iOS 11 a user can set the location permission to 'When in Use' even for an app that has requested the 'Always' location update permissions. In this case the app can still get location information when running; but not when in the background.
In the 4.1.0 update the GetPositionAsync method is checking for the LocationAlways permission if the app is configured for background location updates. If the user has changed the permission to 'When in Use' the permission check fails and GetPositionAsync throws an exception. If the app is running in the foreground and has 'When in Use' permission then GetPositionAsync should succeed.

Version Number of Plugin: 4.1.0
Device Tested On: iPhone 6, iOS 11.0.3
Simulator Tested On: iPhone SE, iOS 11.0
Version of VS: 7.2 build 636
Version of Xamarin: 2.4.0.282
Versions of other things you are using:

### Steps to reproduce the Behavior
Configure an iOS app for background location updates, and calls to GetPositionAsync.
Run the app and allow location updates 'Always'. Verify that GetPositionAsync returns the user location.
Change the iOS permission setting to 'When in Use' and run the app - GetPositionAsync now fails.

### Expected Behavior
If the app is in the foreground and has 'When in Use' permission then GetPositionAsync should succeed.

### Actual Behavior
GetPositionAsync fails and throws an 'Unauthorized' exception.

**Comment by jamesmontemagno** [comment]
With iOS 11 you MUST add When In Use even if you have Always set.

See: https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/request_always_authorization

**Comment by philmoz** [comment]
The app has the correct permissions in info.plist, including the new 'NSLocationAlwaysAndWhenInUseUsageDescription' permission.

The app works correctly in foreground and background if the iOS 11 permission is set to 'Always' (in Settings).

If the user changes the Settings permission to 'When in Use' (outside the app) the app should still be able to fall back to foreground only locations.

However your code is only testing for Permission.LocationAlways if it thinks the app is configured with background location updates, therefore it is no longer possible to get location with GetPositionAsync when running in the foreground - even though the app should have permission.

Relevant code from GetPositionAsync:
`			// permit background updates if background location mode is enabled
			if (UIDevice.CurrentDevice.CheckSystemVersion(9, 0))
			{
				var backgroundModes = NSBundle.MainBundle.InfoDictionary[(NSString)"UIBackgroundModes"] as NSArray;
				var allowBack = backgroundModes != null && (backgroundModes.Contains((NSString)"Location") || backgroundModes.Contains((NSString)"location"));
				if (allowBack)
					permission = Permission.LocationAlways;    <<<<<< 
				else
					permission = Permission.LocationWhenInUse;
			}
`

**Comment by philmoz** [comment]
For an app that uses background location updates, consider the following behaviours (screenshot attached) that are allowed in iOS11, I have highlighted the scenario where I believe V4.1.0 is incorrect.
![screen shot 2017-10-12 at 5 55 21 pm](https://user-images.githubusercontent.com/9474356/31483127-d2527b96-af76-11e7-9255-ce2c34ef99c7.png)

**Comment by jamesmontemagno** [comment]
Fixed in 4.1.1

**Comment by thearaks** [comment]
Is it possible that I'm still experiencing this in 4.1.1?

**Comment by PureWeen** [comment]
I am. I upgraded this and permissions yesterday and it still gave me the exception about permissions not being set correctly so I downgraded for now.   Haven't had a chance to poke around much more than that though

**Comment by mxstudios** [comment]
So does it work with the When in Use on the downgraded version? This is a production app and we have users who now choose "When in Use" when it wasn't available before, and the app just doesn't work anymore. We are preparing a fix, but I don't know how. If I abandon the plug-in we will have to go through weeks of testing and release...

Apple really screwed us on this one...

**Comment by jamesmontemagno** [comment]
You can try: 4.1.2.167-beta as it has a lot of enhancements in it for this use case.

**Comment by jamesmontemagno** [comment]
It is simple.... you can use the Permissions Plugin and check for Always permission yourself first. Then you can force your users to do it. This library can only be so smart and attempt to figure things out, but you just need to use the PermissionPlugin and request LocationAlways and if they don't grant it then they can't use the geolocation.

Some more info:
https://blog.xamarin.com/plugin-permission-changes-ios-11/

**Comment by PureWeen** [comment]
@mxstudios  I haven't tested "4.1.2.167-beta" yet so maybe that resolves but currently

I have 
"NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription" 
set

And Version 2.0.1 of Plugin.Permissions and 4.0.1 of Geolocator installed into the iOS platform project and AFAICT those are currently working fine for me on iOS 11 devices

**Comment by jamesmontemagno** [comment]
@PureWeen 

You don't need NSLocationAlwaysAndWhenInUseUsageDescription  if you ONLY are using When In Use.

You only need to add that if you have NSLocationAlwaysUsageDescription set

**Comment by PureWeen** [comment]
yea? Alright I'll give that I try

I was having issues with ios 11 and found this SO post
https://stackoverflow.com/questions/44424092/location-services-not-working-in-ios-11

Which seems to suggest there's some issues with ios documentation vs reality :-) so I just ended up setting both

**Comment by mxstudios** [comment]
Thanks for all the feedback. I'll give it a try with the beta.

**Comment by mxstudios** [comment]
Still getting a TaskCanceledException no matter what I do.

**Comment by PureWeen** [comment]
@jamesmontemagno   so is the guidance on the blog here not correct then? It seems to be saying the opposite of what you're suggesting. 

https://blog.xamarin.com/plugin-permission-changes-ios-11/

> Developers are required to include both NSLocationWhenInUseUsageDescription and NSLocationAlwaysAndWhenInUseUsageDescription in their info.plist file with iOS 11. Most developers will want to support earlier versions of iOS as well, which means you’ll need to also include a third key, NSLocationAlwaysUsageDescription.

**Comment by ibraun88** [comment]
Hey @jamesmontemagno , 

i currently use your Plugins Xam.Plugin.Geolocator(4.5.0.6) and Plugin.Permissions(3.0.0.12). I want to get the location changes in background(if user gives permission always) and in foreground(if user gives permission when in use). I have the same scenario which philmoz already described. If the user selects the permission "When in use" Geolocator crashs with an Unauthorized exception! 
I checked the permission status of permission LocationWhenInUse and its granted.

plist configuration:

<key>NSLocationWhenInUseUsageDescription</key>
<key>NSLocationAlwaysUsageDescription</key>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<key>UIBackgroundModes</key>
<array>
		<string>location</string>
</array>

Are there any news on this topic?

![image](https://user-images.githubusercontent.com/48519349/54284565-7914c900-45a0-11e9-97cb-e6b8ba9dba73.png)
![image](https://user-images.githubusercontent.com/48519349/54284595-87fb7b80-45a0-11e9-8498-cd31341661d6.png)

**Comment by ibraun88** [comment]
@philmoz 
Have you found a solution or a workaround for the problem?

**Comment by chrisfoulds** [comment]
My advice is use the permissions plugin, get everything from the user yourself and make sure they have agreed and then start the plugin.

**Comment by ibraun88** [comment]
@chrisfoulds 
thanks for your suggestion. I already use the permission plugin and request permission from user. Initially I ask for Location where user can select between WhenInUse, Always and never. Every time I need to get the location I check if the user has permission before using GetPositionAsync method. Do you have some sample code?

**Comment by chrisfoulds** [comment]
Not that I can share.
I simply request the permissions I need, if granted start the app. Then on each launch check them again and if they fail bring up a holding screen with instructions. 
I don't request always however as most users will not grant that , I only use location when in use and then use background modes.

**Comment by ibraun88** [comment]
@chrisfoulds 
Is it enough to get location changes in background when user give permission "WhenInUse", key UIBackgroundMode location is set in info.plist and property AllowBackgroundUpdates of ListenerSettings class is set to true?

Thanks for your help so far!

**Comment by chrisfoulds** [comment]
Works for me with my app , also just install a running app. None of those ask for always, they only ask for when in use.
