### ISSUE TITLE
Kalman Filter

### ISSUE THREAD

**Issue by rizaanlakay** [jamesmontemagno/GeolocatorPlugin#168]
Anyone know if there is any libraries with sample code of how to apply the Kalman Filter to the results from the GPS location? I'm wanting to smooth the location data so it's not as scattered as the raw GPS data.

Would be super cool if the geolocator had a Kalman filter built into it :) (optional offcourse)

**Comment by jamesmontemagno** [comment]
There are helper functions to help calculate distances. The new versions also have ways of removing signal types you don't want and 5.0 has fused locator in it.
