### ISSUE TITLE
Getting mutliple PositionChanged for same location for Android

### ISSUE THREAD

**Issue by MihaMarkic** [jamesmontemagno/GeolocatorPlugin#170]
## Bug Information

Version Number of Plugin: 4.1.1, 4.0.1
Device Tested On: Nexus 6
Simulator Tested On: Android 6
Version of VS:  2017 15.4
Version of Xamarin: 15.4
Versions of other things you are using:

### Steps to reproduce the Behavior

call StartListeningAsync and they you'll get an call to PositionChanged event for each provider. For example, I see that Manager.GetProviders(enabledOnly: false) would return passive and gps providers. And when changing location (both in simulator and device) I'll get two PositionChanged events.
Is there a way to specify which provider to use instead?

### Expected Behavior

One event call for a location.

### Actual Behavior

An call for each provider.

**Comment by jamesmontemagno** [comment]
In the next version (in pre-release) you can: https://github.com/jamesmontemagno/GeolocatorPlugin/blob/android-fused/src/Geolocator.Plugin.Android/GeolocatorImplementation.cs#L48

The next version uses the fused locator as well.
