### ISSUE TITLE
timeoutmilliseconds parameter not working

### ISSUE THREAD

**Issue by musman96** [jamesmontemagno/GeolocatorPlugin#171]
Hi, im having problems using the plugin. it gives me errors when i use a recent version or version 4+. i tried using version 3.0.4, it worked in that it didn't give me any errors but what would happen is that the application would enter into break mode and not tell me what the problem was.

please help as I am not sure of how to proceed from here.

Thanks.

## Bug Information

Version Number of Plugin:4.1.1
Device Tested On:  android 6.0 marshmallow
Simulator Tested On: android 6.0 marshmallow
Version of VS: 2017
Version of Xamarin: 4.7
Versions of other things you are using: xamarin.forms version 2.4.0

### Code snippet
        private async void BtngetLocation_Clicked(object sender, EventArgs e)
        {
         var locator = CrossGeolocator.Current;
         locator.DesiredAccuracy = 50;

         var position = await locator.GetPositionAsync(timeoutMilliseconds: 10000);
        }
### Screenshotst
![errors](https://user-images.githubusercontent.com/27110007/31864584-0b4e49ca-b760-11e7-9fc7-09a241f347fe.png)

**Comment by jamesmontemagno** [comment]
It is now a TimeSpan... so TimeSpan.FromSeconds(10)
