### ISSUE TITLE
Method 'Plugin.Geolocator.Abstractions.IGeolocator.GetLastKnownPositionAsync' not found. on Android

### ISSUE THREAD

**Issue by mamnarock** [jamesmontemagno/GeolocatorPlugin#172]
## Bug Information

Version Number of Plugin: 4.1.1
Device Tested On: Samsung Galaxy J1
Simulator Tested On:
Version of VS: Visual Studio for Mac 7.2 (build 636)
Version of Xamarin:  8.0.0.33 (Visual Studio Community)
Versions of other things you are using:

### Steps to reproduce the Behavior
CrossGeolocator.Current.GetLastKnownPositionAsync();
### Expected Behavior
get las position
### Actual Behavior
Method 'Plugin.Geolocator.Abstractions.IGeolocator.GetLastKnownPositionAsync' not found.

**Comment by jamesmontemagno** [comment]
Update all your nugets and ensure you do a clean and rebuild.
