### ISSUE TITLE
Getting latitude and longitude different for the same spot and same device

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/GeolocatorPlugin#174]
## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: Micromax Q427
Version of VS: VS2017 
Version of Xamarin.Forms:2.3.5.256pre6

### Steps to reproduce the Behavior
In my app users get latitude and longitude of his/her device for some locations and stored as a master data into the database.
### Expected Behavior
For the same spot user's device location should match with the master data that already has been stored 
for the same spot and same device.
### Actual Behavior
Though latitude and longitude has been stored from same device and same spot but in the second time location doesn't match. 
For example:
Old latitude & longitude:
Latitude   28.9636535
Longitude  77.5687512
 
New Latitude & Logitude:
Latitude  28.9642304
Longitude 77.5862966
### Code snippet
```
public static async Task<Position> GetDeviceCurrentLocation()
        {
            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;

                var position = await locator.GetPositionAsync(TimeSpan.FromSeconds(1));

                if (position != null)
                {
                    return position;
                }
            }
            catch (Exception ex)
            {
                DisplayAlertMessage("", "Please enable your device location.");
                Debug.WriteLine("Unable to get location, may need to increase timeout: " + ex);
            }

            return new Position();
        }
```

**Comment by jamesmontemagno** [comment]
You get whatever is returned by the device. Geolocation can only be so accurate.

**Comment by ShahriatHossain** [comment]
"Geolocation can only be so accurate" didn't get it well. And do I need to change anything in my method above to be accurate minimum 3rd decimal points?

**Comment by jamesmontemagno** [comment]
You can adjust the Minimum Distance and timeouts to get more precise readings.

**Comment by ShahriatHossain** [comment]
what should be the appropriate timeouts for 100 meters accuracy?
