### ISSUE TITLE
Error in getting simple longitude and latitude 

### ISSUE THREAD

**Issue by deanilvincent** [jamesmontemagno/GeolocatorPlugin#175]
## Bug Information

Version Number of Plugin: 4.1.1
Device Tested On: Android
Simulator Tested On: Android
Version of VS: 15.4
Version of Xamarin: Latest
Versions of other things you are using: -

### Steps to reproduce the Behavior
I just simply implementing  CrossGeolocator.Current; and suddenly the application throws an error.
### Expected Behavior
Expected behavior should display string value of longitude and latitude value to string
### Actual Behavior
The break point stop on var position
### Code snippet
```
try
{
    var locator = CrossGeolocator.Current;
    var position = await locator.GetPositionAsync(TimeSpan.FromMilliseconds(20), null, true);

     LabelCurrentLocation.Text = position.Longitude.ToString() + position.Latitude.ToString();
}
catch (Exception ex)
{
      var checkError = ex.Data.ToString();
}
```
### Screenshotst
![checkerror](https://user-images.githubusercontent.com/10904957/31949063-fb8e0f14-b90a-11e7-8dec-f04bf1bc2d6a.png)

Exception Details

```
{System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00026] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at Plugin.Geolocator.GeolocatorImplementation+<GetPositionAsync>d__33.MoveNext () [0x0042a]
```

**Comment by jamesmontemagno** [comment]
Looks like it timed out. Are you running on a device? If you are on an emulator you need to push the location to the emulator in the settings.

**Comment by deanilvincent** [comment]
@jamesmontemagno Yes sir, I'm using android emulator. I'll check the GPS there. And I'm also using Xamarin Live Player with connected physical android device. But I get error there. :)

**Comment by higher-faster-better** [comment]
hi
I tested on both android devices, Samsung and Huawei but the app keeps exception like above mentioned.
Please help me to fix.

**Comment by higher-faster-better** [comment]
![screen shot 2017-11-07 at 16 39 57](https://user-images.githubusercontent.com/26017443/32484370-7f30515e-c3da-11e7-9f83-a13c1d7dfcdf.png)
It's related to this setting?

**Comment by deanilvincent** [comment]
What I did was what @jamesmontemagno said, just turn on the GPS in your emulator :)

**Comment by higher-faster-better** [comment]
@deanilvincent I tried it too but unfortunately not work :(
