### ISSUE TITLE
Can you add LocationWhenInUse permission on StartListeningAsync method? (iOS)

### ISSUE THREAD

**Issue by crgabo** [jamesmontemagno/GeolocatorPlugin#176]
StartListeningAsync is not working with "When In Use" Permission. Is it compulsory to set LocationAlways permission or you can include LocationWhenInUse in the permission checking

![screen shot 2017-10-25 at 11 04 22 am](https://user-images.githubusercontent.com/6674255/32012646-ce82a500-b975-11e7-9094-e7868ef88c02.png)
?

**Comment by jamesmontemagno** [comment]
Yes, good catch.

I am going to change it to:

```csharp
#if __IOS__

			var permission = Permission.Location;
			if (UIDevice.CurrentDevice.CheckSystemVersion(9, 0))
			{
				if (listenerSettings.AllowBackgroundUpdates)
					permission = Permission.LocationAlways;
				else
					permission = Permission.LocationWhenInUse;
			}

			var hasPermission = await CheckPermissions(permission);


			if (!hasPermission)
				throw new GeolocationException(GeolocationError.Unauthorized);
#endif
```

**Comment by jamesmontemagno** [comment]
Try: 4.1.1.159-beta

**Comment by crgabo** [comment]
4.1.1.159-beta is working well if I only need LocationWhenInUse permission. Thank you.
I didn't test it for LocationAlways.

**Comment by m3mo89** [comment]
if you configure LocationWhenInUse and send AllowBackgroundUpdates as true, then the validation replaces the LocationWhenInUse permission with LocationAlways, then when you check the permission throw GeolocationException.

this is somewhat confusing, what defines the behavior then is the value of AllowBackgroundUpdates?

**Comment by jamesmontemagno** [comment]
Yes as that can not be set to true if you don't have proper permission. It is best that you handle permissions yourself. The plugin can only do so much.
