### ISSUE TITLE
StartListening iOS Permissions

### ISSUE THREAD

**Issue by po-connor** [jamesmontemagno/GeolocatorPlugin#177]
Hi,
Is it possible to change the permission check in StartListening ios implementation from Permission.LocationAlways to Permission.Location ?
I find it weird to ask the users the permission to access their location when not using the app if I'm not going to do it.
Thanks

**Comment by jamesmontemagno** [comment]
Already closed and will be in 4.1.2 https://github.com/jamesmontemagno/GeolocatorPlugin/issues/176
