### ISSUE TITLE
GetPositionAsync throws Exception: Position unavailable on Samsung Galaxy S5 Mini

### ISSUE THREAD

**Issue by SamuelDebruyn** [jamesmontemagno/GeolocatorPlugin#18]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: Samsung Galaxy S5 Mini
Simulator Tested On: /

### Expected Behavior
Get GPS coordinates.

### Actual Behavior
Throws exception with `Position unavailable`

### Steps to reproduce the Behavior

Just call `var location = await CrossGeolocator.Current.GetPositionAsync(20000);`

Also happened in https://play.google.com/store/apps/details?id=com.refractored.testappforms

**Comment by SamuelDebruyn** [comment]
Also happens on an LG Nexus 4. Both devices have the latest available updates which is Android 5.1.1 on both devices.

**Comment by jamesmontemagno** [comment]
I do not handle device specific issues as it is the same code to run on all devices.

**Comment by SamuelDebruyn** [comment]
Is it still device specific if it also happens on a Nexus 4? I guess it's tied to the Android version and not to the device per se...

**Comment by jamesmontemagno** [comment]
I have 5.1.1 on my Nexus 6 and no issues at all.

**Comment by jamesmontemagno** [comment]
You could go down the route of trying to use the Google Play Services geolocator. In the future I want to update to use that.
