### ISSUE TITLE
Locality returning Town. I need City instead

### ISSUE THREAD

**Issue by savasmurat** [jamesmontemagno/GeolocatorPlugin#181]
Hi James,

ReverseGeocodeLocationAsync is returning Town name in Locality property. Is there a was to get the City name instead of Town?

Thank you

**Comment by jamesmontemagno** [comment]
What platform?

**Comment by savasmurat** [comment]
Xamarin iOS

**Comment by jamesmontemagno** [comment]
Here is your API: 
https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin.iOSUnified/GeolocationUtils.cs

vs 

https://developer.apple.com/documentation/corelocation/clplacemark

we return locality, which is the city associated with it.
