### ISSUE TITLE
[FEATURE] Add IsFromMockProvider (or similar name) to Position object 

### ISSUE THREAD

**Issue by MDueh** [jamesmontemagno/GeolocatorPlugin#183]
[FEATURE] On Android, a Location object has the IsFromMockProvider property, would it be possible to carry/include that on the Position object as well? 

If other platforms than Android don't have the possibility of GPS positions being from mock providers, then maybe Position.IsFromMockProvider could be nullable and set to null for those or just set to False (if nullable is undesirable).

**Comment by jamesmontemagno** [comment]
No plans to do this

**Comment by MDueh** [comment]
Alright, bummer - it was a nice plugin though. I'll just write a small warning below, so other developers maybe wont get as far as me using the plugin, before realizing the functionality is missing.

WARNING! If you are developing an App (for Android) that needs to do as much as possible to ensure the positions are coming from the GPS and not from a simulator App running in the background, the GeolocatorPlugin is not ideal.
