### ISSUE TITLE
[Question] Android API version compatibility

### ISSUE THREAD

**Issue by agouriou** [jamesmontemagno/GeolocatorPlugin#184]
Hi,

Thanks for this plugin. The README.md says that Android API 14+ is supported. However, the getting started says 

> You MUST set your Target version to API 25+ and Compile against API 25+

Why this difference? Which level of Android API is supported?

Thanks

**Comment by jamesmontemagno** [comment]
This is your compile and target, not minimum. 

Watch this: https://channel9.msdn.com/Shows/XamarinShow/Snack-Pack-11-Understanding-Android-API-Level-Settings
