### ISSUE TITLE
Problem with speed

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#188]
Hi,

I'm using this library inna Xamarin PCL project where I need to detect position and speed.
I used the library inside an Android service but what I noticed is that lot of times (not always but really often) the detected speed value is always 0.

I can't imagine why as I'm calling the "GetPositionAsync" including headers. I also read some documentation that talk about GPS and NETWORK provider and that usually the GPS one is more suitable for detecting speed.

Is this true? If yes how can I ask the plugin to use GPS provider explicitly?

Any other idea on a to solve? Unfortunately speed value is really important in my project and without it I cannot proceed anyway.

Thanks for your help!

**Comment by prashantvc** [comment]
GPS provider is the most accurate provider, however it works best in the outdoors, slow, and consumes quite a lot of battery. So, we try to use combination of all the available sensors on the device. It will be lot of refactoring if you want just use GPS. If you decided to do so, fork the code and  pass the `LocationManager.GpsProvider` to `RequestLocationUpdates` method calls

https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin.Android/GeolocatorImplementation.cs#L304-L305

**Comment by jamesmontemagno** [comment]
I have added in two new static string arrays you can set.

ProvidersToUse and ProvidersToUseWhileListening

When you set these they limit the providers to only this set. Will be in next beta.

**Comment by sayed-seliman** [comment]
Really really thanks!
When do you plan to deliver next beta? And when it can be considered stable for production use?

Thanks again

**Comment by jamesmontemagno** [comment]
it is already live. It only has this change so if you test it out, there would be no changes to the final package.

**Comment by jamesmontemagno** [comment]
You are looking for: 4.1.3.174-beta

**Comment by sayed-seliman** [comment]
what are string possible values for providers?

**Comment by jamesmontemagno** [comment]
Look in: https://developer.android.com/reference/android/location/LocationManager.html

**Comment by sayed-seliman** [comment]
So it's available only for Android? on iOS it's not possible to specify which provider to use?
I also noticed that when in background on iOS, even if I have asked for location update while in background, position is often not provided.

I also listed in the info.plist for

<key>NSLocationAlwaysUsageDescription</key>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<key>NSLocationWhenInUseUsageDescription</key>

**Comment by jamesmontemagno** [comment]
It is only available on Android as it is the only one that provides the API.

iOS is very difficult and you need a lot of settings: https://jamesmontemagno.github.io/GeolocatorPlugin/BackgroundUpdates.html

**Comment by sayed-seliman** [comment]
Hi,

I added this

Plugin.Geolocator.GeolocatorImplementation.ProvidersToUse = new string[] { "GPS_PROVIDER" };
Plugin.Geolocator.GeolocatorImplementation.ProvidersToUseWhileListening = new string[] { "GPS_PROVIDER" };

but with this no position is detected. What is wrong?

Thx

**Comment by jamesmontemagno** [comment]
That isn't the string, it is "gps": https://developer.android.com/reference/android/location/LocationManager.html#GPS_PROVIDER
