### ISSUE TITLE
compass calibration screen

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#189]
Hi,

is it possible to disable the compass calibration on iOS?
I'm referring to this one but I cannot find this property on the plugin

https://developer.xamarin.com/api/member/MonoMac.CoreLocation.CLLocationManagerDelegate.ShouldDisplayHeadingCalibration

Thanks

**Comment by jamesmontemagno** [comment]
There is only a get, never a set. It is pretty annoying, but out of control of the app from what I have always seen.

**Comment by sayed-seliman** [comment]
so there is no way to disable? I'm asking for that because on iPhone 6 and 7 it's continuosly asking for me to calibrate, also if I already done it more and more time.
I would need to definitely disable it.

Any suggestion?

**Comment by jamesmontemagno** [comment]
Look in: https://developer.android.com/reference/android/location/LocationManager.html

**Comment by jamesmontemagno** [comment]
No idea

**Comment by sayed-seliman** [comment]
can you just indicate which is the "readonly" property on the plugin?

**Comment by jamesmontemagno** [comment]
going to re-look at the delegate

**Comment by rohitvipin** [comment]
You can set it on the location manager you use within the framework, if this is not possible from the plugin maybe exposing the location manager can help use overriding it.

```
var locationManager = new CoreLocation.CLLocationManager();            
locationManager.ShouldDisplayHeadingCalibration += (CoreLocation.CLLocationManager manager) => {return false;};
```
