### ISSUE TITLE
Xam.Plugin.Geolocator making application crash on Android version 7

### ISSUE THREAD

**Issue by mansi1929** [jamesmontemagno/GeolocatorPlugin#190]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:4.0.1
Device Tested On: Google nexus
Simulator Tested On:
Version of VS: 7.1
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
This plugin works smoothly upto android version 6 but for 7 it is making the app to crashing stating a task was cancelled.I am checking for all the relevant permissions beforehand.
### Code snippet
var locator = CrossGeolocator.Current;

			locator.DesiredAccuracy = 50;
			var position = await locator.GetPositionAsync(TimeSpan.FromSeconds(3));

			if (position == null)
			{
				UserDialogs.Instance.Alert("App needs location to enabled to proceed further", "Alert", "Ok");

				return;
			}

**Comment by jamesmontemagno** [comment]
Did you put this in a try catch? it is possible it throws an exception.
