### ISSUE TITLE
iOS Background updates

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#192]
Hi,

I'm using the plugin on a Xamarin PCL project.
I have no problem with Android, while on iOS on which I need background updates I'm getting lot of problem with battery usage.
In order to get background updates I'm using this configuration

locator.StartListeningAsync(TimeSpan.FromMilliseconds(20000), 0, false, new Plugin.Geolocator.Abstractions.ListenerSettings
                        {
                            ActivityType = Plugin.Geolocator.Abstractions.ActivityType.AutomotiveNavigation,
                            AllowBackgroundUpdates = true,
                            DeferLocationUpdates = true,
                            DeferralDistanceMeters = 200,
                            DeferralTime = TimeSpan.FromSeconds(1),
                            ListenForSignificantChanges = false,
                            PauseLocationUpdatesAutomatically = false
                        });

The problem is ListenForSignificantChanges. If I set this property to TRUE I don't receive updates every 20seconds but it always return me the same position (maybe cached position?) while if I set this property to FALSE I receive continuos updates that use too much battery.
How can I set the plugin on iOS correctly in order to get an updated position (with speed) every 20 seconds also when in background?

Thank you

**Comment by jamesmontemagno** [comment]
See: https://developer.apple.com/documentation/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati
