### ISSUE TITLE
Didn't find class "md5b6a73f2b5f0d449426e9b529d0319f20.GeolocationSingleListener"

### ISSUE THREAD

**Issue by rubenmamo** [jamesmontemagno/GeolocatorPlugin#193]
I'm getting the following exception when I try to use GetPositionAsync in an Android App with Xamarin Forms:
**Didn't find class "md5b6a73f2b5f0d449426e9b529d0319f20.GeolocationSingleListener"**
I'm not sure whether I'm doing something incorrectly or whether this is an issue with the library.

AFAIK I've followed the readme correctly and setup the required permissions and targets.

I'm using the following:
* Xam.Plugin.Geolocator v 4.1.3
* Xamarin.Forms v2.5.0.121934
* Xamarin.Forms.Maps v2.5.0.121934
* Xamarin.Android.Support.Design v25.4.0.2
* Xamarin.Android.Support.v7.AppCompat v25.4.0.2
* Xamarin.Android.Support.v4 v25.4.0.2
* Xamarin.Android.Support.v7.CardView v25.4.0.2
* Xamarin.Android.Support.v7.MediaRouter v25.4.0.2

**Comment by rubenmamo** [comment]
The problem has gone away, however i'm unsure what solved it. I did the following changes recently:
* Updated Visual Studio to 15.5.2
* Changed to use Navigation Pane

**Comment by prashantvc** [comment]
Please attach a sample project and reopen if you hit this issue again. Thanks :)
