### ISSUE TITLE
GetPositionAsync() kept throwing exception on iOS

### ISSUE THREAD

**Issue by VictorK1902** [jamesmontemagno/GeolocatorPlugin#194]
This is not an issue in Android

## Bug Information

Version Number of Plugin: 5.0.0.175-beta
Device Tested On: iPhone 8 plus 256 gb
Simulator Tested On: 
Version of VS: 2015
Version of Xamarin: 2.4.0.280
Versions of other things you are using: Plugin.Permision 2.1.0

### Steps to reproduce the Behavior - Code snippets

    async Task LocationPermissionCheck() {
        var permissionStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
        if (permissionStatus != PermissionStatus.Granted) {
            var reqPerStatus = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
            if (reqPerStatus[Permission.Location] != PermissionStatus.Granted) {
                await Acr.UserDialogs.UserDialogs.Instance.AlertAsync("Location permission is required....");
                CrossPermissions.Current.OpenAppSettings();
                return;
            } else {
                StartPositionTimer();
            }
        }
        else {
            StartPositionTimer();
        }                
    }    
    
    async Task StartPositionTimer() {
        if (await IsLocationAvailable()) {
            while (true) {
                await CheckPosition();
                await Task.Delay(System.TimeSpan.FromMinutes(3));
            }
        } else {
            Acr.UserDialogs.UserDialogs.Instance.Alert("GeoLocation is not available or enabled. Please enable location access and try again.");
            return;
        }
    }    
    
    
    async Task CheckPosition() {    
        Plugin.Geolocator.Abstractions.Position position = null;
        try {
            var locator = CrossGeolocator.Current;
            locator.DesiredAccuracy = 100;

            var temp = await locator.GetPositionAsync(TimeSpan.FromSeconds(30), null, true);
            position = temp;

        } catch (Exception ex) {
            App.CurrentLatitude = "";
            App.CurrentLongitude = "";
            Xamarin.Insights.Report(ex);
            return;
        }

        App.CurrentLatitude = position.Latitude.ToString();
        App.CurrentLongitude = position.Longitude.ToString();
    }
### Expected Behavior

    var temp = await locator.GetPositionAsync(TimeSpan.FromSeconds(30), null, true);

is supposed to run at least 30s before being timed out but an exception is thrown immediately there saying:

    On iOS 8.0 and higher you must set either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in your Info.plist file to enable Authorization Requests for Location updates!

### Actual Behavior

An exception is thrown immediately there saying:

    On iOS 8.0 and higher you must set either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in your Info.plist file to enable Authorization Requests for Location updates!

I have all the permissions needed in info.plist

    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Location access is required .....</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Location access is required .....</string>

The prompt shows up when app launches first time, asking for permission and I tapped allow. Checked in general setting and it shows location access permission correctly. 

### Screenshotst

![alt text](https://i.imgur.com/eWb2iwm.jpg)

**Comment by jamesmontemagno** [comment]
Please read through: https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html

**Comment by VictorK1902** [comment]
@jamesmontemagno : I already read it and setup my info.plist as I stated above:

    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Location access is required .....</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Location access is required .....</string>

I'm not sure what I'm missing here

**Comment by VictorK1902** [comment]
The guide said 

![image](https://user-images.githubusercontent.com/9853294/34182436-dcabe1be-e4db-11e7-906d-9f0e9497e63e.png)

So I put only those 2 above. Eventually I tried adding the following: 

    <key>NSLocationAlwaysUsageDescription</key>
    <string>Location access is required .....</string>

Now info.plist looks like this

    <key>NSLocationWhenInUseUsageDescription</key>
    <string>Location access is required .....</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Location access is required .....</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>Location access is required .....</string>

Now it's working.

**Comment by jamesmontemagno** [comment]
That is what exactly the guide says... you can use one OR the other... and then under iOS 11 it tells you you have to put all 3

**Comment by VictorK1902** [comment]
I guess I misread this part somehow:

    ...(If your app supports iOS 10 and earlier, the NSLocationAlwaysUsageDescription key is also required.)...

My apology
