### ISSUE TITLE
Android version unable to stop listening for position change

### ISSUE THREAD

**Issue by SuhanKoh** [jamesmontemagno/GeolocatorPlugin#195]
Android version unable to stop listening for position change.

## Bug Information

Version Number of Plugin: 4.1.3
Device Tested On: Samsung S7

### Steps to reproduce the Behavior
Call StartListeningAsync, then wait for about 30 seconds then call StopListeningAsync.

### Expected Behavior
Java implementation/Xamarin.Android implementation should not have RunTimeException.

### Actual Behavior
Unhandled Exception
"Java.Lang.RuntimeException: invalid listener: null"

**Comment by jamesmontemagno** [comment]
do you have a stack trace? I can't reproduce this.

**Comment by SuhanKoh** [comment]
I cannot reproduce this anymore, hence I am closing this. What I did was turned off location and turned back on, this issue is no longer reproducible.
