### ISSUE TITLE
Location Permission Not Set for App on Android

### ISSUE THREAD

**Issue by TonyLugg** [jamesmontemagno/GeolocatorPlugin#196]
Using Geolocator 4.1.3 and Permissions 2.1.0.  When my app is installed on iOS or UWP, the OS asks the user if location services can be enabled and does so.  On Android, the OS does not request the user's permission, and the user has to manually go to Settings and enable location services for the app (device location services are already enabled).

I have the permission override in the main activity according to the Goelocator documentation.  This issue causes many help requests from users.  Is it possible to configure the app/geolocator to automatically set the location permission for the app?

**Comment by prashantvc** [comment]
>  On Android, the OS does not request the user's permission

Could you share more information about the device you're using? (like Android OS, manufacturer)

**Comment by TonyLugg** [comment]
I'm now targeting Android 8.  The issue seems to be with all devices.  I mainly test with Pixel these days.  Is there a way to set the app's location permission in configuration or during installation or initial startup?

**Comment by jamesmontemagno** [comment]
What is your Target set to? It must manually be set to the specific version. You can NOT use the "use compile version" as it doesn't set information in the manifest.

**Comment by jamesmontemagno** [comment]
If you have it set below then 2.2.1 of permission plugin takes this into consideration. i am updating the plugin to rely on this new version.

**Comment by TonyLugg** [comment]
Target Android version: Android 8.0 (API Level 26 - Oreo).  What do you mean by your last statement?

**Comment by jamesmontemagno** [comment]
Can you show me a screenshot of all your settings.

**Comment by TonyLugg** [comment]
[ScreenShots.pdf](https://github.com/jamesmontemagno/GeolocatorPlugin/files/1604752/ScreenShots.pdf)

**Comment by jamesmontemagno** [comment]
I just ran my tests with these settings and working correct for me. What NuGet packages are you using?

**Comment by TonyLugg** [comment]
Xam.Plugin.Geolocator: 4.1.3
Plugin.Permissions:  2.1.0

I'll try your updates and see how it goes.

**Comment by jamesmontemagno** [comment]
Can you list me ALL of the nuget dependencies for the android support libraries. This is what I am interested in.

**Comment by TonyLugg** [comment]
Attached is the csproj file (zipped)

[VDIS.XF.Android.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/1604845/VDIS.XF.Android.zip)

**Comment by TonyLugg** [comment]
I update your packages.  Did a factory reset on the Pixel emulator but no luck.  Settings seem to be cached on the physical Pixel between uninstall and redeployment.

**Comment by jamesmontemagno** [comment]
I ran the sample on a pixel api 26 emulator and worked great

![image](https://user-images.githubusercontent.com/1676321/34589595-704db956-f166-11e7-85d9-2b32b21309f6.png)

**Comment by TonyLugg** [comment]
I don't get that popup at all.  In the following code, both IsGeolocationAvailable and IsGeolocationEnabled are false unless I use the Settings app to set the location permission for the app:

```
        public static async Task<Plugin.Geolocator.Abstractions.Position> GetCurrentLocation()
        {
            try
            {
                var loLocator = CrossGeolocator.Current;
                loLocator.DesiredAccuracy = 5;
                if (!loLocator.IsGeolocationAvailable && !loLocator.IsGeolocationEnabled)
                {
                    await App.Current.MainPage.DisplayAlert(AppResources.GetCurrentLocationTitle, AppResources.LocationServicesNotAvailableMessage, AppResources.OK);
                    return null;
                }

                return await loLocator.GetPositionAsync(TimeSpan.FromSeconds(20), null, false);
            }
            catch (Exception ex)
            {
                Device.BeginInvokeOnMainThread(() =>
                {
                    App.Current.MainPage.DisplayAlert(AppResources.GetCurrentLocationTitle, ex.Message, AppResources.OK);
                });
            }
            return null;
        }
```

**Comment by jamesmontemagno** [comment]
Use the https://github.com/jamesmontemagno/PermissionsPlugin to request it manually before checking those settings.

**Comment by TonyLugg** [comment]
I have this in MainActivity:

```
        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

This is exactly from your doc:  https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html

Is it not right?

**Comment by jamesmontemagno** [comment]
Actually try to get the permission:

```
try
            {
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
                if (status != PermissionStatus.Granted)
                {
                    if(await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                    {
                        await DisplayAlert("Need location", "Gunna need that location", "OK");
                    }

                    var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                    status = results[Permission.Location];
                }
}
```

**Comment by jamesmontemagno** [comment]
It is a catch 22... you can't get a list of providers until you get permission.

In version 5 this has more improvements to the API overall though.

**Comment by TonyLugg** [comment]
Is this just needed for Android?  iOS and UWP seem to prompt for permission without the manual permission code.  And in iOS the info.plist already has the rational text.

**Comment by TonyLugg** [comment]
Works for Android now!  Still have to test that it didn't break iOS or UWP :) but it is working for Android.  

Thanks!

**Comment by jamesmontemagno** [comment]
Should work fine on all platforms.

**Comment by TonyLugg** [comment]
Confirmed.  Working fine.  Your guidance is greatly appreciated.

**Comment by Wietse-0803** [comment]
Thanks for this discussion @TonyLugg and @jamesmontemagno. I was facing the same problem.
