### ISSUE TITLE
Going from wifi to mobile data forces restart of app.

### ISSUE THREAD

**Issue by Morten-Kortermann-IT** [jamesmontemagno/GeolocatorPlugin#198]
Not entirely sure the issue is with Geolocator. A number of our testers have reported that when our app is in the background and then leave an area with wifi connection to one where you only have mobile data, the app crashes and you have to restart it.

The problem seems to only occur when moving from a wifi connection to mobile data and only when actually physically moving location and so far it only seems to occur on Android devices. I've been unsuccesful in replecating the issue by simply turning off the wifi while sitting at my computer. This obviously means I've been unable to experience it whilst debugging. I suspect it is unhandled exception or maybe a missing permission.

**Comment by prashantvc** [comment]
That's rather strange! Is it possible to collect the crash log from you users and share it with us?
It will help us to troubleshoot the issue

**Comment by Morten-Kortermann-IT** [comment]
The issue seems to have gone away, at the very least I can no longer provoke the crash regardless of what I try.
