### ISSUE TITLE
Adding support for Fused Location Provider in 5.0

### ISSUE THREAD

**Issue by VictorK1902** [jamesmontemagno/GeolocatorPlugin#199]
Will Fused Locator be available in the next release, since I saw this? 
https://github.com/jamesmontemagno/GeolocatorPlugin/issues/149

I came across the following documentation while writing a foreground service to track GPS on Android:

https://developer.android.com/reference/android/location/package-summary.html

    This API is not the recommended method for accessing Android location.
    The Google Location Services API, part of Google Play services, is the preferred way to add location-awareness to your app. 
    It offers a simpler API, higher accuracy, low-power geofencing, and more. 
    If you are currently using the android.location API, you are strongly encouraged to switch to the Google Location Services API as soon as possible. 
    

Because of that, I ended up implementing [Google Play services location APIs](https://developer.android.com/training/location/index.html) instead.

**Comment by jamesmontemagno** [comment]
It is already available in the pre-release of 5.0
