### ISSUE TITLE
IsGeolocationAvailable hangs if no network connection available

### ISSUE THREAD

**Issue by kinex** [jamesmontemagno/GeolocatorPlugin#20]
## Bug

Version Number of Plugin: 3.0.4
Device Tested On: Surface Pro 4 (Windows 10.0.14393)
### Expected Behavior

No hang
### Actual Behavior

Hangs
### Steps to reproduce the Behavior
1. set Flight mode on (no network)
2. call IsGeolocationAvailable (first call works ok)
3. call IsGeolocationAvailable  again (second call never returns)

Possibly same issue with IsGeolocationEnabled

**Comment by lorant-csonka-planorama** [comment]
I am facing with the same issue.
@jamesmontemagno Why did you close it?
