### ISSUE TITLE
How to loosely couple plugin ?

### ISSUE THREAD

**Issue by leroygumede** [jamesmontemagno/GeolocatorPlugin#201]
Great plugin, after reading your blog (great one) I tried loosely coupling the plugin.
I realised that IGeolocator is the only interface I can find.

```
        static IGeolocator geolocation;
        public static IGeolocator Instance
        {
            get
            {
                return geolocation ?? (geolocation = CrossGeolocator.Current);
            }
            set
            {
                geolocation = value;
            }
        }
    }
```

I would like to access everything like Position, GeolocatorUtils, IsSupported etc which looks like they don't have interfaces. is there a way for me to implement them ?

[![enter image description here][2]][2]

 [2]: https://i.stack.imgur.com/QN646.png

**Comment by leroygumede** [comment]
The following is not working for me

```
        static CrossGeolocator crossGeolocation;

        public static CrossGeolocator Instance
        {
            get
            {
                return crossGeolocation ?? (crossGeolocation = CrossGeolocator.Current);
            }
            set
            {
                crossGeolocation = value;
            }

        }
```

**Comment by prashantvc** [comment]
> is there a way for me to implement them?

This is will be significant changes to the existing APIs. Could you elaborate on the changes that you're requesting?

> The following is not working for me

I need more information to help you with this. What platform platform Android, iOS, UWP? 
It will help if you could elaborate when you say **following is not working for me**

**Comment by jamesmontemagno** [comment]
There is no need for interfaces on those simple classes or Utils as they are supplementary and are just logic and don't touch platform specific APIs. 


Your code should be: `ICrossGeolocator ` not `CrossGeolocator `

**Comment by leroygumede** [comment]
@jamesmontemagno @prashantvc :) Thanks, I was trying to make the plugin unit testable. It was not a feature request , but more trying to understand how to loosely couple it.
