### ISSUE TITLE
Crash on simulator

### ISSUE THREAD

**Issue by fgiacomelli** [jamesmontemagno/GeolocatorPlugin#202]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 
Device Tested On: 
Simulator Tested On: Genymotion Galaxy S6 API 23
Version of VS: 2017 15.5.2
Version of Xamarin: 4.8.0.753
Versions of other things you are using:

### Steps to reproduce the Behavior
Execute an await CrossGeolocator.Current.GetPositionAsync(new TimeSpan(0, 0, 10)); function, an exception is thrown

### Expected Behavior
Return position

### Actual Behavior
01-09 12:22:07.802 E/mono    ( 1788): Unhandled Exception:
01-09 12:22:07.802 E/mono    ( 1788): System.Threading.Tasks.TaskCanceledException: A task was canceled.
01-09 12:22:07.802 E/mono    ( 1788):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00026] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-09 12:22:07.802 E/mono    ( 1788):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-09 12:22:07.802 E/mono    ( 1788):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-09 12:22:07.802 E/mono    ( 1788):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
01-09 12:22:07.802 E/mono    ( 1788):   at Plugin.Geolocator.GeolocatorImplementation+<GetPositionAsync>d__41.MoveNext () [0x004ac] in C:\projects\geolocatorplugin\src\Geolocator.Plugin.Android\GeolocatorImplementation.cs:232

**Comment by jamesmontemagno** [comment]
You need to go into the simulators settings and send the coordinates over to it for it to work.

**Comment by fgiacomelli** [comment]
Thank you for your reply, I see that following your suggestion it works :-)
