### ISSUE TITLE
Is there any way to check Location Service is on satellite mode?

### ISSUE THREAD

**Issue by paradisehuman** [jamesmontemagno/GeolocatorPlugin#203]
Hi. I want to know is there any way to do that with this plugin ?

**Comment by prashantvc** [comment]
Could you elaborate the question? What are you trying to do?

**Comment by paradisehuman** [comment]
@prashantvc CrossGeolocator.Current.IsGeolocationEnabled only checks GPS is enable or not.
It's not any difference whether is getting location from WiFi or GPS satellite.
I want to know is there any way to know is GPS satellite is checked or not .

**Comment by jamesmontemagno** [comment]
On Android you are able to restrict it to only use GPS or only use WiFi. There is no apis really to detect it on the other system.
