### ISSUE TITLE
asking for GPS calibration while running the sample app.

### ISSUE THREAD

**Issue by yongwang** [jamesmontemagno/GeolocatorPlugin#204]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On: iOS -- iPhone 6 and 6+
Simulator Tested On: iPhone 6 & 6+
Version of VS: 7.3.2
Version of Xamarin: 11.6.1.2 (
Versions of other things you are using:
Xamarin.Android
Version: 8.1.0.25 (Visual Studio Professional)
### Steps to reproduce the Behavior
Run the sample App that come with the repo
### Expected Behavior
show gps location
### Actual Behavior
show gps location. However, from time to time it pops up a GPS calibration screen ask me to calibrate (this does not happen on android. see screenshot below
### Screenshotst
![image](https://user-images.githubusercontent.com/1625619/34833474-65439bf8-f6e7-11e7-9ff1-4796b8db98c4.png)

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/GeolocatorPlugin/issues/189
