### ISSUE TITLE
iOS : does not return result, app hangs

### ISSUE THREAD

**Issue by phisakel** [jamesmontemagno/GeolocatorPlugin#205]
## Bug Information
Version Number of Plugin: 4.2
Device Tested On: ios 11.2
Simulator Tested On:  ios 11.2
Version of VS: VS for Mac latest

### Steps to reproduce the Behavior
 await locator.GetPositionAsync(TimeSpan.FromSeconds(5), null, false), TokenSource.Token); // never returns

You can test with the default sample for iOS.
I think it has to do with the plist privacy permissions.
Used a different plugin and it works with NSLocationWhenInUseUsageDescription

**Comment by brodymccroneV2** [comment]
Happening on Android too.

**Comment by jamesmontemagno** [comment]
Do you have a sample project?

**Comment by phisakel** [comment]
Yes I tried the  GeolocatorSample from this repository and it also hangs

**Comment by jamesmontemagno** [comment]
On a device or simulator?

On a simulator you may have to tell it what location to use.

**Comment by prashantvc** [comment]
I am not able to reproduce this on iPhone SE running iOS 11.2
@phisakel could you share more information about your set up?

**Comment by phisakel** [comment]
In the simulator and also on an iPhone 5s. I will attach a sample if you are not able to reproduce.

**Comment by jamesmontemagno** [comment]
On the simulator did you set a location so it knows to pull it back? Sometimes the simulator does not set it correctly on boot.

**Comment by FarReachMarco** [comment]
Same issue on android, downgraded the plugin to version 2.4.0.91020 and now it does not hang anymore

**Comment by phisakel** [comment]
Yes i am setting a custom location on the simulator. It worked before.

**Comment by luveti** [comment]
4.2.0 on iOS will hang for me if I choose "While Using the App" instead of "Always" when iOS prompts me for location access. @phisakel does it hang for you if you choose "Always"?

**Comment by jamesmontemagno** [comment]
Welcome to iOS 11. Only request the permissions that you need. 

See: https://github.com/jamesmontemagno/PermissionsPlugin/issues/75 as there is nothing I can do here.
