### ISSUE TITLE
IGeolocator's PositionChanged firing twice...

### ISSUE THREAD

**Issue by kollasnubben** [jamesmontemagno/GeolocatorPlugin#206]
## Bug Information

Description:
IGeolocator's PositionChanged is triggering twice when I send new coordinates via the emulator.

Version Number of Plugin: 4.20.
Device Tested On: Emulator (Android 7.0, API Level 24)
Simulator Tested On: Android Emulator (Visual Studio)
Version of VS: Microsoft Visual Studio Enterprise v15.5.3
Version of Xamarin: 4.8.0.757

Versions of other things you are using:
Xamarin Forms: 2.5.0.122203

### Steps to reproduce the Behavior
1) Create a Xamarin.Forms project
2) Configure the locator as such:

```
public static IGeolocator locator = CrossGeolocator.Current;

locator.DesiredAccuracy = 100;

if (!locator.IsListening)
await locator.StartListeningAsync(TimeSpan.FromMilliseconds(500), 1, true);


locator.PositionChanged += (sender, e) =>
{
// code

}
```

4) Open the emulator, put in coordinates and hit "Send" on the emulator.

### Expected Behavior
The locator.PositionChanged event should fire once.

### Actual Behavior
The locator.PositionChanged event is firing twice, executing all subsequent functions and API calls two times...

### Code snippet
`System.Diagnostics.Debug.WriteLine("Position has changed...");`

### Screenshots
![image](https://user-images.githubusercontent.com/35563525/35096665-f12e6b90-fc44-11e7-9429-a903d09fd4f3.png)

**Comment by ramiss** [comment]
I'm experiencing the exact same thing.  My workaround is to save the last position and only perform work if a parameter has changed.

**Comment by ramiss** [comment]
I think this is also related to the issue of the speed value showing 0 almost all of the time (randomly 1 in 100 times it'll display a speed).   I ended up writing my own speed calculation and with the PositionChanged firing twice (within about 50 ms of each other) I quickly realized that comparing the current to the last location shows as the same and thus the speed shows 0.   I wonder if this is happening internally as well?

**Comment by jamesmontemagno** [comment]
It is possible that the system sends you the same information multiple times. This is out of the libraries control.

**Comment by ramiss** [comment]
James,  thanks for the reply and the insight.  Perhaps then this is not a bug, but rather a feature request/suggestion to filter out all but 1 event within a minimum time range.  I'm going to work on my own solution and report back here. 

Thanks again for a great plugin!

**Comment by mrTR24** [comment]
Hi 
If you are calling StartListeningAsync(TimeSpan.FromMilliseconds(500), 1, true) in OnAppearing() on first install. 

OnAppearing() is  run twice.

First Time OnAppearing() is called is when permission pop out asking to grant permission
Second time OnAppearing() is called is when user grant permission 

Hence PositionChanged firing twice 

**Fix Just add this check**
var permissionLocation = await Plugin.Permissions.CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Location);
            if (permissionLocation == Plugin.Permissions.Abstractions.PermissionStatus.Granted)
            {
                StartListeningAsync(TimeSpan.FromMilliseconds(500), 1, true);
            }

Worked For Me  xD

**Comment by kollasnubben** [comment]
You're only getting one tick with that code?

**Comment by mrTR24** [comment]
yes

**Comment by chrisfoulds** [comment]
I can confirm I was only setting things up once but getting double fire.
Simply added this and it resolved it 👍 

` if(e.Position.Latitude==lastRecievedPosition.Latitude && e.Position.Longitude == lastRecievedPosition.Longitude && e.Position.Timestamp == lastRecievedPosition.Timestamp)
                {
                    // Reject it we got a double fire !!!
                    return;
                }`

**Comment by pcloof** [comment]
I have the same problem of the handler getting called twice for each location update, despite calling the StartListeningAsync only once (confirmed by debugging) and checking whether "CrossGeolocator.Current.IsListening" returns false before starting it.

I'm just saying that this is still the case even when checking properly. I guess I'll use the workaround of checking whether the timestamp is strictly larger than for the previous handler call.

**Comment by M-Yankov** [comment]
I'm experiencing the same issue, I see that the package is not recently updated.
But the reason for this is "passive" location provider:
![image](https://user-images.githubusercontent.com/10440078/113622916-46960700-9666-11eb-84ec-6dd53d659aa5.png)
 _I've debugged the values just after invoking `StartListeningAsync`_ and shows two listening providers  ⬆️ 

The code where this should be fixed is the `for` loop inside `StartListeningAsync`:
https://github.com/jamesmontemagno/GeolocatorPlugin/blob/8f5987a1d53f4169a5900dd0e33b0aab8ead773f/src/Geolocator.Plugin/Android/GeolocatorImplementation.android.cs#L332
_I didn't debug the code,_ but adding a check for ignored providers should fix this behavior.

I've implemented my own `ILocationListener` (`LocationListener`) class and set it up like:
```c#
var locationCriteria = new Criteria();

locationCriteria.Accuracy = Accuracy.Coarse;
locationCriteria.PowerRequirement = Power.Medium;

LocationManager gpsManager = Application.Context.GetSystemService(Context.LocationService) as LocationManager;
string provider = gpsManager.GetBestProvider(locationCriteria, true);

// provider = "gps"
gpsManager.RequestLocationUpdates(provider, 5000, 10, new LocationListener());
```

My `LocationListener.LocationChanged` was invoked only once!
