### ISSUE TITLE
Issue with Android power saving features

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#208]
Hi,

I'm using last plugin version and I'm facing lots of problem, gettings position updates, in Android 7+ when power saving features are enabled.

I mean that PositionChanged event not fire when power saving features are enabled and I have configured it to ask for position updates in background implementing an Android service.

Is possible to ask to user/system to be whitelisted or to ignore this setting for a specific app? Or there is any parameter in the plugin setting to solve this?

Thank you

**Comment by jamesmontemagno** [comment]
Check Android docs https://developer.android.com/about/versions/oreo/background-location-limits.html 


You are pretty no limited in this mode. Could be good to try the 5.0 beta which I plan on updating again this week that uses the Google play fused stuff, which may be better, but hard to say.

**Comment by sayed-seliman** [comment]
I already defined a foreground service but it also with it Location updates is not fired.
This is my foreground service

`var notification = new Notification.Builder(this)
                    .SetContentTitle("My app")
                    .SetContentText("text...")
                    .SetSmallIcon(Resource.Drawable.white_car)
                    .SetPriority(2)
                    .SetContentIntent(BuildIntentToShowMainActivity())
                    .SetOngoing(true)
                    .AddAction(BuildStopServiceAction())
                    .Build();

                StartForeground(Constants.SERVICE_RUNNING_NOTIFICATION_ID, notification);`

Do you think that using 5.0 beta can solve the problem? Do I have to change something in my code?

In the Android service I'm listening to location updates with this code:

`locator.StartListeningAsync(TimeSpan.FromMilliseconds(minTime), 0, false, new Plugin.Geolocator.Abstractions.ListenerSettings
                {
                    ActivityType = Plugin.Geolocator.Abstractions.ActivityType.Other,
                    AllowBackgroundUpdates = true,
                    DeferLocationUpdates = true,
                    DeferralDistanceMeters = 1,
                    DeferralTime = TimeSpan.FromSeconds(45),
                    ListenForSignificantChanges = false,
                    PauseLocationUpdatesAutomatically = false
                });`

Something wrong?

Thanks

**Comment by jamesmontemagno** [comment]
I don't even think the other version would help...
Via Docs:
If your app is running in the background, the location system service computes a new location for your app only a few times each hour. This is the case even when your app is requesting more frequent location updates.

It is the expected behavior.

**Comment by sayed-seliman** [comment]
The only way is to manually add the app to the saving power whitelist?
Do you know if is it possible to ask user with and Android dialog to add the app to the saving power whitelist?

Il giorno 24 Gen 2018, 20:56, alle ore 20:56, James Montemagno <notifications@github.com> ha scritto:

**Comment by jamesmontemagno** [comment]
Not positive, would have to look through docs.

**Comment by sayed-seliman** [comment]
Did you find anything about?
