### ISSUE TITLE
"Task was cancelled issue"

### ISSUE THREAD

**Issue by sktdeepak** [jamesmontemagno/GeolocatorPlugin#209]
Task was canceled issue when i doing very fast, i tried with sample application what you provided in thread #65. That also having same issue.
[]
![screenshot_20180201-183320](https://user-images.githubusercontent.com/14029491/35680329-0e016704-0780-11e8-8c21-c71dd12f292f.png)
(url)

**Comment by jamesmontemagno** [comment]
You have to send it from the emulator in the settings

**Comment by sktdeepak** [comment]
This is not emulator , it's mobile device

**Comment by jamesmontemagno** [comment]
Then you need to increase the timeout and make sure your GPS is on

**Comment by sktdeepak** [comment]
I am using physical device. but i am not getting this error all the time only first time.

From the app i am moving to settings page,within a second i am turned on GPS and going back to app using hardware back button. I placed code inside of onappering method ,once it reaches the page on that particular line ,suddenly it was thrown "Task was cancelled"

**Comment by sandeep1503** [comment]
I am also facing the same issue after immediate turn off gps and turn on gps then i am getting task failed
