### ISSUE TITLE
Target Framework Version Issue

### ISSUE THREAD

**Issue by Apidcloud** [jamesmontemagno/GeolocatorPlugin#21]
Good afternoon,

I have been using **Geolocator** plugin for a while now, but for some reason and without updating the package, it is now asking for a greater Android version (6.0), whereas my project has always been targeting 4.0.3. How can I lower its version?

Here's the error:
PathXYZ.csproj: Warning XA0105: The $(TargetFrameworkVersion) for Plugin.Geolocator.dll (v6.0) is greater than the $(TargetFrameworkVersion) for your project (v4.0.3). You need to increase the $(TargetFrameworkVersion) for your project. (XA0105) (ProjectXYZ)

Same thing happening with **DeviceMotion** and **Permissions** plugins. 

I don't have any Android 6.0 at my possession and need to test the app on real devices, so using an emulator is out of the question.

Sincerely,
Luís Fernandes

**Comment by jamesmontemagno** [comment]
You must Build & Target API 23, you can set your Minimum lower though, for instance:
![image](https://cloud.githubusercontent.com/assets/1676321/17489658/036609ee-5d54-11e6-9e97-636588053f12.png)


What version are you running of the plugin?

**Comment by Apidcloud** [comment]
Thanks for the reply,

I have the following versions:
CurrentActivity - 1.0.1
Permissions - 1.1.7
DeviceMotion - 1.0.3
GeoLocator - 3.0.4
Android.Support.v4 - 23.1.1.0

Where is that 'Compile using Android version' option located?
Those packages are used inside an Android Library Project. In Project Options > Build > General I only have Target framework set to 6.0 (was 4.0.3 before), as follows:
![image](https://cloud.githubusercontent.com/assets/3720818/17496294/80172fbc-5db4-11e6-852e-a12e475a3cb9.png)

As for the main android application, in Project Options > Build >General:
![image](https://cloud.githubusercontent.com/assets/3720818/17496278/70f013d2-5db4-11e6-9634-0aff78e42937.png)

And Project Options > Build > Android Application:
![image](https://cloud.githubusercontent.com/assets/3720818/17496266/65980d3c-5db4-11e6-8c37-19afcc7cef6a.png)

What can I do?

Thanks again!

**Comment by jamesmontemagno** [comment]
That all looks correct to me.

In VS it groups the 2 pages together for the app.

So the Android Class Library doesn't compile?

**Comment by Apidcloud** [comment]
Ah I see. The build output is the following: http://pastebin.com/gQUpZDFh

**Comment by Apidcloud** [comment]
Ok, I am not sure what fixed it, but after deleting the app and updating the android tools it's working again.

Thanks for your help! :)

**Comment by weitzhandler** [comment]
Same issue here.
I'm freaking out. I've spend several hours fiddling with it and the issue still persists.

```

> 2>  MyProject.Droid -> C:\Users\Shimmy\OneDrive\Documents\Visual Studio 2015\Projects\MyProject\MyProject\MyProject.Droid\bin\Debug\MyProject.Droid.dll
> 2>C:\Users\Shimmy\OneDrive\Documents\Visual Studio 2015\Projects\MyProject\MyProject\MyProject.Droid\MyProject.Droid.csproj : warning XA0105: The $(TargetFrameworkVersion) for FormsViewGroup.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
> 2>C:\Users\Shimmy\OneDrive\Documents\Visual Studio 2015\Projects\MyProject\MyProject\MyProject.Droid\MyProject.Droid.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.Android.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
> 2>C:\Users\Shimmy\OneDrive\Documents\Visual Studio 2015\Projects\MyProject\MyProject\MyProject.Droid\MyProject.Droid.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.dll (v7.0) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.
```

Here are the errors copied from the output tab.

**Comment by jamesmontemagno** [comment]
@weitzhandler what are you targeting.. also that doesn't have anything really to do with this project. They are warnings and you can probably ignore them.

**Comment by shyjumohan** [comment]
I had the similar issue resolved by following steps
1. Go to C:\Program Files (x86)\Android\android-sdk 
2. run SDK Manager.exe. 
3.  Click on Update the Packages. (It will download necessary updates)
4. Go to Application properties
5. Set the Target Android version (6 or 7 according to the error).

**Comment by Casasniper** [comment]
Hello , i gave the same issue , 
my SDKmanager.exe  is located on C:\Users\[user]\AppData\Local\Xamarin\MonoForAndroid\AndroidSDK\tools\lib
i tried to run it , but it fails 
![image](https://cloud.githubusercontent.com/assets/12403555/25026579/5d340a54-20a7-11e7-9219-f8fa21667dae.png)

**Comment by eaintphyo** [comment]
I also got that issue.
The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.dll (v7.1) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrameworkVersion) for your project.	HelloWorld.Android	D:\Xamarin Projects\HelloWorld\HelloWorld\HelloWorld.Android\HelloWorld.Android.csproj

**Comment by LanceJZ** [comment]
I also get "warning XA0105: The $(TargetFrameworkVersion) for Urho.dll (v7.1) is greater than the $(TargetFrameworkVersion) for your project (v6.0). You need to increase the $(TargetFrame"
I've tried everything above, but nothing works.
I only have version 6 SDK installed. I'm using Android Studio for the Android SDK, and it no longer has an SDK manager either. It is now in the Studio settings, and there is no target version.

**Comment by jamesmontemagno** [comment]
You need to target SDK 25+ read: https://blog.xamarin.com/mastering-android-support-libraries/ @LanceJZ

**Comment by TonyC5** [comment]
I experienced the 'warning XA0105' issue when building with Visual Studio on OSX (El Capitan) with Target Android 6.0 in my AndroidManifest.xml.  The solution for me was to change Project Options > Build > General > Target Framework from "Use latest installed platform (6.0)" to "Android 6.0 (Marshmallow)."  For me, the lesson learned is to set the Project's target framework to the specific target.  I won't be using the "Use latest..." option.
