### ISSUE TITLE
GetPositionAsync only returns a location if UIBackgroundModes Location is on

### ISSUE THREAD

**Issue by Morten-Kortermann-IT** [jamesmontemagno/GeolocatorPlugin#210]
When calling GetPositionAsync it never returns a position on iOS unless Location is added to Background Modes, even though the app is running in the foreground and the BackgroundModes should be irrelevant.

Version of plugin: 4.2.0
Device tested one: iPhone 6, iOS 11.2.5
Simulator: iPhone X 11.2
Version of VS: 15.5.4
Xamarin Forms: 2.5.0.121934

**Comment by jamesmontemagno** [comment]
What values are in your info.plist for permissions?

**Comment by Morten-Kortermann-IT** [comment]
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Insert reason</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Insert reason</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Insert reason</string>
	<key>NSCalendarsUsageDescription</key>
	<string>Insert reason</string>
	<key>NSCameraUsageDescription</key>
	<string>Insert reason</string>
	<key>NSContactsUsageDescription</key>
	<string>Insert reason</string>
	<key>NSSiriUsageDescription</key>
	<string>Insert reason</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Insert reason</string>
	<key>NSAppleMusicUsageDescription</key>
	<string>Insert reason</string>

**Comment by jamesmontemagno** [comment]
What does your code snippet look like where it is locking?

**Comment by Morten-Kortermann-IT** [comment]
`        public async Task<bool> PushLocation()
        {
            try
            {
                if (CrossGeolocator.Current.IsGeolocationEnabled && CrossGeolocator.Current.IsGeolocationAvailable)
                {
                    Plugin.Geolocator.Abstractions.Position pos = await CrossGeolocator.Current.GetPositionAsync();
                    CurrentPosition = pos;
                    CurrentPositionDateTime = DateTime.Now;

                    Services.LocationService l = new Services.LocationService();
                    l.PushLocation(pos.Latitude, pos.Longitude, pos.Accuracy);
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.ToString());
                return false;
            }
        }`

**Comment by Umar3x** [comment]
Hello,

Got a similar issue on iOS : 

```
   if (resultRouteInitPos)
                    {
                        pos = await CrossGeolocator.Current.GetPositionAsync(TimeSpan.FromSeconds(1000));
                        position = new Position(pos.Latitude, pos.Longitude);
                    }
```

```
	<key>NSLocationAlwaysUsageDescription</key>
	<string>AppName needs authorization</string>
	<key>NSLocationWhenInUseUsageDescription</key>
		<string>AppName needs authorization</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>AppName needs authorization</string>
```

DeadLock on CrossGeolocator.Current.GetPositionAsync(); 
This snippet is in an async command in a view model. 

Thanks.

**Comment by jamesmontemagno** [comment]
So... The question is... is your application getting updates in the background?

If not remove that from your info.plist and only put WhenInUse

If you have Always then you MUST include UIBackgroundModes

**Comment by jamesmontemagno** [comment]
I have updated: https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/docs/GettingStarted.md

Please read through

**Comment by jamesmontemagno** [comment]
@Umar3x did you have the information for UIBackgroundModes?

@Morten-Kortermann-IT What did you press on the pop up for the initial permissions?

What happened next? Did you get another prompt?

**Comment by Umar3x** [comment]
Wow, you are fast ! Thanks for updating the doc. You are right. If adding <key>NSLocationAlwaysUsageDescription</key> or <key>NSLocationAlwaysAndWhenInUseUsageDescription</key> while its not useful, it drives to a deadlock. For now I don't need background updates. 

Again thank you for the fast answer.

**Comment by Morten-Kortermann-IT** [comment]
I made the changes you suggested and only have WhenInUse in the info.plist.

I pressed allow for the initial permission for WhenInUse and do not get another prompt now but the issue still persists.

**Comment by Morten-Kortermann-IT** [comment]
Nope, physical device

**Comment by Umar3x** [comment]
@Morten-Kortermann-IT 

Perhaps you can try with everything ... I'm on an older version of the plugin. Would you like me to give a try with latest one ? 

I tried too with everything set in the info.plist, NSLocationAlwaysUsageDescription AND NSLocationAlwaysAndWhenInUseUsageDescription AND followed @jamesmontemagno updated doc with UIBackgroundModes, working well. 

My device is iphone 5S with iOS 11.2.5 
VS : 15.5.3
XF : 2.5.0.122203
Plugin version : 4.0.1

**Comment by jamesmontemagno** [comment]
I can't reproduce and have no issue here.

**Comment by gsalunkhe** [comment]
Hi 

Able to solve it, it will ask for permission for location while loading only. 

GOT ACTUAL CODE from https://stackoverflow.com/questions/41763540/crossgeolocators-getpositionasync-does-not-work

Putting the code as it is. Things to take care is 

1. calling the method in constructor.
2. have available lat long if exists.
3. VERY IMP have try catch, without try catch the application crashes. Not writing any thing in catch as don;t want to catch exception.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Foundation;
using UIKit;
using System.Threading.Tasks;
using Plugin.Geolocator.Abstractions;
using Plugin.Geolocator;
using System.Diagnostics;
using Xamarin.Forms;
using Community_Gateway_Mobile_App.iOS;

[assembly: Xamarin.Forms.Dependency(typeof(GPSLocation_iOS))]

namespace Community_Gateway_Mobile_App.iOS
{
    public class GPSLocation_iOS : IGPSLocation
    {
        public Position _position;

        public GPSLocation_iOS()
        {
            GetPosition();
        }

        public Dictionary<string, string> GetGPSLocation()
        {
            Dictionary<string, string> dictPosition = new Dictionary<string, string>();

            dictPosition.Add("latitude", _position.Latitude.ToString());
            dictPosition.Add("longitude", _position.Longitude.ToString());

            return dictPosition;
        }

        public async void GetPosition()
        {
            try
            {
                var locator = CrossGeolocator.Current;

                _position = await locator.GetLastKnownLocationAsync();

                if (_position == null)
                {
                    locator.DesiredAccuracy = 50;
                    var myPosition = await locator.GetPositionAsync();
                    _position = new Position(myPosition.Latitude, myPosition.Longitude);
                }
            }
            catch (Exception ex)
            {
                               
            }
        }
