### ISSUE TITLE
StartListeningAsync causing System.TypeLoadException in assembly Plugin.Geolocator.Abstractions.ListenerSettings

### ISSUE THREAD

**Issue by mtpagano** [jamesmontemagno/GeolocatorPlugin#211]
More of a question than a bug...

After updating the plugin from 3.0.4 to 4.0.2 I get a System.TypeLoadException error when calling StartListeningAsync from the application's onStart.

02-08 13:46:31.225 I/MonoDroid( 7795): System.TypeLoadException: Could not resolve type with token 01000081 (from typeref, class/assembly Plugin.Geolocator.Abstractions.ListenerSettings, Plugin.Geolocator.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

Version Number of Plugin: upgrading from plugin 3.0.4 to 4.0.2
Device Tested On: Nexus 4 Emulator and Samsung Galaxy Tab 7
Simulator Tested On:
Version of VS: 2015 (14.0.25431.01 Update 3)
Version of Xamarin: 4.8.0.760
Versions of other things you are using:
  Xamarin Android 8.1.013
  Xamarin Android SDK 8.1.5.0

### Steps to reproduce the Behavior
Changed the StartListeningAsync call from 

var locator = CrossGeolocator.Current;
await locator.StartListeningAsync(300000, 1);
locator.PositionChanged += (sender, e) => {
                    var position = e.Position;
                    Lat = Convert.ToDecimal(position.Latitude);
                    Long = Convert.ToDecimal(position.Longitude);
                    GPSDate = DateTime.Now;
                    Console.WriteLine("Lat:" + Lat.ToString() + "  Long:" + Long.ToString());

                    //Console.WriteLine("GPS: {0} : {1} x {2}", GPSDate.ToShortTimeString(), Lat, Long);
                };

To:

if (CrossGeolocator.Current.IsListening)
                return;

            await CrossGeolocator.Current.StartListeningAsync(TimeSpan.FromSeconds(5), 10, true, new Plugin.Geolocator.Abstractions.ListenerSettings
            {
                ActivityType = Plugin.Geolocator.Abstractions.ActivityType.AutomotiveNavigation,
                AllowBackgroundUpdates = true,
                DeferLocationUpdates = true,
                DeferralDistanceMeters = 1,
                DeferralTime = TimeSpan.FromSeconds(1),
                ListenForSignificantChanges = true,
                PauseLocationUpdatesAutomatically = false
            });

            CrossGeolocator.Current.PositionChanged += Current_PositionChanged;

I was able to use plugin version 4.0.2 in another application without the error.

**Comment by jamesmontemagno** [comment]
do a full clean/rebuild or simply remove and re-add all nugets. this is a nuget cache issue.

**Comment by mtpagano** [comment]
Thank you so much!  That worked!
