### ISSUE TITLE
GetAddressesForPositionAsync on iOS Null Reference

### ISSUE THREAD

**Issue by TonyLugg** [jamesmontemagno/GeolocatorPlugin#212]
## Bug Information

Version Number of Plugin:  4.2
Device Tested On:  
Simulator Tested On:  iPhone 7
Version of VS: 15.5.6
Version of Xamarin: 4.8.0.760  Xam iOS 8.1.5.0
Versions of other things you are using:

### Steps to reproduce the Behavior

GetAddressesForPositionAsync(position, null)

### Expected Behavior
Returns address

### Actual Behavior
Null Reference error (Object not set to an instance...)
** works in Android and UWP.

**Comment by jamesmontemagno** [comment]
most likely means the geocoder coulldn't get anything. 

The code is very simple: 
  if (position == null)
                throw new ArgumentNullException(nameof(position));

            using (var geocoder = new CLGeocoder())
            {
                var addressList = await geocoder.ReverseGeocodeLocationAsync(new CLLocation(position.Latitude, position.Longitude));
                return addressList.ToAddresses();
            }

**Comment by jamesmontemagno** [comment]
what is your stack trace so I can see more info.

**Comment by TonyLugg** [comment]
Position is valid.  Not null.  It used to work…

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner

**Comment by TonyLugg** [comment]
Going into meeting, will check in a bit.

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner

**Comment by TonyLugg** [comment]
The call stack doesn’t show me anything from inside your library.

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner

**Comment by TonyLugg** [comment]
Seems to work on a device, but not in a simulator

**Comment by TonyLugg** [comment]
Were you able to reproduce this in the simulator?

**Comment by jamesmontemagno** [comment]
Works great for me
![image](https://user-images.githubusercontent.com/1676321/36056528-f18e7d4c-0db9-11e8-803e-0373b3d477d9.png)

I will put some more null checking in here, but if it throws then it means it can't detect and it is totally possible on any platform.

**Comment by TonyLugg** [comment]
Don't throw null reference exception, just return null address collection.

On Feb 9, 2018 5:55 PM, James Montemagno <notifications@github.com> wrote:

Works great for me
[image]<https://user-images.githubusercontent.com/1676321/36056528-f18e7d4c-0db9-11e8-803e-0373b3d477d9.png>

I will put some more null checking in here, but if it throws then it means it can't detect and it is totally possible on any platform.

**Comment by jamesmontemagno** [comment]
That is what I am going to do however it is still possible that the underlying geocoder can throw, so you should still try/catch around it

**Comment by TonyLugg** [comment]
I do always 😉

On Feb 9, 2018 8:37 PM, James Montemagno <notifications@github.com> wrote:

That is what I am going to do however it is still possible that the underlying geocoder can throw, so you should still try/catch around it

**Comment by 8-Ball85** [comment]
Same problem here: CurrentPosition has
Latitude	47.83515875	double
Longitude 12.254026249999999	double
Adresses = Current	null	Plugin.Geolocator.Abstractions.Address

I got a valid brand-new Bing-Maps-Key ;-)
