### ISSUE TITLE
How do I add this NuGet package to a PCL shared-code Xamarin Forms project?

### ISSUE THREAD

**Issue by bitsol** [jamesmontemagno/GeolocatorPlugin#213]
The "Getting Started" document says to "Install into ALL of your projects, include client projects."

There's no proper VS project file for the shared-code project that works with the command (`dotnet add package Xam.Plugin.Geolocator`):
`error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.1.4/Microsoft/VisualStudio/v15.0/CodeSharing/Microsoft.CodeSharing.Common.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Unable to create dependency graph file for project '/Users/solomon/Documents/...'. Cannot add package reference.`

This command works on the platform-specific (Android and iOS) projects, however. How can I go about adding this?

I'm on macOS.

**Comment by jamesmontemagno** [comment]
What type of project are you trying to install it into? I just use nuget package manager in VS

**Comment by bitsol** [comment]
VS for Mac gives me no package manager for the shared code (PCL) Xamarin
project. The command line tool backs this up.

**Comment by bitsol** [comment]
I've tried every version, so I don't think it's a regular .NET issue (I know there have been some breaking changes). What missteps do you think I'm taking here?

Here's an image showing that there is no package manager for the shared code project:
![image](https://user-images.githubusercontent.com/9170316/36077041-7e7fb58e-0f1a-11e8-819c-ad4d7bbc43b2.png)

**Comment by bitsol** [comment]
I'm assuming I have to:
"Install into ALL of your projects, include client projects."

**Comment by jamesmontemagno** [comment]
If you are using shared projects then they don't have references or NuGet packages. They use their parent projects references/NuGet packages so you would only need to install them there.
