### ISSUE TITLE
Problem with new provider on iOS

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#214]
Hi,

i'm testing my app with the Geolocation plugin that works fine both on Android and iOS.
I started new test on an iOS device that has a new SIM with a different network provider and I started to get some problem.
I am not able to retrieve speed from the position it's always 0, excepets some rare cases.

If I open another app e.g.Maps while I'm using mine it's immediatly starts to work properly retrieving also the speed.

How this is possible? There is some option that I have to set in order to ask differently for position?

I'm asking for positiom in the AppDelegate with background options as described in the documentation.

Thanks

**Comment by prashantvc** [comment]
> How this is possible? There is some option that I have to set in order to ask differently for position?

This is rather strange! I was reading through the Apple documentations, there no mention of Sim card effecting the CoreLocation

Do you see same issue if you use your old simcard?

**Comment by sayed-seliman** [comment]
It's really strange I know, but the same app version with the same device works perfectly with the old simcard!

**Comment by jamesmontemagno** [comment]
These values come from the locator itself and of course the accuracy could be different from time to time.
