### ISSUE TITLE
Task timeout when GPS is disabled on Android

### ISSUE THREAD

**Issue by Bohrlotto** [jamesmontemagno/GeolocatorPlugin#216]
Hi,
I am trying to make the Geolocator example work, but if I manually turn on the GPS, everything goes ok.
If my gps is switched off, the application crashes because of a System.Threading.Tasks.TaskCanceledException

Version Number of Plugin: Permissions: 2.2.1 - Geolocator 4.2.0
Device Tested On: Samsung S7
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 4.8

What am I missing?

**Comment by jamesmontemagno** [comment]
Are you wrapping it in a Try/Catch?

**Comment by Bohrlotto** [comment]
yes. thanks. I can do that, but is this the best to check if gps is enabled?

**Comment by bentmar** [comment]
First have a look at the documentation
https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html
