### ISSUE TITLE
Can't compile project with Xam.Plugin.Geolocator

### ISSUE THREAD

**Issue by smhasan11** [jamesmontemagno/GeolocatorPlugin#221]
## Bug Information
Hi guys,
I'm trying to use Xam.Plugin.Geolocator to get user's current location.
I've installed following:
==> Xam.Plugin.Geolocator
==> Plugin.Permissions
==> Plugin.CurrentActivity

I've added following code snippet in **MainActivity.cs**

```
    public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
    {
        PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
    }
```
There is a **MainApplication.cs** class in Android project too.

I'm compiling against Android **API 26** (also tried with API 25)

![android_api_version](https://user-images.githubusercontent.com/13771705/36393243-a098bbb2-1563-11e8-82fe-283e899ced14.PNG)
![compile_version](https://user-images.githubusercontent.com/13771705/36393244-a0adf0ea-1563-11e8-91e3-882b7fb3f199.PNG)

But while building the entire project, I'm getting following errors:

> CS0115 'MainActivity.OnRequestPermissionsResult(int, string[], Permission[])': no suitable method found to override
> CS0104 'Permission' is an ambiguous reference between 'Plugin.Permissions.Abstractions.Permission' and 'Android.Content.PM.Permission'

 Interestingly, I was able to compile and run that sample project. But I can't make it work for my own project.

I must doing something wrong or missing something... What am I missing?

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
follow your github readme.txt
### Expected Behavior
Able to compile my project
### Actual Behavior
> CS0115 'MainActivity.OnRequestPermissionsResult(int, string[], Permission[])': no suitable method found to override
> CS0104 'Permission' is an ambiguous reference between 'Plugin.Permissions.Abstractions.Permission' and 'Android.Content.PM.Permission'

**Comment by Vladis466** [comment]
I suggest posting on the https://forums.xamarin.com/ as this seems more to be a configuration issue than a bug :)
At first glance I would guess you have an issue with your implementation of the permissions plugin where you are not handling the fact that a permission doesn't exist on the version of android you are running

**Comment by jamesmontemagno** [comment]
Remove:
using Plugin.Permissions.Abstractions;

from main activity.

**Comment by jamesmontemagno** [comment]
or change to this:

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
{
    Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```

I have updated my docs/readme.txt

**Comment by juanagu** [comment]
The problem is the version of Plugin.Permissions, only works with 2.2.1.  It doesn't work with version > 2.2.1
