### ISSUE TITLE
Location Updates on iOS works only with "Always" setting

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#224]
Hi,

I'm getting a problem with the geolocation plugin as my app is able on iOS to get location update only if user select the "Always location updates", if he select "Just when the app is in use" option I never get location update?

Can you please help me solving this problem?

Regards

**Comment by kingnguyen1993** [comment]
Get the same issue.

**Comment by jamesmontemagno** [comment]
Read through https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html and make sure you have it setup correct.

Works for me
