### ISSUE TITLE
StartListeningAsync Method ignoring deferral properties

### ISSUE THREAD

**Issue by ryandenkaat** [jamesmontemagno/GeolocatorPlugin#225]
Version Number of Plugin: 4.2.0
Device Tested On: iPhone X
Simulator Tested On: iPhone X, 8, 7
Version of VS: VS 2017 for Mac
Version of Xamarin: 2.4.0.91020

### Steps to reproduce the Behavior

Implemented example code for StartListeningAsync method and added deferral details. Then ran on device and it works yet appears to ignore the deferral details as it hit my "PositionChanged" method about 500 times in 10 seconds

### Expected Behavior

The deferral would occur to details provided. I don't care about the location change I just want it to get the location every 5-10 seconds and hit my "PositionChanged" method. I have also tried with the exact deferral details in the sample and it still appears to behave the same.

### Actual Behavior

Hits "PositionChanged" method way more frequently than it should if deferral worked.

### Code snippet
```
protected async Task StartListening() 
        {
            if (CrossGeolocator.Current.IsListening)
                return;

            await CrossGeolocator.Current.StartListeningAsync(TimeSpan.FromSeconds(5), 10, true, new Plugin.Geolocator.Abstractions.ListenerSettings
            {
                ActivityType = ActivityType.AutomotiveNavigation,
                AllowBackgroundUpdates = true,
                PauseLocationUpdatesAutomatically = false,
                DeferLocationUpdates = true,
                DeferralDistanceMeters = 1,
                DeferralTime = TimeSpan.FromSeconds(10),
            });

            CrossGeolocator.Current.PositionChanged += Current_PositionChanged;
        }
```

**Comment by paradisehuman** [comment]
I have same problem, please fix this.

**Comment by jethomas84** [comment]
Also having this problem. Without paying attention to minTime and minDistance in the declaration, iOS should use DeferLocationUpdates, which it ignores. This results in the PositionChanged event to fire almost constantly even with the most minor nudge of the phone. This is bogging down the thread and causing the app to eventually crash. This is a major bug that I'm hoping can be addressed soon. Thanks.

**Comment by marcuskammerlander** [comment]
i have the same issue after investigating i found out that it can be a bug on apple (http://www.openradar.me/34994712). I set this manually to true, only the minDistance working. minTime has no effect.

**Comment by paradisehuman** [comment]
Is there any news for fixing this bug ?

**Comment by jamesmontemagno** [comment]
Looks like i do set it here:

  manager.AllowDeferredLocationUpdatesUntil(listenerSettings.DeferralDistanceMeters == null ? CLLocationDistance.MaxDistance : listenerSettings.DeferralDistanceMeters.GetValueOrDefault(),
                    listenerSettings.DeferralTime == null ? CLLocationManager.MaxTimeInterval : listenerSettings.DeferralTime.GetValueOrDefault().TotalSeconds);
#endif

**Comment by RichPesci** [comment]
Unfortunately still happening, is there a work around? As of right now i just created a variable LastGpsPollTime and evaluate if 40 seconds has passed from that time, if it hasn't, return, if it has just set LastGpsPollTime to DateTime.Now and execute code.
