### ISSUE TITLE
Speed is showing 0 - could be due to position change firing twice

### ISSUE THREAD

**Issue by ramiss** [jamesmontemagno/GeolocatorPlugin#226]
I'm on the latest plugin (as of 3/9/2018) - testing with Android (Samsung Note 5) - and I have been having issues with speed showing 0 (other than a few random times).   I think it is related to the "firing twice" issue (link below).  It would certainly make sense that the speed function calculates 0 if the update fires twice for every change in location (comparing two identical locations give 0 speed).

[https://github.com/jamesmontemagno/GeolocatorPlugin/issues/206](https://github.com/jamesmontemagno/GeolocatorPlugin/issues/206)

**Comment by jamesmontemagno** [comment]
Could be completely possible for it to return 0.
