### ISSUE TITLE
Pre-release installation 

### ISSUE THREAD

**Issue by baneageorge** [jamesmontemagno/GeolocatorPlugin#229]
For common questions and issues see the [FAQ](https://jamesmontemagno.github.io/GeolocatorPlugin/FAQ.html)

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.0.0.187-beta
Device Tested On: Android 7.1 (25)
Simulator Tested On: -
Version of VS: Professional 15.5.2
Version of Xamarin: 4.8.0.753
Versions of other things you are using: Windows 7 x64

### Steps to reproduce the Behavior
Trying to install the pre-release but on Android, it fails

### Expected Behavior
To install on Android

### Actual Behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'Project.Android'.			0	

### Code snippet
I set the compile with Android 7.1 
and
`<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" />`
### Screenshots

I managed to make it work with the release version but the altitude and speed are not accurate at all. Is this a known bug? Is this pre-release supposed to fix it?

Thanks in advance for any help

**Comment by jamesmontemagno** [comment]
I am no longer supporting 5.0 at this time.
