### ISSUE TITLE
IsGeolocationEnabled return allways true

### ISSUE THREAD

**Issue by proxymus89** [jamesmontemagno/GeolocatorPlugin#23]
Version Number of Plugin: 3.0.4
Device Tested On: Lumia 950 XL (UWP project)

IsGeolocationEnabled and IsGeolocationAvailable return allways True also if GPS is turned off, so i can't check if GPS is enabled or not

Please solve, thanks.

**Comment by groege** [comment]
Same here (Lumia 640xl - UWP)

**Comment by ZeAleks** [comment]
In my case, it always return true but I found a situation where it return false while it should return true :)
I implemented the RequestPermission process :

`if (ContextCompat.CheckSelfPermission(ActivityBase.CurrentContext, PERMISSION) == (int)Permission.Granted)
{
    await base.InitializeAndStart();
    return;
}

ActivityCompat.RequestPermissions(ActivityBase.CurrentActivity, PermissionsLocation, PERMISSION_REQUEST_LOCATION_ID);
`
If the location is not allowed and that the user allow it through the Android dialog message, IsGeolocationEnabled return false ...

**Comment by maartenvandillen** [comment]
same here, IsGeolocationEnabled and IsGeolocationAvailable both stay false after granting permissions until app restarts.
