### ISSUE TITLE
Fetch only GPS

### ISSUE THREAD

**Issue by ThiagoAguirre** [jamesmontemagno/GeolocatorPlugin#230]
There's a way to fetch only GPS data? The foo.isAvailable should return false if GPS isn't acquired.
Thank you!

**Comment by jamesmontemagno** [comment]
On android yes you can by setting:

		/// <summary>
		/// Gets or sets the location manager providers to use when getting postition
		/// </summary>
		public static string[] ProvidersToUse { get; set; } = new string[] { };

		/// <summary>
		/// Gets or sets the location manager providers to use when doing
		/// continuous listening
		/// </summary>
		public static string[] ProvidersToUseWhileListening { get; set; } = new string[] { };

**Comment by ThiagoAguirre** [comment]
Thanks! And for iOS? If it isn't possible to restrict to GPS data only, there's a way to check if the data is fetched from GPS or not?
Sheers!

**Comment by jamesmontemagno** [comment]
Not possible on other platforms
