### ISSUE TITLE
GPS tracking (inaccurate measurements)

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/GeolocatorPlugin#237]
Hi,

I installed the latest version of the plugin and trying to using it for detecting position of a person while walking/running, plotting the position on a map (with an image)
It works great but some times a get a "wrong position" that moves the image in a completely different location, and after some second it return to the correct one.

How can I avoid this kind of errors?

This is my configuration

`locators.StartListeningAsync(TimeSpan.FromMilliseconds(4000), 0, false, new Plugin.Geolocator.Abstractions.ListenerSettings
                            {
                                ActivityType = Plugin.Geolocator.Abstractions.ActivityType.Fitness,
                                AllowBackgroundUpdates = true,
                                DeferLocationUpdates = true,
                                DeferralDistanceMeters = 1,
                                DeferralTime = TimeSpan.FromMilliseconds(4000),
                                ListenForSignificantChanges = false,
                                PauseLocationUpdatesAutomatically = false
                            });`

There is something wrong that causes this strange behaviour?

Thanks!

**Comment by jamesmontemagno** [comment]
You need to filter:
See:
https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving.Utils/Helpers/DistanceUtils.cs (this is included in the library)
and
https://github.com/Azure-Samples/MyDriving/blob/da6c978c46af662672133c10b6240e9c47258f89/src/MobileApps/MyDriving/MyDriving/ViewModel/CurrentTripViewModel.cs#L492
