### ISSUE TITLE
GPS locations sometimes are wrongs.

### ISSUE THREAD

**Issue by kikutano** [jamesmontemagno/GeolocatorPlugin#238]
## Bug Information

Version Number of Plugin: 4.2.0
Device Tested On: Android
Version of Xamarin: 7.3.3
Versions of other things you are using:

### Steps to reproduce the Behavior
The problem appears when I try to get the position changed from the Plugin `CrossGeolocator.Current.PositionChanged += OnPositionChanged`

### Expected Behavior

Correct GPS position

### Actual Behavior

Sometime GPS position is far away 2/3 Km from my current position.

### Code snippet
`CrossGeolocator.Current.DesiredAccuracy = 1.0f`
`CrossGeolocator.Current.PositionChanged += OnPositionChanged`

### Description

Hi, I'm using your plugin on Android without problem, but for some reason, sometime the GPS position is displaced by 2/3 Km from my position. I'm getting the GPS position every time PositionChanged is fired and I'm saving it on an Array:

[510] => Array
        (
            [**timestamp] => 2018-05-06T12:38:46.783794+02:00**
            [current_km_gyroscope] => 0.9247592111759
            [current_kmh_gyroscope] => 0
            [current_kmh_avg_gyroscope] => 1.6513557342427
            **[current_km_gps] => 43.315898645655**
            [current_kmh_gps] => 0
            **[latitude] => 41.1503157
            [longitude] => 16.4021259**
            [altitude] => 0
            [ble_disconnected] => 
        )

    [511] => Array
        (
            **[timestamp] => 2018-05-06T12:38:51.530281+02:00**
            [current_km_gyroscope] => 0.9247592111759
            [current_kmh_gyroscope] => 0
            [current_kmh_avg_gyroscope] => 1.6464555688592
            **[current_km_gps] => 45.155270289361**
            [current_kmh_gps] => 0
            **[latitude] => 41.137394607929
            [longitude] => 16.388408780172**
            [altitude] => 299.00817618053
            [ble_disconnected] => 
        )

As you can see from [510] to [511] few seconds are passed, but the distance is near to 2 Km. In [511] the latitude and longitude value is composed by 14 numbers, in [510] is composed by 9. It seems is an approximation or something like that. I really can't understand why. The altitude is 0 when an approximation occur. Could you please tell me what's that mean? It's an approximation caused by the lost of GPS signal or something else? Thanks!

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/GeolocatorPlugin/issues/237

You should filter if possible.
