### ISSUE TITLE
Version 4.5.0.1 issues with Android

### ISSUE THREAD

**Issue by faceoffers28** [jamesmontemagno/GeolocatorPlugin#239]
For common questions and issues see the [FAQ](https://jamesmontemagno.github.io/GeolocatorPlugin/FAQ.html)

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.5.0.1
Device Tested On: Alcatel One Touch running version 22
Simulator Tested On: NA
Version of VS: 2017
Version of Xamarin: Xamarin 4.9.0.753 and Xamarin.Android SDK 8.2.0.16
Versions of other things you are using: Minimum is 21, Target is 25, Compile is Android 8.1

### Steps to reproduce the Behavior

Install version 4.5.0.1 of the plugin with version 3.0.0.8 of Plugin.Permissions and Xam.Plugin.Media version 3.0.1

### Expected Behavior

The GeoLocator should return addresses. CrossMedia.Current.TakePhotoAsync and CrossMedia.Current.PickPhotoAsync should work as expected.

### Actual Behavior

The GeoLocator plugin returns the following error in a Try Catch when executing GetAddressesForPositionAsync.

ex = {Java.IO.IOException: Service not Available
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <fcbf47a04b2e4d90beafbae627e1fca4>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectRefe...	

Xam.Plugin.Media (3.0.1) returns the following error in a Try Catch when executing CrossMedia.Current.TakePhotoAsync and CrossMedia.Current.PickPhotoAsync.

Plugin.Permissions.CrossPermissions.get_Current' not found

### Code snippet

```
if (current == PermissionStatus.Granted)
                    {
                        var locator = CrossGeolocator.Current;
                        var position = await locator.GetPositionAsync(TimeSpan.FromSeconds(10));
                        var addresses = await locator.GetAddressesForPositionAsync(position);

                        if (addresses.Any())
                        {
                            var address = addresses.FirstOrDefault();
                            var test = address;
                        }
                    }
```

```
 var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
                    {
                        //PhotoSize = PhotoSize.Small,
                    });
```

### Resolution

Installing version 4.2.0 of GeoLocator allows me to run version 2.2.1 of Plugin.Permissions. This fixes the Xam.Plugin.Media issue. The Xam.Plugin.Media issues seems to be an issue with permissions, but it is causing an issue with taking and picking photos.

I'm still getting the GeoLocator error when executing GetAddressesForPositionAsync.

Hope this helps!

**Comment by jamesmontemagno** [comment]
I have rolled back this updated for now.

**Comment by faceoffers28** [comment]
@jamesmontemagno Should I try to upgrade the Xam.Media.Plugin to overcome the permissions issue or do you think it exists with the 3.1.3 version as well? Thanks!
