### ISSUE TITLE
.net standard 2.0 Plugin fails with "Unauthorized" error.

### ISSUE THREAD

**Issue by HUBBER12** [jamesmontemagno/GeolocatorPlugin#242]
## Bug Information
Getting Unauthorized Error in .NET Standard Android version of Xamarin.

Version Number of Plugin: 4.5.0.1
Device Tested On: Samsung Galaxy S8 
Simulator Tested On: No simulator
Version of VS: 15.7.1
Version of Xamarin: (not sure - just latest on VS 15.7.1
Versions of other things you are using:  Xamarin.Forms project ( .NET Standard 2.0)

### Steps to reproduce the Behavior
This use to work
 var position = await locator.GetPositionAsync(new TimeSpan(0, 0, timeoutSeconds));
and then all of a sudden after upgrading to Visual Studio / 15.7.1, and after Android/ 8.1 i'm now noticing i get an error stating "Unauthorized" when trying to get the GPS position.

### Expected Behavior
GPS position should return

### Actual Behavior
Getting Exception that has an error description of "Unauthorized"

### Code snippet
none

### Screenshotst
none

**Comment by HUBBER12** [comment]
It looks like Plugin.CurrentActivity package cannot install because it's not compatable with netstandard 2.0.. instead it needs MonoAndroid.Version-v4.4      

I'm wondering how it was working before because i had not installed the Plugin.CurrentActivity, and i was using it on .NetStandard… just not sure why it changed.. i'm thinking i thas to do with Android 8.1 target , but I've been playing with that and it does not seem to work either.

**Comment by jamesmontemagno** [comment]
I removed this version and have a beta.

This most likely means you didn't setup the current activity stuff in your main activity.

**Comment by HUBBER12** [comment]
Aha.... i got it to work :).Two thoughts in case it helps others...

1) I was trying to ad the Plugin.CurrentActivity package to all projects, when only Android needed it. I was getting some errors in trying to install it to all projects.   (Do we need it for IOS as well?)

2) the Current Activity line in documentation is slightly off... maybe due to latest version changes... but for me the line

CrossCurrentActivity.Current.Activity.Init(this, bundle);
needed to be
CrossCurrentActivity.Current.Init(this, bundle);

after making the line code change and installing CrossCurrentActivity to Android project, it works again.

thanks !!
