### ISSUE TITLE
[iOS] IsGeolocationEnabled return true with authorisation to Never

### ISSUE THREAD

**Issue by quentinR0bert** [jamesmontemagno/GeolocatorPlugin#244]
## Bug Information

Version Number of Plugin: 4.1.3
Device Tested On: Iphone 6 plus
Version of VS: VS for mac 7.5
Version of Xamarin: 11.9.1.24

### Steps to reproduce the Behavior
First accept the Geolocation in your application.
Second go into the privacy settings ans set the Geolocation for the app at Never
Test if the Geolocation is okay with IsGeolocationEnabled

### Expected Behavior
IsGeolocationEnabled return False

### Actual Behavior
IsGeolocationEnabled return true

### Use Case
In need to know if the user is still okay without asking for the position (RGPD legislation)

### Analyse
For what i've seen, in your GeolocatorImplementation.apple.cs, in the IsGeolocationEnabled (line 141) you test if the geolocator service is enabled, and apparently your started to test the Status of the CLLocationManager but not finish it ^^.

We will need to test if the service is Enabled and if the user is still okay with this (!=Denied), no ?

**Comment by jamesmontemagno** [comment]
Because it is enabled on the device.
