### ISSUE TITLE
IsGeolocationEnabled always returning true / Provider GPS Is On

### ISSUE THREAD

**Issue by leroygumede** [jamesmontemagno/GeolocatorPlugin#245]
## Bug Information

Version Number of Plugin:
Device Tested On: Huawei P8 light  
Simulator Tested On: 2
Version of VS: 
Version of Xamarin: Xamarin Forms 

Versions of other things you are using:
Plugin.Permissions = 2.2.1
Xam.Plugin.Geolocator = 4.2.0

### Steps to reproduce the Behavior

1.  Turn on GPS 
2. Run App
3. Call CrossGeolocator.Current.IsGeolocationEnabled
4. .IsGeolocationEnabled comes back as true :) ....
5. Turn off GPS 
6. Call CrossGeolocator.Current.IsGeolocationEnabled again
7. .IsGeolocationEnabled comes back as true :( ....
### Expected Behavior
IsGeolocationEnabled should switch status .
or How can I check provider GPS is on
### Actual Behavior
Current.IsGeolocationEnabled is always true.

I also need to get the use new  current location every time (I need to check if gps is on every time)
### Code snippet

```
var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = desiredAccuracy;

if (!locator.IsGeolocationAvailable || !locator.IsGeolocationEnabled)
{
	throw new Exception("Your GPS Service seems to be turned off");
} 
```

**Comment by alanspires** [comment]
This happens on UWP as well.

**Comment by leroygumede** [comment]
@alanspires After going through the code, I realised IsGeolocationEnabled is based on if any of the providers are enabled :
`LocationManager.PassiveProvider, "local_database"`

I had to write a custom renderer to explicitly check if gps is enabled
