### ISSUE TITLE
NetStandard support

### ISSUE THREAD

**Issue by raV720** [jamesmontemagno/GeolocatorPlugin#248]
Does this plugin support NetStandard? The nuget packages contains builds for netstandard but this dlls does not contain actual implementation (am I missing something?)
I have installed 4.5.0.6 version of plugin on Android project targeting Android 7.0. The actual library used by project is from NetStandard version, because plugin targets MonoAndroid 7.1. After running application the Plugin.Geolocator.CrossGeolocator.IsSupported is FALSE. The previous version 4.2.0 works as expected.

**Comment by jamesmontemagno** [comment]
You must compile against 7.1 you can keep the target the same. Else you won't be getting the correct version.

**Comment by raV720** [comment]
Yes, I know about it, but it does not answer my question. I am wondering about net standard implementation. Does this implementation exist or not?
