### ISSUE TITLE
Different Position.Timestamp between Android and iOS

### ISSUE THREAD

**Issue by iw1qlh** [jamesmontemagno/GeolocatorPlugin#25]
![img_1140](https://cloud.githubusercontent.com/assets/12544578/17831834/68d330a0-66f4-11e6-8413-d9b7d0b82d99.JPG)
## Bug 
Different Timestamp is returned by Android devices and iOS devices.

I wrote a simple program that displays Latitude, Longitude, Altitude, Timestamp, Timestamp.LocalDateTime, Accuracy, Heading.

Like you can see in the attachment (taked at 16:20 local, 14:20 UTC time) the Android phone (Galaxy A3) shows the correct timestamp, instead on the iOS devices (iPhone 4 / iPhone 5c) a wrong timestamp is displayed (an hour back).

```
                LabelTime.Text = pos.Timestamp.ToString("HH:mm:ss z");
                LabelTimeLocal.Text = pos.Timestamp.LocalDateTime.ToString("HH:mm:ss z");
```

Version Number of Plugin: 3.0.4 (last stable)
Device Tested On: Samsung Galaxy A3 (Android 5.0.2) / iPhone 4 (iOS 9.2.1) / iPhone 5c (iOS 9.3.4)
Simulator Tested On:

**Comment by jamesmontemagno** [comment]
I think we fixed this in the beta....

Due to convergence with how I moved the repos it is hard for me to go back and fix this as a hotfix :(
