### ISSUE TITLE
System.NotImplementedException - This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by pauldiston** [jamesmontemagno/GeolocatorPlugin#250]
## Bug Information

Version Number of Plugin: 4.5.0.6
Device Tested On: Samsung A5
Simulator Tested On: N/A
Version of VS: 2017
Version of Xamarin: 4.10.0.448
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Upgrade from 4.2.0 to 4.5.0.6
2. Run the same code unchanged
3. Exception raised regarding "This functionality is not implemented in the portable version of this assembly"

### Expected Behavior
1. Should not raise exception

### Actual Behavior
1. Exception raised

**Comment by jamesmontemagno** [comment]
You are probably referencing the netstandard version. You must set your compile version to 7.1 or higher and then install the NuGet.
