### ISSUE TITLE
Is 5.x version still under active development?

### ISSUE THREAD

**Issue by nicolas-garcia** [jamesmontemagno/GeolocatorPlugin#251]
Hi!

I was wondering if the android-fused version (5.x) of the plugin was still under active development. Looks like the master keeps receiving updates but no more this branch.
As an user of the plugin 5.0.0.187-beta, I wonder if I should go back using the stable release 4.x.

Any news on the subject?

**Comment by jamesmontemagno** [comment]
Yes, I have to re-do it completely as I have tons of changes :) Hopefully in the next 2 weeks. You can also try Xamarin.Essentials for simple updates to just getting the location.

**Comment by nicolas-garcia** [comment]
Thank you for the heads up!
I already gave a look at Xamarin.Essentials, but I haven't tried it yet.
Anyway, thank you for your time :)
