### ISSUE TITLE
Pixel 2 XL Android 8.1.0 not returning location at all

### ISSUE THREAD

**Issue by tkieronski** [jamesmontemagno/GeolocatorPlugin#253]
Version Number of Plugin: 4.2.0 & 4.5.0.6
Device Tested On: Pixel XL2 Android 8.1.0
Simulator Tested On: no
Version of VS: 2017 15.7.2
Version of Xamarin: 4.10.0.448
Versions of other things you are using:

### Steps to reproduce the Behavior
Loading Geolocator sample produces no results for any calls and times - out on Get current location, Get Last Known Location always returns NULL

Google maps on the device work fine in detecting location so I don't think this is a hardware issue.

### Expected Behavior
Lat/Long of the location

### Actual Behavior
Timeout message on get current location, last know location is always NULL, tracking produces no error or results

I tested on other devices and it always worked fine. Tested on Nexus 6p Android 8.1.0 that works fine.

**Comment by alapointe42** [comment]
Same here, CrossGeolocator.Current.IsGeolocationAvailable always return false on Pixel 2, it's working on a Samsung and on a Nexus 6p.

**Comment by jamesmontemagno** [comment]
I have updated the sample nugets to test it out, but works perfect on my device. Would need a sample repro project.
