### ISSUE TITLE
Error iOS: Attempting to JIT compile method '<GetLocation>d__45:MoveNext ()' while running in aot-only mode.

### ISSUE THREAD

**Issue by juanagu** [jamesmontemagno/GeolocatorPlugin#254]
## Bug Information

Version Number of Plugin: 4.5.0.6
Device Tested On: iPhone 6s
Version of VS: VS for Mac community 7.5.1
Version of Xamarin: 3.0.0.48

### Steps to reproduce the Behavior
When Call: await GetLocation() :
### Expected Behavior
return Location or null
### Actual Behavior

> {System.ExecutionEngineException: Attempting to JIT compile method 'Garzon.Forms.UI.ViewModels.GarzonBaseViewModel/<GetLocation>d__45:MoveNext ()' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.
> 
>   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <8a48725212864358a4554e3196f5ca74>:0 
>   at Garzon.Forms.UI.ViewModels.GarzonBaseViewModel.GetLocation () [0x00013] in <eb12914b10884b23825e9cb80962ddb2>:0 
>   at Garzon.Forms.UI.ViewModels.PlaceListViewModel+<Load>d__32.MoveNext () [0x00089] in /Users/jagu/Projects/Garzon/garzon-app/Garzon.Forms.UI/ViewModels/Place/PlaceListViewModel.cs:153 }

### Code snippet
```
protected async Task<bool> IsLocationAvailable()
        {
            if (!CrossGeolocator.IsSupported)
                return false;

            if (!await PermissionsUtils.CheckPermissions(Permission.Location))
            {
                return false;
            }
            return await CrossGeolocator.Current.GetIsGeolocationAvailableAsync();
        }

        protected async Task<Position> GetLocation()
        {
            try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;

                var available = await IsLocationAvailable();
                var enabled = await locator.GetIsGeolocationEnabledAsync();
                if (!available || !enabled)
                {
                    //not available or enabled
                    return null;
                }

                return await locator.GetPositionAsync(TimeSpan.FromSeconds(10), null, true);
            }
            catch (Exception ex)
            {
                return null;
            }
        }
```

**Comment by jamesmontemagno** [comment]
I would report this to the Xamarin.iOS repo as I do not have this issue and can not reproduce it at all.
