### ISSUE TITLE
Current location unavailable when only LocationWhenInUse is set

### ISSUE THREAD

**Issue by karch4162** [jamesmontemagno/GeolocatorPlugin#255]
## Bug Information

Version Number of Plugin: 4.2.0
Device Tested On: IphoneX, Iphone 7, Iphone 6s
Simulator Tested On: IphoneX
Version of VS: 2017
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
What is happening is that when only LocationWhenInUse is enabled the plugin won't return a current location.  If I simply change to LocationAlways current location returns perfectly fine.  I think I have followed the getting started guide fairly closely.  I have all of the permissions added to the info.plist.  Am I just doing something wrong here?

I have linked a gist with a debug code snippet I am using and console output.

### Expected Behavior
Current location should return when LocationWhenInUse is enabled
### Actual Behavior
Unable to get the current location
### Code snippet
https://gist.github.com/karch4162/3b3af3884485742245155c6dbfe4a716

**Comment by lukejaylarsen** [comment]
Same here. Last version that worked for me is v4.0.1

**Comment by aparkerw** [comment]
I would like to bump this issue as well.  Some guidance or a timeline at addressing this would help my team leverage this plugin.

**Comment by jamesmontemagno** [comment]
it will depend on what you will be using in your info.plist. Only specify the one that you want to use: https://jamesmontemagno.github.io/GeolocatorPlugin/GettingStarted.html has guidance here.

**Comment by jamesmontemagno** [comment]
I'll take another look this week though.

**Comment by jamesmontemagno** [comment]
[App11.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/2139061/App11.zip)
Works just fine here.

**Comment by karch4162** [comment]
That is good, I appreciate you looking, but the example I gave wasn't using Xamarin forms.  Could that be the issue?

**Comment by jamesmontemagno** [comment]
Doesn't matter, it is all the same. You should just compare/contrast the info.plist and yours or any entitlements.

**Comment by karch4162** [comment]
Ok will take a look.  Thanks for taking the time to take a look.  Much appreciated.

**Comment by karch4162** [comment]
Just a follow up here.  My info.plist is listening for background location updates so I have the below keys added there.
NSLocationWhenInUseUsageDescription
NSLocationAlwaysUsageDescription
NSLocationAlwaysAndWhenInUseUsageDescription

When I setup the solution you gave me the same way I see the below in the console.  Oddly enough though the location eventually shows up in the dialog.  So maybe my application is having some timing issue, but in my testing the console was throwing me a bit.  Thanks again man!!

2018-06-27 08:41:56.644 App11.iOS[73722:20800895] Currently does not have Location permissions, requesting permissions
2018-06-27 08:41:56.678 App11.iOS[73722:20800895] NotDetermined
Thread started: <Thread Pool> #3
Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #6
2018-06-27 08:42:00.714 App11.iOS[73722:20800895] AuthorizedWhenInUse
2018-06-27 08:42:00.732 App11.iOS[73722:20800895] Currently does not have Location permissions, requesting permissions
2018-06-27 08:42:00.744 App11.iOS[73722:20800895] AuthorizedWhenInUse
Thread started:  #7
Thread finished: <Thread Pool> #4
Thread started: <Thread Pool> #8
Thread started: <Thread Pool> #9
2018-06-27 08:42:08.760 App11.iOS[73722:20800895] Location permission denied, can not get positions async.
2018-06-27 08:42:08.793 App11.iOS[73722:20800895] Simulator user has requested new graphics quality: 100
Thread finished: <Thread Pool> #9
Thread finished: <Thread Pool> #8
2018-06-27 08:42:41.398 App11.iOS[73722:20800895] Currently does not have Location permissions, requesting permissions
2018-06-27 08:42:41.409 App11.iOS[73722:20800895] AuthorizedWhenInUse
2018-06-27 08:42:49.412 App11.iOS[73722:20800895] Location permission denied, can not get positions async.

**Comment by jamesmontemagno** [comment]
If you only need it when the app is running remove the following:

NSLocationAlwaysUsageDescription
NSLocationAlwaysAndWhenInUseUsageDescription
