### ISSUE TITLE
Altitude information is coming as 0 only 

### ISSUE THREAD

**Issue by parth1729** [jamesmontemagno/GeolocatorPlugin#256]
Version Number of Plugin: 4.5.0.6
Device Tested On: Honor 7 X , Oreo Update
Simulator Tested On:
Version of VS: VS 2017 
Version of Xamarin:  3.0.0.550146 Xamarin Forms
Versions of other things you are using:

### Steps to reproduce the Behavior
In demo application position.Altitude is returning 0 only.
Also while integraiting it has the same behavior.

### Expected Behavior
position.Altitude Should return actual Altitude

### Actual Behavior
position.Altitude is returning 0 only

### Code snippet
void CrossGeolocator_Current_PositionChanged(object sender, PositionEventArgs e)
	{

		Device.BeginInvokeOnMainThread(() =>
		{
			var position = e.Position;
			Positions.Add(position);
			count++;
			LabelCount.Text = $"{count} updates";
			labelGPSTrack.Text = string.Format("Time: {0} \nLat: {1} \nLong: {2} \nAltitude: {3} \nAltitude Accuracy: {4} \nAccuracy: {5} \nHeading: {6} \nSpeed: {7}",
				position.Timestamp, position.Latitude, position.Longitude,
				position.Altitude, position.AltitudeAccuracy, position.Accuracy, position.Heading, position.Speed);

		});
	}

### Screenshotst

![screenshot_20180619-235550](https://user-images.githubusercontent.com/503148/41616814-94411dd8-741c-11e8-8b6a-c6880485aa2b.jpg)

**Comment by jamesmontemagno** [comment]
I return what Android gives me: https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin/Android/GeolocationUtils.android.cs#L66
