### ISSUE TITLE
Exception while loading assemblies: Plugin.Geolocator.Abstractions

### ISSUE THREAD

**Issue by almutama** [jamesmontemagno/GeolocatorPlugin#257]
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Geolocator.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?

## Bug Information

Version Number of Plugin: 4.5.0.6
Device Tested On: Can't compile yet
Simulator Tested On: Can't compile yet
Version of VS: 15.7.4
Version of Xamarin: 4.10.10.2
Versions of other things you are using:
   Xam.Plugin.Battery: 3.0.1
   Xam.Plugin.DeviceInfo: 4.0.0.13
   Xam.Plugin.Media: 4.0.1.1
   Xam.Plugin.Settings 3.1.1
   Xamarin.Forms: 3.1.0.583944
   Xamarin.Forms.Maps: 3.1.0.583944

### Steps to reproduce the Behavior
  New Forms App then Nuget libs

### Expected Behavior
  Compile and run
### Actual Behavior
  Exception
### Code snippet
  NA
### Screenshotst
![image](https://user-images.githubusercontent.com/4400542/41833932-fe022194-785a-11e8-8fe4-1ff8f16a58a9.png)

**Comment by jamesmontemagno** [comment]
Did file->new and installed it didn't have any issues at all. Maybe try a clean and re-build... that DLL no longer exists as it is a single assembly now maybe nuget cached it wrong.
