### ISSUE TITLE
TaskCanceledException when GPS times out

### ISSUE THREAD

**Issue by rileykarson** [jamesmontemagno/GeolocatorPlugin#26]
## Bug 
Version Number of Plugin: 4.0.0-beta4
Device Tested On: Nexus 9 (6.0.1), LG G3 (6.0)

### Expected Behavior
I would expect the GeolocationAvailable flag to be set to false, a null location, or some exception indicating what has happened other than TaskCanceled - something like GeolocatorTimeout, or NoGeolocatorPosition.

### Actual Behavior
When my device tries getting a lock with GetPositionAsync and some millisecond value, and has no GPS signal, it throws a TaskCanceledException.

### Steps to reproduce the Behavior
When inside a building
Turn on high accuracy (GPS only) GPS settings
Load an app with GetPositionAsync and some millisecond parameter.
Wait that long

**Comment by Bodmoor** [comment]
Using the android emulator, I always get this issue. Even though GPS should be emulated as well.

On device tests always provide a taskcancelledexception on android 5.0.1.

**Comment by jamesmontemagno** [comment]
That is the expected result if the geolocation can not be locked and found after the timeout.

the current beta is not stable, i would try beta12 or fall back to stable.
