### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by pollaris** [jamesmontemagno/GeolocatorPlugin#261]
In your documentation at

https://jamesmontemagno.github.io/GeolocatorPlugin/

you suggest a bare minimum of:

CrossCurrentActivity.Current.Activity.Init(this, bundle);

In my project Init was undefined.  I used:

Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;

inside android OnCreate() instead.  Working fine, thank you for an excellent plugin.

**Comment by jamesmontemagno** [comment]
Yes, either is fine, but I would like people to use Init
