### ISSUE TITLE
MoveToRegion when I user Mobile Data Don't redirect me to the Current Position just stay in Rome 

### ISSUE THREAD

**Issue by AbanoubSedrak7** [jamesmontemagno/GeolocatorPlugin#266]
## Bug Information

Version Number of Plugin:4.5.0.6
Device Tested On:Android 7.0-API 24
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 3.0
Versions of other things you are using:

### Steps to reproduce the Behavior
When  i Call MoveToRegion Function Using WIFI It Works Fine and Redirect Me To The Target Location But When i Use Mobile Data The Position Not Updated and Stay in Rome
### Expected Behavior
When I User Mobil Data The MoveToRegion Works as Using WIFI
### Actual Behavior
Stay in ROme
### Code snippet
  var position = new Position(
                    geolocatorService.Latitude,
                    geolocatorService.Longitude);
                Device.BeginInvokeOnMainThread(() =>
                {
                    MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(
                   position,
                   Distance.FromKilometers(.5)));
                });

**Comment by jamesmontemagno** [comment]
I don't think that is this plugin at all sorry.
