### ISSUE TITLE
Cannot use in conjunction with Xamarin.Forms.Maps due to version conflict

### ISSUE THREAD

**Issue by tbenum** [jamesmontemagno/GeolocatorPlugin#268]
Version Number of Plugin: 5.0.0.187-beta 
Device Tested On:Android
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 3.2.0.729530-pre2
Versions of other things you are using:

### Steps to reproduce the Behavior

I cannot seem to figure how to use this plugin together with Xamarin forms maps on Android, I get the following package incompatibility issue:

NU1107: Version conflict detected for Xamarin.GooglePlayServices.Base. Reference the package directly from the project to resolve this issue. 
 UsynligO.Android -> Xamarin.Forms.Maps 3.2.0.729530-pre2 -> Xamarin.GooglePlayServices.Maps 60.1142.1 -> Xamarin.GooglePlayServices.Base (= 60.1142.1) 
 UsynligO.Android -> Xam.Plugin.Geolocator 5.0.0.187-beta -> Xamarin.GooglePlayServices.Location 60.1142.0 -> Xamarin.GooglePlayServices.Base (= 60.1142.0).
Package restore failed.  

Is there a way I can work around this? Is the only way to extract the dll and add it as a reference manually?

**Comment by NehpetsEtnam** [comment]
Have you tried to add Xamarin.GooglePlayServices.Base version >= 60.1142.1 then add this plug in? I think it will work.

**Comment by jamesmontemagno** [comment]
I no longer support 5.0
