### ISSUE TITLE
Android background updates SIMPLE example

### ISSUE THREAD

**Issue by zois** [jamesmontemagno/GeolocatorPlugin#272]
Hello,

thank you for providing this very useful plugin, I am using it in many of my projects!
My question is that for a new app I want to create, I need now to get location updates in the background. I have successfully done that for iOS since its quite simple.
But for android, you are not providing a simple example, you pretty much redirect everyone to the MyDriving app, which is at least for beginner somewhat confusing :)
A very simple example of a Foreground service, MainActivity and Shared code would be very very helpful! That is give an example for your own sentence:
"_For this you will want to integrate a foreground service that subscribes to location changes and the user interface binds to._".
A very simple one :)

Thank you very much in advance!

Zois

**Comment by Klewerro** [comment]
Try this
Interface:
    `public interface IGeolocationBackgroundService
    {
        void StartService();
        void StartTracking();
    }`

ViewModel:

        public ICommand StartTrackingCommand => new Command(async () =>
        {
            if (CrossGeolocator.Current.IsListening)
            {
                await CrossGeolocator.Current.StopListeningAsync();
            }

            CrossGeolocator.Current.DesiredAccuracy = 25;
            CrossGeolocator.Current.PositionChanged += Geolocator_PositionChanged;

            await CrossGeolocator.Current.StartListeningAsync(
                TimeSpan.FromSeconds(3), 5);
        });

        private void Geolocator_PositionChanged(object sender, PositionEventArgs e)
        {
            var position = e.Position;
            _currentUserPosition = position;
            var positionString = $"Latitude: {position.Latitude}, Longitude: {position.Longitude}";
            CoordinatesString = positionString;
            Device.BeginInvokeOnMainThread(() => CoordinatesString = positionString);
            userPositions.Add(positionString);
            Debug.WriteLine($"Position changed event. User position: {CoordinatesString}");
        }

Service:

    [assembly: Dependency(typeof(GeolocationService))]
    namespace Backgrounding.Droid.Services
    {
    
    [Service]
    public class GeolocationService : Service, IGeolocationBackgroundService
    {
        private static readonly string CHANNEL_ID = "geolocationServiceChannel";
        public GeolocatorPageViewModel ViewModel { get; private set; }

        public override IBinder OnBind(Intent intent)
        {
            return null;
        }

        public GeolocationService()
        {
            CreateNotificationChannel();
        }

        private void CreateNotificationChannel()
        {
            NotificationChannel serviceChannel = new NotificationChannel(CHANNEL_ID,
                "GeolocationService", NotificationManager.ImportanceDefault);
            NotificationManager manager = Forms.Context.GetSystemService(Context.NotificationService) as NotificationManager;

            manager.CreateNotificationChannel(serviceChannel);

        }

        //[return: GeneratedEnum]
        public override StartCommandResult OnStartCommand(Intent intent, [GeneratedEnum] StartCommandFlags flags, int startId)
        {
            var newIntent = new Intent(this, typeof(MainActivity));
            newIntent.AddFlags(ActivityFlags.ClearTop);
            newIntent.AddFlags(ActivityFlags.SingleTop);

            var pendingIntent = PendingIntent.GetActivity(this, 0, newIntent, 0);

            var builder = new Notification.Builder(this, CHANNEL_ID);
            var notification = builder.SetContentIntent(pendingIntent)
                .SetSmallIcon(Resource.Drawable.ic_media_play_light)
                .SetAutoCancel(false)
                .SetTicker("Locator is recording")
                .SetContentTitle("GeolocationService")
                .SetContentText("Geolocator is recording for position changes.")
                .Build();

            StartForeground(112, notification);
            //ViewModel = new GeolocatorPageViewModel();
            return StartCommandResult.Sticky;
        }



        public void StartService()
            => Forms.Context.StartService(new Intent(Forms.Context, typeof(GeolocationService)));



        public void StartTracking()
        {
            ViewModel = new GeolocatorPageViewModel();
            ViewModel.StartTrackingCommand.Execute(null);
        }
    }

I don't know if it's best way to do this, but it's working :)

**Comment by jamesmontemagno** [comment]
Basically ^ 

And https://github.com/Azure-Samples/MyDriving/tree/master/src/MobileApps/MyDriving/MyDriving.Android/Services
