### ISSUE TITLE
Hello community,

### ISSUE THREAD

**Issue by tsantinho** [jamesmontemagno/GeolocatorPlugin#277]
I'm using Xamarin Forms 3.2 and Geolocator plugin 4.5.0.6 and i believe that 
this issue is not resolved yet, when you are in house and you not get gps location, then you call GetPositionAsync with any timeout then plugin doesn't return any callback.

Is there anything I'm doing wrong?

I have checked "improve location accuracy" and this option is on, my device is Honeywell CT50 running Android 6.0

_Originally posted by @tsantinho in https://github.com/jamesmontemagno/GeolocatorPlugin/issues/15#issuecomment-424405025_

**Comment by jamesmontemagno** [comment]
You can pass in a longer timeout and make sure your device's location is on. I also recommend using Xamarin.Essentials to get position now. This plugin works for me just fine.
