### ISSUE TITLE
Err Name Not Resolved on Maps

### ISSUE THREAD

**Issue by mick1313** [jamesmontemagno/GeolocatorPlugin#28]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: VS Droid Emulator
Simulator Tested On: Visual Studio

I am using the location code like so....
                        var position = await locator.GetPositionAsync(10000);
                        var success = await CrossExternalMaps.Current.NavigateTo("Current", position.Latitude, position.Longitude);

But when the maps open on the simulator I get :+1: 

![image](https://cloud.githubusercontent.com/assets/1896074/18284338/bedc6478-7426-11e6-8d33-9f0569da7152.png)

If I pass in a known Lat and Long like the Space Needle example, the Cross external maps works just fine.  Am I missing something

**Comment by jamesmontemagno** [comment]
Can you post over at: https://github.com/jamesmontemagno/LaunchMapsPlugin

**Comment by jamesmontemagno** [comment]
Also, are you sure that you emulator has internet?
