### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.  Parameter name: cancel

### ISSUE THREAD

**Issue by srsivaprasad** [jamesmontemagno/GeolocatorPlugin#29]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

got an error  
System.ArgumentNullException: Value cannot be null.

Parameter name: cancel

Version Number of Plugin: 3.0.4

Simulator Tested On
### Steps to reproduce the Behavior

installed the nuget to both the plc and in the native application Android .

in my constructor i coded 

 try
            {
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;

```
            var position = await locator.GetPositionAsync(timeoutMilliseconds: 10000);

            dynamic p1 = position.Timestamp;
            p1 = position.Latitude;
            p1 = position.Longitude;
        }
        catch (Exception ex)
        {
            DisplayAlert("", ex.Message, "");
        }
```

i got an exception as mentions.

 the stack trace is like :

{System.Threading.Tasks.TaskCanceledException: A task was canceled.\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0002d] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:179 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 \n  at Plugin.Geolocator.GeolocatorImplementation+<GetPositionAsync>d__27.MoveNext () [0x00597] in C:\projects\xamarin-plugins\Geolocator\Geolocator\Geolocator.Plugin.Android\GeolocatorImplementation.cs:175 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00027] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:176 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/2923/52635947/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 \n  at TicTacToe.Views.GeolocatorPage+<getLocation>d__0.MoveNext () [0x00075] in c:\Users\sivaprasad.sr\Documents\Visual Studio 2013\Projects\TicTacToe\TicTacToe\TicTacToe\Views\GeolocatorPage.xaml.cs:28 }

**Comment by jamesmontemagno** [comment]
Unable to reproduce
