### ISSUE TITLE
Anyone use this to track a users location on a map?

### ISSUE THREAD

**Issue by tekinc** [jamesmontemagno/GeolocatorPlugin#292]
For common questions and issues see the [FAQ](https://jamesmontemagno.github.io/GeolocatorPlugin/FAQ.html)

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
https://github.com/Azure-Samples/MyDriving/tree/master/src/MobileApps/MyDriving

**Comment by tekinc** [comment]
Thanks, do you know of a sample where tracking is implemented in xamarin forms? I'm trying to implement  inside XF but can't get an accurate user trail. It seems that the geo location of the user constantly moves(100 feet or more) even when the user is standing still.

**Comment by chrisfoulds** [comment]
I have a running app on both ios and android that uses this plugin , works perfectly.

**Comment by tekinc** [comment]
How are you using it? My use case is I want to track a users path. 

> I have a running app on both ios and android that uses this plugin , works perfectly.

**Comment by tekinc** [comment]
> I have a running app on both ios and android that uses this plugin , works perfectly.

Can you send me a itunes link to your running app? 

Thanks

**Comment by tekinc** [comment]
> I have a running app on both ios and android that uses this plugin , works perfectly.

I just tested with your app and it reproduces the same bug. 
![tracking](https://user-images.githubusercontent.com/1194213/53601577-5f27bf00-3b7a-11e9-89aa-08a4042e6938.png)

**Comment by chrisfoulds** [comment]
Congratulations on finding my app, I am not sure what app you are showing above as that is not mine.
Anyway in the above screenshot it is showing extremely low confidence (hence large blue circle) and the movement is caused by GPS jitter as there is no filtering algorithm

**Comment by tekinc** [comment]
Sorry, thought I found your app. I'm seeing the same issue using this plugin.

**Comment by chrisfoulds** [comment]
It is NOT the plugin. The screenshot clearly shows GPS jitter with low accuracy, the plugin provides raw data it is upto you to filter and smooth it all out.

**Comment by tekinc** [comment]
Ah I see. so what would you recommend the strategy be? Do you have any sample code? I appreciate the feedback.

**Comment by jamesmontemagno** [comment]
I did something like this: https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving/ViewModel/CurrentTripViewModel.cs#L486
basically calculate the distance from a previous point and if it is too big or too small don't use it.

**Comment by tekinc** [comment]
Got it, that makes sense.

**Comment by tekinc** [comment]
> I did something like this: https://github.com/Azure-Samples/MyDriving/blob/master/src/MobileApps/MyDriving/MyDriving/ViewModel/CurrentTripViewModel.cs#L486
> basically calculate the distance from a previous point and if it is too big or too small don't use it.

One under question, why not just filter out the positions by accuracy? Would that work? 

Thanks again.
