### ISSUE TITLE
App crashed in GetPositionAsync call for android P

### ISSUE THREAD

**Issue by nmano2188** [jamesmontemagno/GeolocatorPlugin#301]
## Bug Information

Version Number of Plugin: 4.5.4-beta
Device Tested On: Samsung A10
Simulator Tested On:
Version of VS: VS2015
Version of Xamarin:

I'm getting ClassNotFound Error while calling "GetPositionAsync" method.

Below is stack trace
05-21 16:14:13.305 E/AndroidRuntime( 7455): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at gu.b(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):3)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at gr.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):3)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at gt.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):14)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at com.google.maps.api.android.lib6.drd.ak.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):4)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at fv.a(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):22)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at fv.run(:com.google.android.gms.dynamite_mapsdynamite@17122077@17.1.22 (100300-245988633):8)
05-21 16:14:13.305 E/AndroidRuntime( 7455): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000000e/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000000e/MapsDynamite.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/0000000e/MapsDynamite.apk!/lib/armeabi, /system/lib]]
Thread started:  #1705-21 16:14:13.305 E/AndroidRuntime( 7455): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)

05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at ab.loadClass(:com.google.android.gms.dynamite_dynamiteloader@17122077@17.1.22 (100300-245988633):4)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-21 16:14:13.305 E/AndroidRuntime( 7455): 	... 6 more
Unhandled Exception:

Java.Lang.NoClassDefFoundError: <Timeout exceeded getting exception details>

**Comment by chrisfoulds** [comment]
Google broke ?
Literally the first result if you type in java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" 


https://stackoverflow.com/questions/50782806/android-google-maps-java-lang-noclassdeffounderror-failed-resolution-of-lorg-a

**Comment by nmano2188** [comment]
Fixed. Thanks @chrisfoulds
