### ISSUE TITLE
GetPositionAsync is slower than Xamarin.Essentials.Geolocation.GetLocationAsync

### ISSUE THREAD

**Issue by ImGonaRot** [jamesmontemagno/GeolocatorPlugin#303]
Xam.Plugin.Geolocator 4.5.0.6

I was going to replace the Xamarin.Essentials.Geolocation.GetLocationAsync with the GetPositionAsync from the GeolocatorPlugin but noticed that the "timeout" parameter in GetPositionAsync does not work that same as the Essentials call.

Here is the exact test code I am using on the Visual Studio 2019 Android Emulator (81. API 27)
```C#
GeolocationRequest geolocationRequest = new GeolocationRequest(GeolocationAccuracy.High, TimeSpan.FromSeconds(20));
Location location = await Geolocation.GetLocationAsync(geolocationRequest, token);
```

```C#
var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = 10;
var location = await locator.GetPositionAsync(TimeSpan.FromSeconds(20), token, true);
```

GetLocationAsync returns within a second BUT GetPositionAsync does not return until the "timeout" property has been reached.
In GetPositionAsync if I set the timeout = 60 seconds, then I don't get a position for 60 seconds.

**Comment by jamesmontemagno** [comment]
We calculate things different for the accuracy/precision. 

You should use Xamarin.Essentials.

**Comment by ImGonaRot** [comment]
While I have no doubt that your code calculates things different than the Xamarin.Essentials version, I really would prefer to use your version.

The Essentials version does not work at all when the droid is on power saver mode, where as your version at least returns a "cached" version of the coordinates, the Essentials version just does nothing on the call.

This above post seems like a bug in that when I put a time in the 1st parameter (Timeout to wait, Default Infinite) of GetPositionAsync, it should represent how long before the call gives up and stops trying to ask for the GPS coordinate, BUT that is not what it is doing at all. Instead, it is pausing the GetPositionAsync for the length of the 1st parameter (Timeout to wait) before it return the coordinate. Even though I am 100% sure it does not take 9+ seconds to get a GPS coordinate on the android emulator.

I would assume that if I put in 9 seconds, then it has up to 9 seconds to try and find GPS coordinates BUT instead it is pausing 9 seconds before it returns the GPS coordinates. 

Am I using the parameter incorrectly?
