### ISSUE TITLE
Issue on Ios 10

### ISSUE THREAD

**Issue by markobls** [jamesmontemagno/GeolocatorPlugin#31]
I always use this plugin to get my latitude and longitude and never had problem with that.

But now with IOS 10, I dont know why it dosnt give the latitude/longitude.. and its not asking to Active your Location on device.

is there any change with ios 10 ?
Im testing on device.
On android is working Fine.

My info.plist
    <key>NSLocationAlwaysUsageDescription</key>
    <string>Ative sua geolocalização</string>

My Code
 var locator = CrossGeolocator.Current;
     var position = await locator.GetPositionAsync(10000);

**Comment by jamesmontemagno** [comment]
Are you sure the permission was granted on the device?

**Comment by markobls** [comment]
Yea..

I uninstalled and installed again on device, but the prompt to "Allow to app get your location ...." dosn't appear anymore..
It is not asking to get my location and on my info.plist there is the string to NSLocationAlwaysUsageDescription
On android is working fine
What should i Do?

**Comment by markobls** [comment]
Well,

Well, I saw that sometimes the prompt appear, but it dosnt give the chance to click on "allow".. it appear so fast and close..
And when I go to App Settings on Settings from iphone, there is no "Allow Location".

=(
@jamesmontemagno

**Comment by jamesmontemagno** [comment]
Hmmm seems like something else happening in the code. I would try to use the Permission Plugin to handle requesting for Geolocation permission, that is best practice.

**Comment by markobls** [comment]
Hmm..
What should i do then ?

@jamesmontemagno

**Comment by jamesmontemagno** [comment]
Checkout the sample code here:
https://github.com/jamesmontemagno/PermissionsPlugin after installing the nugets into all projects.

Specifically this: https://github.com/jamesmontemagno/PermissionsPlugin#in-action will help out.

That said though... remember on iOS after the dialog has come up once and your user has rejected it or ignored it, it will NEVER come up again. You must go and tell them to go into their settings. In the evolve app we did this:

https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Clients.Portable/Services/ReminderService.cs#L116

**Comment by jamesmontemagno** [comment]
I would try to uninstall the app and re-install so it comes up the first run again. It will wait for you to approve or reject unless your code is doing something weird and not awaiting on calls.

**Comment by markobls** [comment]
James,

I tried and followed your code, but here:
**var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Location });**

He stands here and have no answer, I waited for 5 minutes, but it dosnt move from this line..
:S

Here you can see the status value and the info.plist

![a2](https://cloud.githubusercontent.com/assets/9846536/19141356/19def8ee-8b6b-11e6-9d2d-b8073a688cca.png)
![e1](https://cloud.githubusercontent.com/assets/9846536/19141357/19df46e6-8b6b-11e6-8600-6f37340d37a9.png)

@jamesmontemagno

**Comment by alanspires** [comment]
Try wrapping it in Device.BeginInvokeOnMainThread I've seen scenarios where this seems to fix it. Just a thought.
