### ISSUE TITLE
Longitude/LAtitude changed on Some iOS Devices

### ISSUE THREAD

**Issue by SSpormann** [jamesmontemagno/GeolocatorPlugin#315]
## Bug Information

Version Number of Plugin: 4.5.0.6
Device Tested On: iPhone XR / iPhone SE
Simulator Tested On: - 
Version of VS: 2019 Enterprise
Version of Xamarin: 13.4 / 4.2.0.848062
Versions of other things you are using:

### Steps to reproduce the Behavior
    var locator = CrossGeolocator.Current;
                                locator.DesiredAccuracy = 50;
                                Plugin.Geolocator.Abstractions.Position position = await locator.GetPositionAsync(new TimeSpan(0, 0, 0, 1));
                                var Logitude = position.Longitude.ToString();
                                var Latitude = position.Latitude.ToString();
                                //if (!position.IsFromMockProvider)
                                //{
                                try
                                {
                                    string jscript = null;

                                    if (Device.RuntimePlatform == Device.iOS)
                                    {
                                        jscript = "setPosition('" + Latitude + "','" + Logitude + "');";
                                    }
                                    else
                                    {
                                        jscript = "setPosition('" + Logitude + "','" + Latitude + "');";
                                    }

### Expected Behavior

Expected is that i don't have to use the else block, I dont on iPhone SE, here it yields an error, 

### Actual Behavior
on the iPhone XR the behavior is correct, but the contetn is swaped.  I can not say what causes this behavior, the devices both have iOS 13.1.2 installed, and it works fine if i use the native implementation in non xamarin apps.

### Code snippet
see above 
### Screenshotst
if you want to I can add a dump later.

**Comment by jamesmontemagno** [comment]
We set what CLLocaiton gives us: https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin/Apple/GeolocationSingleUpdateDelegate.apple.cs#L115-L116

https://github.com/jamesmontemagno/GeolocatorPlugin/blob/master/src/Geolocator.Plugin/Apple/GeolocatorImplementation.apple.cs#L522-L523

are you sure the jscript isnt' the cause here?

**Comment by SSpormann** [comment]
after some more reseach and looking through lots of code. It seems to happen on manual implementation as well, feel free to close this issue, i belive it must be in mono or xamarin, my guess is its a mono problem the xamarin code looks fine as well.

**Comment by jamesmontemagno** [comment]
Can you post an issue: https://github.com/xamarin/xamarin-macios if the swift/obj-c differs from c#

I don't think anything has changed in a long while: https://github.com/xamarin/xamarin-macios/tree/master/src/CoreLocation
