### ISSUE TITLE
[iOS] Blue header when backgrounded

### ISSUE THREAD

**Issue by padic-dev** [jamesmontemagno/GeolocatorPlugin#317]
## Bug Information

Version Number of Plugin: 4.5.0.6
Device Tested On: iPhone Xr with iOS 13.1.3
Simulator Tested On: N/A
Version of VS: 2019 16.3.4
Version of Xamarin: 3.1.0.697729
Versions of other things you are using: Plugin.Permissions 4.0.2-beta

### Steps to reproduce the Behavior
1. Launch my app
2. Login to enable location listening
3. Swipe up on bottom handle to send to background

### Expected Behavior
After step 3 the top right corner should turn blue with the location arrow indicator.

### Actual Behavior
After step 3 the top right corner remains black with time and location arrow indicator to the right of the time.

### Code snippet
Upon login the following is run to begin listening:
success = await CrossGeolocator.Current.StartListeningAsync(time, distance, false, new ListenerSettings {
    ActivityType = ActivityType.Other,
    AllowBackgroundUpdates = true,
    DeferLocationUpdates = true,
    DeferralDistanceMeters = distance,
    DeferralTime = time,
    ListenForSignificantChanges = true,
    PauseLocationUpdatesAutomatically = false
});

info.plist:

...
<key>UIBackgroundModes</key>
<array>
	<string>location</string>
	<string>fetch</string>
</array>
...
<key>NSLocationWhenInUseUsageDescription</key>
<string>[redacted]</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>[redacted]</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>[redacted]</string>
...

### Comments

I can't quite figure out if there is something I am missing and/or doing wrong here to get the standard blue header notification to appear once my app goes into the background while the location listener is active.  

I have used logging to verify the listener is working in the background.

If I set the permissions for the app to Location: Always, send it to the background then go into the settings and switch from Location: Always to Location: In Use the blue indicator appears until I bring the app to the foreground.  If permissions are set to Location: In Use I cannot get the blue indicator to appear at all.  Any advice here?

**Comment by mzaatar** [comment]
I believe the problem is that the `ShowsBackgroundLocationIndicator` is being exposed in the `ListenerSettings` object. It supposed to be exposed.

**Comment by padic-dev** [comment]
Thanks for the reply but I cannot seem to find that build as an option within VS 2019 Nuget Manager. I am currently using 4.5.4-beta which is the highest version available.

![Microsoft Visual Studio (Administrator)](https://user-images.githubusercontent.com/39010826/72456266-550eaf00-3792-11ea-8c49-6cabde464257.png)
