### ISSUE TITLE
On UWP getting speed property value as NaN

### ISSUE THREAD

**Issue by prajaktashindeSilicus** [jamesmontemagno/GeolocatorPlugin#327]
For common questions and issues see the [FAQ](https://jamesmontemagno.github.io/GeolocatorPlugin/FAQ.html)

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.5.0.6
Device Tested On: HP ELITEBOOK X360 1030 G4
Simulator Tested On: Local machine of UWP 
Version of VS: VS Professional 2019 V 16.6.5
Version of Xamarin: 16.6.000.1064
Versions of other things you are using:

### Steps to reproduce the Behavior
I have followed this document
https://jamesmontemagno.github.io/GeolocatorPlugin/
### Expected Behavior
As location changes speed property should give some value on uwp as we are getting speed value on ios and Android in X.F. I want to capture speed of the device.
### Actual Behavior
Speed property is giving value NaN
### Screenshotst
![speed demo NAN](https://user-images.githubusercontent.com/32475659/90119332-0c929080-dd77-11ea-81fb-582a8d3abf96.jpg)

**Comment by Gakk** [comment]
I believe this is not the fault of this plugin, but rather a Windows 10 issue.

We have a navigation software written as a WPF application. It implements .NET Frameworks `System.Device.Location.GeoCoordinateWatcher`, and it does not report speed or heading either when run on Windows 10.

Both speed and heading has correct values when running our application on Windows 8.

**Comment by prajaktashindeSilicus** [comment]
Thanks @Gakk for the reply. I'm not sure what @jamesmontemagno has used. I have tested this on actual Windows 10 surface tablet too. Any other help is appreciated.

**Comment by jamesmontemagno** [comment]
Integrating #311
