### ISSUE TITLE
Network provider on Android 5.0 doesn' retrieve geolocation on Background mode

### ISSUE THREAD

**Issue by JanNepras** [jamesmontemagno/GeolocatorPlugin#33]
## Bug

Version Number of Plugin: 3.0.4
Device Tested On: 
Samsung s3 mini, Android 4: ok
Huawei P8 Lite, Android 5: issue
Alcatel Pixi 4, Android 6: ok
Simulator Tested On: none
### Expected Behavior

As a user I woud like to retrieve geolocation every specified interval, when the phone is locked on background mode.
### Actual Behavior

Geolocations are not beeing retrieved when the device is locked within network provider. This happens just on Huaweii P8 Lite.
### Steps to reproduce the Behavior

1/ Run this code
            var locator = CrossGeolocator.Current;
            locator.DesiredAccuracy = 100;
            locator.AllowsBackgroundUpdates = true;
            await locator.StartListeningAsync(1000 \* 60 \* 5, 0, false);
2/ Stay in the building or somewhere where the network provider is in use.

Is it expected behaviour or a bug? Does it mean that network provider sensor is not charged on Huaweii P8 lite and this is the reason why it doesn't retirieve any geolocation? In that case could be there some detection, that this sensor doesn't work on background?

**Comment by jamesmontemagno** [comment]
I can't provide fixes for specific devices sorry. If the sensor is off then it wont provide geolocation. 

Are you running it in a background service like: https://github.com/azure-samples/mydriving
