### ISSUE TITLE
[iOS] Null reference exception from GetPositionAsync

### ISSUE THREAD

**Issue by Troto** [jamesmontemagno/GeolocatorPlugin#34]
## [iOS] Null reference exception from GetPositionAsync

Version Number of Plugin: 4.0.0-beta4
Device Tested On: iPhone 5s

### Expected Behavior
Position to be returned, normal GetPositionAsync behaviour.

### Actual Behavior
A null reference exception is being thrown.

### Steps to reproduce the Behavior
Nothing special.

```
readonly int _gpsSearchTimeout = 20000;
var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = 50;
position = await locator.GetPositionAsync(_gpsSearchTimeout);
```

Sorry I can't give you more useful information. That's all I get from the exception.

If it helps these are my info.plist keys:
```
<key>NSLocationAlwaysUsageDescription</key>
<string>Can we use your location?</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>Can we use your location?</string>
```

**Comment by jamesmontemagno** [comment]
Please upgrade to https://www.nuget.org/packages/Xam.Plugin.Geolocator/4.0.0-beta12 as it is the only valid beta
