### ISSUE TITLE
Android : LocationManager vs Fused Location

### ISSUE THREAD

**Issue by AlonRom** [jamesmontemagno/GeolocatorPlugin#347]
Hi,

According to what I read, the best way to get the current and last known location is with "Fused Location Provider" and not the "Location Manager". I think that the code in the GeoloacorPlugin is using the Location Manager.

1. Is it true that it's better to use "Fused Location Provider" in order to get the location?
2. Which one is this Plugin is using? and if it's using "Location Manager", why?

thanks!

**Comment by jamesmontemagno** [comment]
Fused Location Provider for sure is optimal, however it requires a dependency on Google Play Services which is why we do not use it as it would add other restrictions and dependencies.

**Comment by AlonRom** [comment]
thanks for the quick response @jamesmontemagno 
I just want to make sure I understand.
If I use the Fused Location Provider I won't be able to get the location from a device like Huawei for instance?
does the fact that my project includes Google Play Services nugets is even relevant to such devices?

**Comment by jamesmontemagno** [comment]
So, in Google Play Services you can check to see if they are available or not, and if not then you should go down another path to get that functionality.
