### ISSUE TITLE
MinTime in StartListeningAsync no effect in iOS

### ISSUE THREAD

**Issue by duizer** [jamesmontemagno/GeolocatorPlugin#35]
The iOS implementation of IGeoLocator does not use the parameter "minTime" in StartListeningAsync() (GeolocatorPlugin/src/Geolocator.Plugin.iOSUnified/GeolocatorImplementation.cs). The parameter is used in the Android implementation. 
I have tried to set the minTime to 10,000 in the iOS simulator. I would expect this would restrict  PositionChanged to be invoked with at least 10 seconds apart, but it is invoked every second.
## Bug

Version Number of Plugin: 3.0.4
Simulator Tested On: iOS 10 iPad Air 2

**Comment by jamesmontemagno** [comment]
This is as designed currently, in 4.X there is a new deffered updates that can be used
