### ISSUE TITLE
Readme.txt 

### ISSUE THREAD

**Issue by ericbrunner** [jamesmontemagno/GeolocatorPlugin#37]
## Bug

I had to set the ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION in the Droid project file. It is not automatically added as described here:

**IMPORTANT**
Android:
The ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION permissions are required, but the library will automatically add this for you. 
Additionally, if your users are running Marshmallow the Plugin will automatically prompt them for runtime permissions.

**Comment by jamesmontemagno** [comment]
It is added please check manifest it is in the assembly info.
