### ISSUE TITLE
Object not set to an instance on iOS Device

### ISSUE THREAD

**Issue by bnikollov** [jamesmontemagno/GeolocatorPlugin#38]
Hello, James. We are using geolocator in xamarin forms app to get location. In android - no problem. Then we test it on iOS device with iOS 10 and on GetLocationAsync() it throws exception "Object not set to an instance". What is the problem here? Thanks in advance!

**Comment by veryhumble** [comment]
I experience the same issue: Stacktrace:

```System.NullReferenceException: Object reference not set to an instance of an object
  at Plugin.Geolocator.GeolocatorImplementation.GetPositionAsync (System.Int32 timeoutMilliseconds, System.Nullable`1[T] cancelToken, System.Boolean includeHeading) [0x00086] in <804816ee43bf4ac6bdac94245c7fd590>:0 ```

I am on Version `4.0.0-beta4` on the iOS Simulator `10.1`

It does not happen if i call `StartListeningAsync()` first.

**Comment by jamesmontemagno** [comment]
Have you tried beta 12? https://www.nuget.org/packages/Xam.Plugin.Geolocator/4.0.0-beta12

**Comment by veryhumble** [comment]
Works with Beta 12, Thanks!
