### ISSUE TITLE
Nuget Package Description typo

### ISSUE THREAD

**Issue by rdaniel0** [jamesmontemagno/GeolocatorPlugin#40]
"Easly" is supposed to be spelt "Easily".
<img width="783" alt="screen shot 2016-11-01 at 07 43 33" src="https://cloud.githubusercontent.com/assets/18712717/19872779/3a4e76c6-a007-11e6-9dd7-fd99552d147c.png">

**Comment by jamesmontemagno** [comment]
Fixed up, thanks.
