### ISSUE TITLE
PositionChanged giving new GPS position when device is in static position

### ISSUE THREAD

**Issue by bernardlcn** [jamesmontemagno/GeolocatorPlugin#41]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug (or may not be) 
Hi James, i'm new to xamarin and also new to implementing Geo services solution.

The issue I'm facing currently is that if I put the phone on a static location (e.g on the table) without moving it, but then I noticed the PositionChanged event will keep firing periodically and give a new GPS location, isn't the GPS location of the phone should be always the same if it is in static position without moving around?

Is there anything that I have missed out? Please kindly advise. 
Much Appreciated and Thanks.

Version Number of Plugin: 1.0.3
Device Tested On: 31 October 2016
Simulator Tested On: Nil

### Expected Behavior
PositionChanged to retain the same GPS position when device is in static position

### Actual Behavior
PositionChanged giving new GPS position when device is in static position

### Steps to reproduce the Behavior
Below is partial of my code implementation. 

var locator = CrossGeolocator.Current;
        locator.DesiredAccuracy = 50;
        locator.PositionChanged += (s, e) =>
        {

                 try
                 {
                     var newPosition = e.Position;
                     Position newLogPosition = new Position(newPosition.Latitude, newPosition.Longitude);    
                     labelNewGPS.Text = "New GPS Location : Latitude :" + newLogPosition.Latitude + ", Longitude: " + newLogPosition.Longitude; ;
                 }
                     catch (Exception ex)
                 {
                     labelErrorMessage.Text = "Trip Log encountered error - " + ex.Message.ToString();
                 }
        };
        locator.PositionError += (s, e) =>
        {
              labelErrorMessage.Text = "Trip Log encountered error - " + e.Error.ToString();
        };

        ......
        ......

       if (!locator.IsListening)
       {
              await locator.StartListeningAsync(1000, 0);
       }

## Feature Request:
Please fill in what you would like

**Comment by fguarini** [comment]
I think this is not a problem with the nugget, but more with how GPS work. I experienced the same problem and fixed it by StartListening and subscribe to the event after some time with another Task (wait for a couple of seconds and then subscribe on another thread). Do that and you will be fine for the setup (start time). You still might get some weird readings later on, but that should fix your problem. Also to the StartListeningAsync you should give the second parameter a couple of metters since no GPS (at least the ones found inside smartphones) are that precise so a minimum distance to update will save you reading unuseful data.

**Comment by istoff** [comment]
Hi,

Having similar issues.  My testing with devices with/without SIMCards seems to put the blame on the Network Assisted GPS using WIFI/GSM towers to triangulate you.  It seems to go away if you set your mobile device to use GPS Sensor only under the Phone's location settings.  This behaviour was verified on 3 different devices from different manufacturers.

Ultimately, what would be nice would be a property for the Locator component to force which sensor(s) to use.  Will add as a separate issue.

Hope this helps.

**Comment by jamesmontemagno** [comment]
Closing as I report based on the device. 4.x has several improvements here though.
