### ISSUE TITLE
Android Nougat not work GetPositionAsync()

### ISSUE THREAD

**Issue by kikolopes90** [jamesmontemagno/GeolocatorPlugin#42]
## Bug 

I tested the next "locator.GetPositionAsync()" breakpoint and failed. Is it because of nougat?

Version Number of Plugin: 4.0.0-beta12
Device Tested On: 
Huawei P9 Lite, Android 6: Ok
OnePlus 1, Android 7: Crash or not work

### Steps to reproduce the Behavior

var locator = CrossGeolocator.Current;
var position = await locator.GetPositionAsync(); // Failed and does not show message error
pos = new Position(position.Latitude, position.Longitude);

**Comment by jamesmontemagno** [comment]
I would not recommend beta at this time. Please go back to 3.0.4 unless there is a specific need that you have for 4.0.0. I will be starting more work on it next week and will investigate.

**Comment by kikolopes90** [comment]
Test for "await locator.GetPositionAsync();"

Huawei P8, Android 5.0 Lollipop
4.0.0-beta12: work
3.0.4: work
3.0.3: work

Huawei P9 Lite, Android 6.0 Marshmallow
4.0.0-beta12: work
3.0.4: work
3.0.3: work

OnePlus 1, Android 7.0 Nougat
4.0.0-beta12: not work
3.0.4: not work
3.0.3: not work

I already tested two my different applications, and the only one does not work is nougat.

**Comment by ConsentDevelopment** [comment]
I am also having a similar issue.

First time giving permission for the app to use the GPS the GetPositionAsync() method never returns 
but when running the app after giving the permission then it then works.

Device - Nexus 5
Device Android version - 7.0
App Android SDK built with and  target  - 7.0

**Comment by abdul-qadirdeveloper** [comment]
i am testing it on LG-E970 with following code
            try
            {
                var position = await locator.GetPositionAsync(10000);
                if (position == null)
                {
                    lblGeoLocation.Text = "Null GPS";
                    return;
                }
            await LogPosition(position);
            }catch(TaskCanceledException ex)
            {

            }
but it is always throwing exception TaskCancelledException.
how could I avoid this exception.

in MainPage Constructor, I am using CrossGeolocator as follows
            locator = CrossGeolocator.Current;
            locator.AllowsBackgroundUpdates = true;                  
            locator.DesiredAccuracy = 10;
            lblGeoLocation.Text = "Getting GPS";
            locator.PositionChanged += Locator_PositionChanged;
            locator.PositionError += Locator_PositionError;

**Comment by jamesmontemagno** [comment]
Have you tried the sample in:
https://github.com/jamesmontemagno/GeolocatorPlugin/tree/master/samples

I ran this as is on my Nexus 6P running Android 7.1 and worked out of the box. Double check your project settings and ensure you setup the permissions code.

I just want to make sure we are all working from the same sample.

The current is 3.0.4 and then I updated all Nugets to the beta-12

**Comment by ConsentDevelopment** [comment]
The sample works for me running on Nexus 5 with Android version 7.

I will look into my own project to see why the GetPositionAsync() method hangs after giving permission.

Thanks for the update.

**Comment by ConsentDevelopment** [comment]
Ok, I found the issue in my project.

You have to have the following method call in the MainActivity,OnRequestPermissionsResult() method :

  PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

This will let the permissions module know that the user has granted the location permission to be used.

This is why the method call GetPositionAsync() was hanging the first time after giving permission as it was waiting for the permission to be granted before continuing.

**Comment by jamesmontemagno** [comment]
That is correct. The readme directions tell you this on all plugins that use the permissions plugin.

**Comment by ConsentDevelopment** [comment]
Actually the plugin readme does not mention this. The readme for Android just has the following -
```
**IMPORTANT**
Android:
The ACCESS_COARSE_LOCATION & ACCESS_FINE_LOCATION permissions are required, but the library will automatically add this for you. 
Additionally, if your users are running Marshmallow the Plugin will automatically prompt them for runtime permissions.
```
It would be worthwhile to also mention in the readme that the MainActivity.cs code I mentioned above should be added to a project that wants to use the GeolocatorPlugin for Android.

People will just be installing the nuget package and then calling the method  GetPositionAsync() and wonder why it is not working.

**Comment by jamesmontemagno** [comment]
I added it here https://github.com/jamesmontemagno/geolocatorplugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code
also it is in the readme.txt that pops up.

Closing this now because I can't reproduce.
