### ISSUE TITLE
[Android] Problem with Background Location Refresh

### ISSUE THREAD

**Issue by fguarini** [jamesmontemagno/GeolocatorPlugin#44]
Version Number of Plugin:
-3.0.4
Device Tested On: 
-Samsung Galaxy Grand 2 (Android 4.4)
-LG Nexus 4 (Android 5)
-Alcatel Touch Idol (Android 4.1)
Simulator Tested On: 
-None

## Bug
I am running the following code inside the main thread of the application (inside the PLC) having no issues with iOS as the app continues listening to location updates even when the app is in background or the device is locked. But the position doesn't update on Android once I put it on background. Am I doing something wrong?, should I change the code to run on a new task on Android?. That might be the problem, but it's strange that the code works flawlessly on iOS but just doesn't seem to work on Android.

### Code (The relevant parts)
Locator = CrossGeolocator.Current;
Locator.AllowsBackgroundUpdates = true;
Locator.DesiredAccuracy = DESIRED_ACCURACY;
await Locator.StartListeningAsync(MINIMUM_TIME, MINIMUM_DISTANCE, false);
Locator.PositionChanged += OnPositionChangedHandler;

**Comment by jamesmontemagno** [comment]
Only iOS out of the box support background listening such as that.

On Android you must implement your own background service.

Here is a sample: https://github.com/Azure-Samples/MyDriving/tree/master/src/MobileApps/MyDriving/MyDriving.Android/Services

**Comment by fguarini** [comment]
@jamesmontemagno Excellent, thanks a lot for the quick response and also for the reference! Also thanks for the Nuget it's awesome 👍
