### ISSUE TITLE
Geolocator.GetPositionAsync handing if user press deny on the permissions popup

### ISSUE THREAD

**Issue by SlyNet** [jamesmontemagno/GeolocatorPlugin#46]
## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: Nexus 10 android 6

### Expected Behavior
`GetPositionAsync` throws missing permissions exception 

### Actual Behavior
`GetPositionAsync` never ends

### Steps to reproduce the Behavior
call `GetPositionAsync` and press deny on permissions popup

**Comment by jamesmontemagno** [comment]
Can't reproduce: https://github.com/jamesmontemagno/geolocatorplugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code

did you set the target == 23 or 24 in your manifest? Not to use compile.

it returns null. TEsts on nexus 6p.

**Comment by SlyNet** [comment]
Yes, target is 24, maybe thats because CrossPermissions.Current.RequestPermissionsAsync call has no `ConfigureAwait(false)`?..

**Comment by SlyNet** [comment]
I've noticed that such call `await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location)                                                            .ConfigureAwait(false)` does block a task entirely

**Comment by SlyNet** [comment]
Sorry, it was my fault. Forgot to add 
```
PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
```
in main activity

**Comment by jamesmontemagno** [comment]
It will not block any tasks at all.
