### ISSUE TITLE
Windows Phone 10 Not tracking if offline

### ISSUE THREAD

**Issue by reislanes** [jamesmontemagno/GeolocatorPlugin#47]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.0.4.0
Device Tested On: Lumia 930
Simulator Tested On:

### Expected Behavior

Catch coordinates

### Actual Behavior
When offline the exception task is canceled is thrown
### Steps to reproduce the Behavior

- device offline
- (
private async Task<Local> setgeo()
        {
            var locator = CrossGeolocator.Current;
            locator.DesiredAccuracy = 100; //100 is new default 
            var position = await locator.GetPositionAsync(timeoutMilliseconds: 10000);
            if (position != null)
            {
                gps.data = position.Timestamp;
                gps.latitude = position.Latitude;
                gps.longitude = position.Longitude;
            }
            return gps;
}

When device is connected works fine, if disconnected, no coordinates are returned. 

## Feature Request:
- Offline position tracking.

**Comment by reislanes** [comment]
Testing if could it be gps not getting coordinates, i tried the native Map app location and it works fine and responsive, while the plugin can't return a valid position.

**Comment by jamesmontemagno** [comment]
Do you just mean you turn on airplane mode?

**Comment by reislanes** [comment]
No, i mean not being connected to internet. Not wifi (my primary testing environment), neither 3g/4g internet connection. 
I've tested increase accuracy, it worked once and then stopped. 
I've implemented a try catch to deal with the error and automatically increase de accuracy meters each time the error occur, so it would decrease precision until the gps could get info, but it also didn't work. 
Sometimes, i open the app with the phone connected to internet, get the location, disconnect from internet with the app open and it gets my position fine at first try, but become unresponsive next ones.     
I was trying to replace an internet dependent web application used by our external sales team to check in and keep their manager up to date with their position and agenda. They sometimes visit places where there's no internet at all, and sometimes places where not even carrier signal, so a expected to use a local cache to store their check in info and later sync with our backend since the device gets a valid connection.

**Comment by groege** [comment]
Same problem here.

**Comment by nguyenthanhliemfc** [comment]
I'm using Lumia 950 XL build 14393 with latest this Plugin it working find even in airplane mode

**Comment by jamesmontemagno** [comment]
wasn't able to reproduce locally with 4.0
