### ISSUE TITLE
Getting rid of "isolated" GPS bad readings  

### ISSUE THREAD

**Issue by fguarini** [jamesmontemagno/GeolocatorPlugin#48]
@jamesmontemagno  (sorry really don't know where else to contact you to ask this).

I have been using your plugin successfully on Android and iOS, but sometimes when using my app I get weird readings (which I think are a result of going close to tall buildings which affect the signal quality or precision of the GPS), showing up as "weird spikes" (isolated points) when looked at a map. Then when the signal reestablishes it starts reading everything right 👍 

Looking up at the code of "MyDriving" which you gave me as a reference to run the Android Service on the background, I can't seem to find how you fixed this (if you did). I thought to use the GPS signal quality but really cant find a way to do so on Xamarin Forms. Do you know a way I can get rid of this "bad readings"?

pd: Also thought about using the compass, but not all devices have compass so it wouldn't work.. Right now I am calculating the acceleration as a magnitude and using that to eliminate some of those wrong readings but if you know a better way I would really appreciate it.

Also if you need more information please let me know!

**Comment by fguarini** [comment]
Just realized that the returned object has "Accuracy" (my bad). Which do you think would be the sweet spot for measuring car positional data (from your experience). Meaning the "maximum tolerable accuracy value".

**Comment by istoff** [comment]
Does the problem go away if you change the device location settings to GPS Only?  Having mixed results using the Network assisted Location.

**Comment by fguarini** [comment]
@istoff Will check on the weekend and report back.
