### ISSUE TITLE
Creating IGeolocator object in App.cs on Android with Xamarin 4.2.1.73 crashes app with System.NullReferenceException.. 

### ISSUE THREAD

**Issue by calbert52** [jamesmontemagno/GeolocatorPlugin#49]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
Creating IGeolocator object in App.cs on Android with Xamarin 4.2.1.73 crashes app with System.NullReferenceException
[DebugOutputWindow.txt](https://github.com/jamesmontemagno/GeolocatorPlugin/files/666765/DebugOutputWindow.txt)
![screen1](https://cloud.githubusercontent.com/assets/15325409/21395610/17ba2e4e-c76b-11e6-8c9f-1db9b2535cf1.png)
![screen2](https://cloud.githubusercontent.com/assets/15325409/21395611/17c42c0a-c76b-11e6-9088-3662e815c04b.png)

Version Number of Plugin: 3.0.4
Device Tested On:
Simulator Tested On: VS Emulator 5.1" Marshmallow (6.0.0) Android 6.0 API 23

### Expected Behavior
After creating the location object, the app code should continue to execute. Sample creation of object below:
public static IGeolocator loc = CrossGeolocator.Current;

### Actual Behavior
crashes app with System.NullReferenceException

## Feature Request:
Please fill in what you would like

**Comment by calbert52** [comment]
Additional info when run as release, see "Screen3.png".
![screen3](https://cloud.githubusercontent.com/assets/15325409/21398798/ccff6994-c776-11e6-9121-0a46c45c4718.png)

**Comment by jamesmontemagno** [comment]
Did you try not making it static and just using it as CrossGeolocator.Current that is the supported mechanism.
