### ISSUE TITLE
IGeoLocator TimeSpan? added to interface, but not implementations

### ISSUE THREAD

**Issue by statecb** [jamesmontemagno/GeolocatorPlugin#50]
## Bug 

It could be my lack of full understanding of the Git environment, but the IGeoLocator interface was updated to use TimeSpan? instead of int (milliseconds) but the implementation was not updated.  As a result the build is currently broken.

**Comment by jamesmontemagno** [comment]
The current repo is a work in progress and reflects 4.0.
