### ISSUE TITLE
How to use the speed value

### ISSUE THREAD

**Issue by wsteinbinder** [jamesmontemagno/GeolocatorPlugin#51]
I was checking out the GeolocatorPlugin on the Android Emulator. The values of Timestamp, Latitude and Longitude just work fine except of the speed value

### Expected Behavior
Receiving a speed value while chainging the GPS point.

### Actual Behavior
Receiving the value 0

### Steps to reproduce the Behavior

    private async void GetGeolocation() {
         this.locator = CrossGeolocator.Current;
         this.locator.DesiredAccuracy = 50;
         await this.locator.StartListeningAsync(1000, 0);

         this.position = await this.locator.GetPositionAsync(timeoutMilliseconds: 1000);

         this.locator.PositionChanged += (sender, e) => {
               this.position = e.Position;

               this.Status.Text = "Position Status: " + this.position.Timestamp;
               this.Lat.Text = "Position Latitude: " + this.position.Latitude;
               this.Long.Text = "Position Longitude: " + this.position.Longitude;
               this.Speed.Text = "Speed: " + this.position.Speed + " m/s";
            };
      }

## Feature Request:
How to handle the speed value correct?

**Comment by jamesmontemagno** [comment]
See: https://developer.android.com/reference/android/location/Location.html#getSpeed()
