### ISSUE TITLE
TaskCanceledException when running GeolocatorSample on subsequent runs

### ISSUE THREAD

**Issue by imgregduh** [jamesmontemagno/GeolocatorPlugin#52]
## Bug 
Version Number of Plugin: 3.0.4.0
Simulator Tested On: Android Emulator via Visual studio
![image](https://cloud.githubusercontent.com/assets/5440162/22173567/a9e1899c-df7c-11e6-9a26-2057beab1d06.png)

### Expected Behavior
Get geolocation position
### Actual Behavior
First run was successful
subsequent runs all resulted in the following
![image](https://cloud.githubusercontent.com/assets/5440162/22173574/e6a255f0-df7c-11e6-8ef6-64a56a93ae30.png)

### Steps to reproduce the Behavior

1. Open the vanilla GeolocatorSample solution (I downloaded the sample solution a hour prior to this post from here)
2. Select the Android project as startup
3. Run with emulation settings from above image. 
4. Press GETGPS
5. Repeat 1-4 once

**Comment by jamesmontemagno** [comment]
The problem with the default android emulators now is that they don't send the current GPS, you have to go to settings->GPS-> and send a lat/lng down to it in the emulator settings. try that.

**Comment by imgregduh** [comment]
Based on @jamesmontemagno comment
Solution
While `locator.GetPositionAsync(timeoutMilliseconds: 10000);` is awaiting you have to manually send gps data to your android emulator via emulator settings.
