### ISSUE TITLE
Add property to allow which Sensor Data to use (Mobile/GPS)

### ISSUE THREAD

**Issue by istoff** [jamesmontemagno/GeolocatorPlugin#54]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Feature Request:
Would like the ability to select a desired level of accuracy (other than metres) to ensure we only use GPS Sensor data instead of having mixed readings from the network assisted / play services.

I'm finding that when parked in a highly populated area, my GPS readings jitter by about 30m.   I have experimented with multiple devices and the problem only occurs when Location accuracy is set to include GPS assist from the mobile network / wifi (google play).  If I force physical gps sensor only, the problem goes away.

I would debug this using the NMEA strings if I had them, but I see this issue is already opened, so I won't duplicate that.

If there is any additional info you need, happy to test / help.  I am using your reference code so nothing unique my side.  It works perfectly if only physical GPS is used (or phone without SIMCard).

Thanks for a very useful set of plugins.  Keep it up, it's much appreciated.

**Comment by DeRas** [comment]
I'm having the same issue - I need to be able to only receive locations from GPS. I think its more then an enhancement, as the locations are useless in many scenarios.

**Comment by istoff** [comment]
Unfortunately, I had to revert to the google implementation to get the NMEA string and to filter out the Network & Play Store GPS Location Providers and use Sensor only.  Not sure how easy it would be to implement on IOS to make this cross platform.   To James, in engineering applications, precise GPS co-ords are not a luxury.  We cannot deliver applications which drift OR, where the readings differ from multiple devices mounted on a measuring platform.  I hope there is a way that this can be implemented in the plugin as it would be really useful.

**Comment by fromm1990** [comment]
I am making an app where precise GPS locations are a necessity, however, the GeolocatorPlugin does not assure the validity of GPS points since it occasionally returns random results.

![image](https://cloud.githubusercontent.com/assets/7311836/25328943/fbd6270c-28d9-11e7-9330-33ccc299b9d2.png)

The dots marked by a red circle are all points send from providers different from the GPS only provider. Unfortunately, missing the feature of selecting the provider on Android smartphones makes this plugin unusable in my context. Therefore, I agree with @DeRas, this is not an enhancement, but rather a feature necessary for applications that are location dependent.

**Comment by thomasfrisko** [comment]
I have a very similar issues with this plug-in. It seems like it stores random GPS points which are far away from the correct location.

**Comment by jorgen-k** [comment]
This is absolutely needed. It also seems, after browsing the code, that any provider can make an update at any time (indicates the problem @thomasfrisko mentions) - thus no control at all of which provider to use. Furthermore it seems like the DesiredAccuracy setting is not used in the Android GeoLocationContiuousListener at all.

Easy fast fix is to make a setter for Providers (android only).

**Comment by istoff** [comment]
My investigation of this from the Apple side is that you will never be able to force sensor only.  On Android, it is possible to use sensor only data.   Trying to implement a cross-platform provider might not be possible, but I do think it is worth implementing it for Android only.

**Comment by jamesmontemagno** [comment]
Now available in 5.0-beta.

I used the fused locator by default now, but you can revert back to the old school by doing this in your android project:

CrossGeolocator.UseFusedLocationProvider = false;

then do this:

Plugin.Geolocator.GeolocatorImplementation.ProvidersToIgnoreWhileListening = new string[]{};

and add whatever you want in there to itnore.

**Comment by istoff** [comment]
Thank you.
