### ISSUE TITLE
DesiredAccuracy?

### ISSUE THREAD

**Issue by wierzba3** [jamesmontemagno/GeolocatorPlugin#56]
Could someone explain to me the function of DesiredAccuracy and why you would choose a higher value? Is it more taxing on the hardware to ask for higher accuracy i.e. more triangulation ?

**Comment by wierzba3** [comment]
Also I apologize as this is not an issue but I do not see anywhere else to ask questions.

**Comment by jamesmontemagno** [comment]
The desired accuracy is the distance you want the GPS to be within. So the smaller the number the longer it would take for the GPS to lock in. Usually you can set this relatively high so it doesn't take as long to lock in and you would still be really accurate.
