### ISSUE TITLE
Background service dying after 30 minutes.

### ISSUE THREAD

**Issue by Aphire** [jamesmontemagno/GeolocatorPlugin#58]
## Bug 
When an iOS user clicks their "home" button and pushes the app to the background, it should continue getting their GPS location, which it **does**. However after roughly 30 minutes, the "App is using your location" message dissapears and the app stops getting their info. I believe i have all of the required permissions etc, and it does work for a while but not for the duration needed.

For more info, please see my SO post which did not get much attention: 

http://stackoverflow.com/questions/41677464/xamarin-ios-geolocator-background-service-dying-after-about-30-mins

Version Number of Plugin: 3.0.4
Device Tested On: Various iOS devices

### Expected Behavior
App should continue as a background service to track the user until they tell it to stop.

### Actual Behavior
App continues as a background service for a while, then stops with no warning.

### Steps to reproduce the Behavior
Launch the app, click the home button and wait.

**Comment by jamesmontemagno** [comment]
Would need to most likely use the new 4.X background services that are included.
