### ISSUE TITLE
Does not work on android

### ISSUE THREAD

**Issue by mohsinalam88** [jamesmontemagno/GeolocatorPlugin#59]
## Bug 
Cant get it to work on android device. Neither on UWP. Works on WinPhone though

**Comment by Aphire** [comment]
I think before anyone can begin to help you, you need to add some more information, i.e what did you do to try and get it working on droid, are you running a simulator (if so, are you actually changing the GPS values) and what steps can be taken to reproduce the error.

**Comment by WiteCastle** [comment]
Actually, I'm starting to have this issue. When I click a button to get the coordinates I can see the location icon pop up on the top bar. But looking closer at my logs this is what I found. This [gist](https://gist.github.com/WiteCastle/0c8707df4bb073a210da89408fe43a23) has a piece of my code and the logs. It looks like its having trouble opening some files. I've made sure the ACCESS_COURSE_LOCATION and ACCESS_FINE_LOCATION are set and that I'm targeting v23 explicitely. I've also checked on the phone and the app has permission to Location.

I'm running on a Nexus 6p with Android 7.1.1.

**Comment by WiteCastle** [comment]
So, I got it to work by using the StartListeningAsync() method when I travel to the page. It now grabs the location in record time! I also don't see the error I found in the gist. I'm not sure why this is but does the documentation need to be edited to include this step?
