### ISSUE TITLE
Error "Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))" when attempting to restart the listener

### ISSUE THREAD

**Issue by gceaser** [jamesmontemagno/GeolocatorPlugin#60]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
I have the following method in the App class of my PCL

public static void ListenForLocationChanges()
        {
            if (gobj_RealGeoCoordinator.IsListening)
            {
                var lobj_Result1 = gobj_RealGeoCoordinator.StopListeningAsync();

                while (!lobj_Result1.IsCompleted)
                {
                    Debug.WriteLine("App-ListenForLocationChanges-1");
                    Task.Delay(100);
                }
            }

            var lobj_Result2 = gobj_RealGeoCoordinator.StartListeningAsync(10000, 100);
            while (!lobj_Result2.IsCompleted)
            {
                Debug.WriteLine("App-ListenForLocationChanges-2");
                Task.Delay(100);
            }

        }

When the app starts I call this and everything works fine.  When the user changes mode (in one of my content pages), I call the my app method to stop listening as follows:

        public static void StopListeningForLocationChanges()
        {
            gobj_RealGeoCoordinator.StopListeningAsync();
        }

Then when the user clicks on a button to start using GPS again, I call the ListenForLocationChanges.  In that method when it attempts to start listening again, I get the following error:

{"Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))"}

Version Number of Plugin: 3.0.4
Device Tested On: N/A
Simulator Tested On: Windows Phone 8.1

### Expected Behavior
The GeoLocation listener should start back up.

### Actual Behavior
The listed exception is generated.

### Steps to reproduce the Behavior
As listed above.

## Feature Request:
I would like the error to be resolved.

**Comment by jamesmontemagno** [comment]
Have you tried to run them with the dispatcher so they occur on the correct thread. That is my first thought when I see something like that.

**Comment by jamesmontemagno** [comment]
As of 4.0 Win 8.x is no longer supported and not providing and patches to 3.x
