### ISSUE TITLE
Error xamarin.forms Java.Lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION

### ISSUE THREAD

**Issue by ramiss** [jamesmontemagno/GeolocatorPlugin#61]
Please note that this is likely not a bug, I just can't figure out what is going on.

## Bug 

Version Number of Plugin: Latest as of 2/7/2017
Device Tested On: Samsung Note 5 (Marshmallow)
Simulator Tested On:

### Expected Behavior
For the App to wait for me to "Allow app to use device location"

### Actual Behavior
The App (more precisely VS2015) errors out with the error in the subject line "as soon" as the "Allow app to use Location" popup appears.  It seems that the "await" command is not... waiting.
I do have ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION set in the manifest.

### Steps to reproduce the Behavior
This happens just by initializing the plugin. (before requesting a position).

**Comment by jamesmontemagno** [comment]
Seems like you are using the xamarin.forms maps perhaps. You should request permissions from your users.
