### ISSUE TITLE
[Feature Request] Find GPS Mock location enabled in android

### ISSUE THREAD

**Issue by devapalanisamy** [jamesmontemagno/GeolocatorPlugin#63]
## Feature Request:
Android GPS Spoof apps can manipulate location. If we can get that info about the mock location in android, it will be helpful.

**Comment by prashantvc** [comment]
@devapalanisamy 

Could you elaborate the feature request please
- What are you ideas? 
- How this feature should work, on different platforms?

**Comment by jamesmontemagno** [comment]
I don't really like this feature request as it can't be set for the other platforms at all. I think should be closed as it is so platform specific.
