### ISSUE TITLE
GeoLocator- Task was cancelled.

### ISSUE THREAD

**Issue by ruchi12l** [jamesmontemagno/GeolocatorPlugin#64]
###Version Number of Plugin: Version - 3.0.4
###Emulator Tested On: 4.4.2 (API level-19)
###Steps to reproduce the Behaviour

await locator.GetPositionAsync(timeoutMilliseconds: 10000).ContinueWith(t =>{
					if (t.IsCanceled){}
});

I always returns with Is.Canceled = true(exception- "Task was cancelled"). I have also requested for "ACCESS_FINE_LOCATION" & "ACCESS_COARSE_LOCATION" in AndroidManifest.xml file and on runtime for marshmallow and above android versions. Its not working fine. Im facing this issue since last 2 weeks.

Do we need to configure anything else to make it working.

**Comment by jamesmontemagno** [comment]
This means that it couldn't lock onto the location. If you are using an emulator you need to send the location each time via the settings.

Make sure you have your actual location on if you are using a device. Also make sure you have proper permissions. It will auto request the first time, but best to try to manage that.

**Comment by ruchi12l** [comment]
@jamesmontemagno 

Location is on and permissions are requested properly in manifest file and in code also (runtime request for marshmallow and above).

**Comment by ruchi12l** [comment]
On marshamallow GetPositionAsync never returns.

When I click the button to get location, it request for location. Popup appears "Allow app to access this device's location". After Allowing, When Requested for location GetPositionAsync, it never returns.

**Comment by jamesmontemagno** [comment]
Have you done this: https://github.com/jamesmontemagno/permissionsplugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code

**Comment by ruchi12l** [comment]
@jamesmontemagno working on 4.4.2 emulator but when I try to get location on Marshmallow (real device) , It throws an exception "A task was cancelled."

Location is on.
Target/Minimum versions are set properly.
Permissions are requested also.

**Comment by jamesmontemagno** [comment]
hmmmm interesting, can you screen shot the target/minimum for me just to validate.

Did you also add the code in your MainActivity so the permissions code returns properly when requested? Does it break in there at all?

Is High precision on on your device?

**Comment by ruchi12l** [comment]
https://screencast.com/t/80am4Fx28n4X (requesting permissions in mainactivity)

https://www.screencast.com/t/b2Q3LaTKslki (setting versions properly)

**Comment by jamesmontemagno** [comment]
Do you want to send me the source code and I can test it. Simply delete the packages folder anda ll bin/obj and it will zip really small.

**Comment by jamesmontemagno** [comment]
My only other assumption is to try to remove the "StartListening" to make sure that isn't interferring at all.

**Comment by ruchi12l** [comment]
[GeolocatorPlugin-master.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/795659/GeolocatorPlugin-master.zip)

**Comment by jamesmontemagno** [comment]
@ruchi12l you just sent me the plugins code, not your samples code.

**Comment by jamesmontemagno** [comment]
oh, i see you were working out of the samples project I guess..?

**Comment by jamesmontemagno** [comment]
oh, i see you were working out of the samples project I guess..?

**Comment by jamesmontemagno** [comment]
So, I ran your sample code and it worked fine in my emulator and on my Nexus 6P, but you are doing way too much work that isn't needed and I condensed it down into a few lines of code. See attached.

[GeolocatorSample.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/797790/GeolocatorSample.zip)

**Comment by tcthechamp** [comment]
<uses-feature android:name="android.hardware.location.gps" />
  <uses-feature android:name="android.hardware.location.network" />
  
add these in your mainfest.xml 
solved my problem Try it out

**Comment by tcthechamp** [comment]
` 
  <uses-feature android:name="android.hardware.location.gps" />
  <uses-feature android:name="android.hardware.location.network" /> `

Add these in my mainfest solved my problem 
try it out
