### ISSUE TITLE
A Task was canceled or Timed out wating for response from server

### ISSUE THREAD

**Issue by TeuryBazzo** [jamesmontemagno/GeolocatorPlugin#65]
When  i using the method GetPositionAsync() he return a execption "A task was canceled" or "Timed out wating for response from server", but sometimes the method work fine. Does anyone know why this execption ?

Version Number of Plugin: 3.0.4.0
Device Tested On: Galaxy S6 - android marshmallow

my code : 

`               var locator = CrossGeolocator.Current;

                var geo = new Geocoder();

                locator.DesiredAccuracy = 100;
                
                var position = await locator.GetPositionAsync(timeoutMilliseconds: 6000);

                var positionCurrentl = new Position(position.Latitude, position.Longitude);

                var adress = await geo.GetAddressesForPositionAsync(positionAtual);

                camp.Text += adress .First().ToString();
`

**Comment by jamesmontemagno** [comment]
see flow from #64 and sample project.
[GeolocatorSample.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/797793/GeolocatorSample.zip)

**Comment by TeuryBazzo** [comment]
thanks  @jamesmontemagno
