### ISSUE TITLE
GetAddressesForPosition Not Found

### ISSUE THREAD

**Issue by TonyLugg** [jamesmontemagno/GeolocatorPlugin#68]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 3.0.4

In the PCL, when I code locator.GetAddressesForPosition (or with Async suffix) the method is not found.  locator.GetPositionAsync works fine.  Was GetAddressesForPosition added after the 3.0.4 release?

**Comment by jamesmontemagno** [comment]
Yes, it is in the next 4.0 release
