### ISSUE TITLE
GetAddressesForPositionAsync not showing up

### ISSUE THREAD

**Issue by GregorioCunha007** [jamesmontemagno/GeolocatorPlugin#70]
## Bug 

Version Number of Plugin: 3.0.4

 var addresses = await locator.GetAddressesForPositionAsync (position);

I tried to compile this line but the method simply doesn't exist. I saw all the methods and properties available in IGeolocator and it doesn't exist in my project. Do you have any idea what might be the cause of this ? 

Thanks in advance

**Comment by jamesmontemagno** [comment]
This is in the beta, not stable.
