### ISSUE TITLE
Upgrade from 3.0.4 to 4.0.0.46-beta failed with "This functionality is not implemented" exception

### ISSUE THREAD

**Issue by ZeAleks** [jamesmontemagno/GeolocatorPlugin#73]
## Bug 

Version Number of Plugin: 4.0.0.46-beta
Device Tested On:
Simulator Tested On: Emulator 8.1 720P 4.7 inch

### Expected Behavior
Application launched and I can get the position

### Actual Behavior
This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

### Steps to reproduce the Behavior
Application was launching correctly and I was able to get my position.
I just upgraded from 3.0.4 to 4.0.0.46-beta.
Now I get this error above.

**Comment by jamesmontemagno** [comment]
4.0 no longer support windows phone or store 8

**Comment by ZeAleks** [comment]
Hello,

Do you mean 8.0 only or also 8.1 ?
On Windows platform, my users are 90% Windows Phone 8.1 users !

Thank you.
Alek

**Comment by jamesmontemagno** [comment]
I have it clearly defined on the main Readme. I am dropping support for Windows Phone 8, 8.1, and Windows Store 8.X as far as new features and including them in new packages. With Visual Studio 2017 out of the box the support has been removed and that is my main environment that I use for development. The old code will remain in the repo for reference, but no new work will be done and they will no longer ship with new packages. This is the first to drop support and all others to follow throughout the year.
