### ISSUE TITLE
Showing incorrect plist keys message

### ISSUE THREAD

**Issue by maartenvandillen** [jamesmontemagno/GeolocatorPlugin#74]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:4.0.0.46-beta
Device Tested On: iOS 10.2.1
Simulator Tested On:

### Expected Behavior
Alert described below should not be shown.

### Actual Behavior
The alert from the RequestAuthorization method is shown ("On iOS 8.0 and higher you must set either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in your Info.plist file to enable Authorization Requests for Location updates!") despite having the key "NSLocationAlwaysUsageDescription" in my Info.plist. Problems started today after upgrading to the latest plugin version.

**Comment by jamesmontemagno** [comment]
The code specifically calls out:

```csharp
            if (UIDevice.CurrentDevice.CheckSystemVersion(8, 0))
            {
                if (info.ContainsKey(new NSString("NSLocationAlwaysUsageDescription")))
                    manager.RequestAlwaysAuthorization();
                if (info.ContainsKey(new NSString("NSLocationWhenInUseUsageDescription")))
                    manager.RequestWhenInUseAuthorization();
                else
                    throw new UnauthorizedAccessException("On iOS 8.0 and higher you must set either NSLocationWhenInUseUsageDescription or NSLocationAlwaysUsageDescription in your Info.plist file to enable Authorization Requests for Location updates!");
            }
```

That hasn't changed at all. Can you double check your info.plist to make sure. I tested this out and seems to work here.

**Comment by maartenvandillen** [comment]
Copied (and stripped) from my Info.plist:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	...
	<key>NSLocationAlwaysUsageDescription</key>
	<string>We gebruiken je locatie om ...</string>
	...
</dict>
</plist>

Same as the code, this has not changed at all so it must have another cause. I can think of these things:
1) I only use NSLocationAlwaysUsageDescription, not NSLocationWhenInUseUsageDescription. Is that allowed?
2) can I check in some way the correct Info.plist ends up in the ipa?
3) is there an easy way to skip this check as the code is there for a developers safety check?

Thanks.

**Comment by jamesmontemagno** [comment]
I will test it out only with the single usage.

**Comment by jamesmontemagno** [comment]
oh, i see the issue in that code. forgot an ```else if`` let me fix and push

**Comment by maartenvandillen** [comment]
Yes it's working great now. Thanks for your quick response and actions!
