### ISSUE TITLE
IsGeolocationEnabled returning wrong result

### ISSUE THREAD

**Issue by DeRas** [jamesmontemagno/GeolocatorPlugin#75]
## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: Huawei P8
Simulator Tested On: -

### Expected Behavior
CrossGeolocator.Current.IsGeolocationEnabled to return false when position/location/gps is disabled on phone.

### Actual Behavior
It returns true.

### Steps to reproduce the Behavior
Disable locations on the Huawei P8, create an app that checks for CrossGeolocator.Current.IsGeolocationEnabled - it returns true.

Perhaps similar issue reported here: 
https://components.xamarin.com/view/geolocatorplugin (second last comment)
https://forums.xamarin.com/discussion/62705/is-there-a-bug-in-xam-plugin-geolocator

*Note that i have tested on OnePlus Two and OnePlus Three, which has correct behavior.

**Comment by DeRas** [comment]
Just noticed closed issue #23 .

**Comment by DeRas** [comment]
Issue persists in version: 4.0.0.52-beta
Feel free to close my issue if it is fixed in newer versions, @jamesmontemagno .

**Comment by jamesmontemagno** [comment]
On my nexus 6 this works if you turn off geolocation as it will leave only passive on. You will need to help me debug here:..

Code:

```
 string[] Providers => Manager.GetProviders(enabledOnly: false).ToArray();
       

        LocationManager Manager
        {
            get
            {
                if (locationManager == null)
                    locationManager = (LocationManager)Application.Context.GetSystemService(Context.LocationService);

                return locationManager;
            }
        }

/// <inheritdoc/>
        public bool IsGeolocationEnabled => Providers.Any(p => p != LocationManager.PassiveProvider && Manager.IsProviderEnabled(p));

```

See which provider is returning true.

**Comment by DeRas** [comment]
Huawei phones has their quirks. I'll debug it and submit a PR if i figure out the issue, first thing monday.

**Comment by DeRas** [comment]
I have a OnePlus Two and a Huawei P8 as test devices. Both have the same location settings (High accuracy using GPS, Wi-Fi, Bluetooth or celluilar) and locations disabled. I'm checking the providers with the code you specified.

Huawei P8 has an extra provider named local_database which is always enabled even though Geolocation is disabled. Check screenshot:

![huawei-isgeolocationenabled](https://cloud.githubusercontent.com/assets/7255223/24355076/cdd61376-12f4-11e7-8081-b758088ac808.PNG)

I don't see a way to exclude local_database the way you do it with the passive provider. Do you have a elegant fix, @jamesmontemagno ?

**Comment by jamesmontemagno** [comment]
ahhh interesting, thanks for debugging this. I can ignore that one. so weird! basically all i care about is GPS and Network. I will maybe do a check to see if it is GPS or Network and if enabled instead.

**Comment by DeRas** [comment]
I agree - maybe even let it be up to the consumer of the plugin to decide whether to check for GPS or Network or both. I know that would be useful in my usecase, as i need GPS :)

**Comment by jamesmontemagno** [comment]
It is tricky, because really only android has that option.

**Comment by jamesmontemagno** [comment]
What all are you using in the new beta? I am getting ready for it to go stable, but need some real testers that have been active with it. 

I will push out a fix for this soon.

**Comment by DeRas** [comment]
I updated to the beta version friday to test this bug and so far it has been a pretty stable experience for me. I'm using:
IsGeolocationAvailable
IsGeolocationEnabled
IsListening
PositionChanged event
StartListeningAsync
StopListeningAsync

Is there anything specific you'd like me to test ?

**Comment by DeRas** [comment]
And thanks for the fix, really appreciate it :)

**Comment by jamesmontemagno** [comment]
Lovely! That is great! Are you just testing Android or iOS too?

**Comment by DeRas** [comment]
I'm working with iOS too :)
