### ISSUE TITLE
Not working in PCL

### ISSUE THREAD

**Issue by longlostbro** [jamesmontemagno/GeolocatorPlugin#77]
## Bug 
Code:
var locator = CrossGeolocator.Current;
locator.DesiredAccuracy = 1;
var position = await locator.GetPositionAsync(10000);

Version Number of Plugin: 3.0.4

Simulator Tested On: Android 23 x86 phone vs emulator

### Expected Behavior
 Returning the current location
### Actual Behavior
 Error message:
"This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."
### Steps to reproduce the Behavior
Create a xamarin.forms pcl blank project and add code suggested in plugin.geolocator readme

**Comment by PureWeen** [comment]
You need to add the nuget package to the actual platform. So add the nuget package to the Android project itself.  That adds the Android specific implementation that's able to inject itself into the PCL so that you can then interact with it in a generic way from the PCL.

**Comment by longlostbro** [comment]
I have added it to all three: android, ios and common projects but it still gives me this message

**Comment by anth12** [comment]
Exact same issue. I first added the reference to my PCL then added the same nuGet package to the Android project and get a `NotImplementedException`. I also get the exception when accessing `Plugin.Geolocator.CrossGeolocator.Current` from the Android project.

**Comment by jamesmontemagno** [comment]
You must install into all, make sure you clean and re-build.

**Comment by longlostbro** [comment]
I have done that and it still doesnt work. Why did you close the issue? Two people have the same problem and it hasnt been fixed.

**Comment by jamesmontemagno** [comment]
Because it is most likely something with your environment, uninstall and re-install the nugets. It has worked for thousands of others including myself.

**Comment by longlostbro** [comment]
after upgrading to the beta it now works

**Comment by grockland** [comment]
yep, upgrading to the beta did it.  Maybe requires the no timeout option for reliable performance.
