### ISSUE TITLE
Having trouble with .NetStandard and Xamarin.Forms / Android

### ISSUE THREAD

**Issue by AndyMason75** [jamesmontemagno/GeolocatorPlugin#78]
## Bug ? (could just be me)

I'm in the middle of adopting .NetStandard, so I'm upgrading what were my PCL projects to NetStandard 1.6. Mostly going well, and I've got everything working again, including your permissions, battery, settings and version plugins. Just not geolocator.

Version Number of Plugin: 3.0.4
Device Tested On: Nexus 5 / other Android hardware running 4.4
Simulator Tested On: n/a

### Expected Behavior
Should work perfectly like it always has, please note that I only use Xamarin.Forms with Android at the moment so I can't test/check anything on UWP or iOS

### Actual Behavior
Exception rasied when running unmodified code that used to work (project is modified a lot to work with NetStandard, but the code itself is unchanged).
```
04-03 19:15:44.669 I/MonoDroid(14810): System.TypeLoadException: Could not resolve type with token 01000114
04-03 19:15:44.669 I/MonoDroid(14810):   at Plugin.Geolocator.GeolocatorImplementation.OnListenerPositionChanged (System.Object sender, Plugin.Geolocator.Abstractions.PositionEventArgs e) [0x00030] in C:\projects\xamarin-plugins\Geolocator\Geolocator\Geolocator.Plugin.Android\GeolocatorImplementation.cs:282 
04-03 19:15:44.669 I/MonoDroid(14810):   at Plugin.Geolocator.GeolocationContinuousListener.OnLocationChanged (Android.Locations.Location location) [0x0014e] in C:\projects\xamarin-plugins\Geolocator\Geolocator\Geolocator.Plugin.Android\GeolocationContinuousListener.cs:86 
04-03 19:15:44.670 I/MonoDroid(14810):   at Android.Locations.ILocationListenerInvoker.n_OnLocationChanged_Landroid_location_Location_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_location) [0x00011] in /Users/builder/data/lanes/4009/3a62f1ea/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Locations.ILocationListener.cs:94 
04-03 19:15:44.670 I/MonoDroid(14810):   at (wrapper dynamic-method) System.Object:50e55dd4-df03-4c11-92bb-e135ba7f533b (intptr,intptr,intptr)
```

### Steps to reproduce the Behavior
Run any of the simple examples with a Xamarin.Forms project which uses an Android front end and a NetStandard library (rather than PCL) for the shared code.

Thanks again, and I'm really sorry if I'm being stupid.

p.s. I have tried building/running with your source code, but it's not tagged so I couldn't easily find the right commit. v4 beta is a bit different and I didn't want to muddy the waters so to speak.

**Comment by jamesmontemagno** [comment]
4.0 will solve this up

**Comment by AndyMason75** [comment]
Thanks James, I'll update.

**Comment by DamianSuess** [comment]
@jamesmontemagno I know this is an old & closed off issue, however, what was done to solve this issue?  I'm having the same issue with a different plugin (_ZXing.Net.Mobile.Forms and netStandard v1.4_). I'd like to fix theirs, just not sure how you did it in yours.
