### ISSUE TITLE
GetLastKnownLocationAsync Misiing 

### ISSUE THREAD

**Issue by juanse417** [jamesmontemagno/GeolocatorPlugin#79]
## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: iOS 10.2, Android API 23
Simulator Tested On: iPhone 6 10.2, Nexus 4 Android 6.0

### Expected Behavior
Be able to use as detailed in documentation

```
var cached = await CrossGeolocator.Current.GetLastKnownLocationAsync();
				if (cached == null)
					return;
```

### Actual Behavior
Error message:
```
Plugin.Geolocator.Abstractions.IGeolocator does not contain a definition for GetLastKnownLocationAsync and no extension method GetLastKnownLocationAsync of type Plugin.Geolocator.Abstractions.IGeolocator could be found. Are you missing an assembly reference?
```

### Steps to reproduce the Behavior
*Create a new PCL project
*Add Geolocator plugin (PCL, Droid, iOS)
*Try to use `GetLastKnownLocationAsync`

**Comment by jamesmontemagno** [comment]
This is in the beta

**Comment by Nick1611** [comment]
I found that GetLastKnownLocationAsync is missing. I am on the latest stable version 4.0.1.  I have just removed and reinstalled the package. 

Though I could find that task defined in the IGeolocator source code on github, it could not be found in the project. Is there any chance that it was omitted when released?

**Comment by jamesmontemagno** [comment]
Make sure all of your nugets are up to date or remove and re-add them and clean and rebuild

**Comment by Nick1611** [comment]
Thank you very much James. That's my fault. I have the mj fused location provider installed and hold the old version of your geolocator. I overlooked it. Sorry for my mistake.
