### ISSUE TITLE
CrossGeolocator timestamp is 1 hour off in iOS

### ISSUE THREAD

**Issue by bokmadsen** [jamesmontemagno/GeolocatorPlugin#81]
## Bug 

Version Number of Plugin: 3.0.4
Device Tested On: iPhone 7 10.3.1
Simulator Tested On: 10.3

### Expected Behavior
Position.Timestamp should be UTC

### Actual Behavior
It's UTC -1

### Steps to reproduce the Behavior
CrossGeolocator.Current.StartListeningAsync(5, 10, false);
CrossGeolocator.Current.PositionChanged += Current_PositionChanged;
private void Current_PositionChanged(object sender, Plugin.Geolocator.Abstractions.PositionEventArgs e)
        {
            // Observe that e.Position.Timestamp is off by one hour
        }

**Comment by jamesmontemagno** [comment]
I believe fixed in the new beta.
