### ISSUE TITLE
Needs some Help with Newest Pre Release

### ISSUE THREAD

**Issue by Bobisback** [jamesmontemagno/GeolocatorPlugin#83]
I am not sure if this a bug or me just missing something. if I update to the newest version of this 4.0.0.55 I am getting a missing method exception for pretty much every method on the IGeolocator abstraction. This is in Android. I am compiling and targeting 7.1 api 25. I am using the caxmarin forms 2.3.4.231.

If I downgrade to the 3.0.1 release it works fine. Any ideas what I am doing wrong?

**Comment by Bobisback** [comment]
As a side note this is happening at run time. It compiles and runs just once I go to that screen that calls it i get these exceptions.

**Comment by jamesmontemagno** [comment]
May remove and re-add and do a full clean/rebuild and delete bin/obj. Probably a build error.
