### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/GeolocatorPlugin#84]
I have longitude and latitude in my database and I want to check user device is currently staying in the range of that db location. How can I achieve it using this plugin? Sorry to post as an issue.

**Comment by DeRas** [comment]
Hi @ShahriatHossain 

This plugin does not offer any functionality to observe range from a fixed point. I think the best option for you is to calculate the distance the location received from this plugin to your location in the database.
The calculation is trivial to find an implementation for online.

**Comment by rrispoli** [comment]
The plugin doesn't do this, but you can calculate the distance between two coordinates with GeoCoordinate:

using System.Device.Location;
var distanceInMeters = new GeoCoordinate(myLat, myLng).GetDistanceTo(new GeoCoordinate(dbLat, dbLng));

**Comment by ShahriatHossain** [comment]
thank you guys!

**Comment by DeRas** [comment]
@jamesmontemagno i think you can consider this one closed 👍
