### ISSUE TITLE
plugin won't retrieve coordinates in time

### ISSUE THREAD

**Issue by Mikaelle333777** [jamesmontemagno/GeolocatorPlugin#88]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug fails to retrieve coordinates in time.

Version Number of Plugin: 3.0.4
Device Tested On: LG G4, LG L70, Samsung Galaxy S3
Simulator Tested On: 

### Expected Behavior
Retrieve the coordinates in time.

### Actual Behavior
Fails to retrieve the coordinates even in 10000ms.

### Steps to reproduce the Behavior
- timeout set to 10000ms - > I am in screen A of my app, and the plugin retrieves the coordinates in time (called in async function). If I press back and go screen B, then fast to screen A again, it fails to retrieve the coordinates again, with the error message telling to increase timeout (it is set to 10000). If I wait on screen B a couple of seconds before going again to A, it retrieves the coordinates again, normally.

**Comment by julesx** [comment]
I too am noticing this.  I can open google maps or any other GPS app and get a location near-instantaneously, but this plug seems sort of random.  Sometimes it is instant, sometimes it takes 10+ seconds, and sometimes it just never seems to work at all.

**Comment by jamesmontemagno** [comment]
You could try latest beta and let me know if you see any difference.

**Comment by Mikaelle333777** [comment]
Thank you for the instant feedback. I've installed the latest beta and, at a first glance, it seems to work quite fine, though a bit slow, still. Anyway, I'll keep an eye on it :)

**Comment by jamesmontemagno** [comment]
@Mikaelle333777 the fastest possible way is to use Google Play services itself. This library uses the core services. You may want to look into https://github.com/jamesmontemagno/GeolocatorPlugin/issues/30#issuecomment-280524977

I will eventually be bringing this work in.

**Comment by Mikaelle333777** [comment]
Well, I have a Xamarin project targeting both Android and iOS, so our Core should be platform-independent, as much as possible. Therefore, google play services don't seem the best solution. Anyway, thank you so much for the support, now in last Beta it really does what it should.

**Comment by julesx** [comment]
@Mikaelle333777 the core code just reaches into the platform specific functionality, such as google play services on android.
