### ISSUE TITLE
Prompt not showing when no permissions

### ISSUE THREAD

**Issue by jorisM96** [jamesmontemagno/GeolocatorPlugin#89]
Version Number of Plugin: 3.0.4
Device Tested On: Motorola MG3 (API 23)

### Expected Behavior
User is prompted when no permission

### Actual Behavior
User is never prompted

I added the OnRequestPermissionsResult in my MainActivity and got the permissions in my AndroidManifest.

**Comment by jamesmontemagno** [comment]
Did you set your target: https://github.com/jamesmontemagno/GeolocatorPlugin#important

**Comment by jorisM96** [comment]
I've got them both set to Android 7.0

**Comment by jamesmontemagno** [comment]
The permissions only prompt when you request location. 

I highly recommend you use the permission plugin though.
