### ISSUE TITLE
Geolocator conflicts with Xamarin.GooglePlayServices.Ads

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/GeolocatorPlugin#92]
Gecolocator - http://github.com/jamesmontemagno/GeolocatorPlugin
I get this error **"java.exe" exited with code 2** when use Geolocator and Xamarin.GooglePlayServices.Ads in my project. When I use Proguard then I get error **"java.exe" exited with code 1**. It's not happen when i UNINSTALL Geolocator Plugin.
Please check. Thank you!

**Comment by jamesmontemagno** [comment]
You probably want to increase your java heap size in your project settings under advanced to 1G.

**Comment by nguyenthanhliemfc** [comment]
I try a lot of way with error code 1. I have try from 512M..1G..2G it's still happen code 1. I have try with new blank project too. How about error code 2, Do you get this error when use Geolocator with GoogleplayServices.Ads?
