### ISSUE TITLE
Geolocator conflict with Xamarin.GooglePlayServices.Ads

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/GeolocatorPlugin#93]
Thank you for your plugin. 
But I hate the way you close issues after your one comment. 
Please try Geolocator Plugin and Xamarin.GooglePlayServices.Ads in one project. Thank you!

**Comment by jamesmontemagno** [comment]
Please attach or upload a sample project. Without knowing your versions of this plugin, your sdks, or the ads nuget it will be hard for me to diagnose.

**Comment by nguyenthanhliemfc** [comment]
Xamarin.Forms : 2.3.4.247
Xam.Plugin.Geolocator : 3.0.4
Xamarin.GooglePlayServices.Ads : v42.1021.1
Visual Studio 2017
JDK 1.8.0_131
NDK r14
I have try with new project. Just install from Nuget --> Build --> error
Here is my [link](https://1drv.ms/u/s!Ah-5hC3QyJDai4F3tRhdCG7QaNOU3Q)

**Comment by jamesmontemagno** [comment]
You need to update your NuGet Packages and also ensure you are building against 7.0 or 7.1 and it will build just fine.

Also, I would recommend looking into Ads Lite as it has less dependencies: https://blog.xamarin.com/lightweight-ads-for-android-apps/

[LocatorTest.zip](https://github.com/jamesmontemagno/GeolocatorPlugin/files/1017634/LocatorTest.zip)
