### ISSUE TITLE
Breakpoint or control disapear while execute "await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Location });"

### ISSUE THREAD

**Issue by ersachinkaliraman** [jamesmontemagno/GeolocatorPlugin#95]
**Breakpoint or control disapear while executing below instrution
"await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Location });"

after selecting "Allow" or "Don't Allow" from the alert box for location permission, 

control never come back to next instruction or anywhere. 

It only works if page loaded again.**

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On: Iphone 6 and Air2
Simulator Tested On: Iphone 6, 6+
Version of VS: 7.0.1
Version of Xamarin: Xamarin.iOS, Version: 10.10.0.36 (Visual Studio Community)
Versions of other things you are using: 1.2.1

**Comment by jamesmontemagno** [comment]
You will need to add a code snippet. For iOS you need to make sure you update your info.plist. if you decline the permission you can't bring it up again.

**Comment by jamesmontemagno** [comment]
You will need to add a code snippet. For iOS you need to make sure you update your info.plist. if you decline the permission you can't bring it up again.

**Comment by ersachinkaliraman** [comment]
I do always allow the permission for location, still control never come back to code. 

Info.plist is already updated as per instruction you mentioned http://www.screencast.com/t/YEeuAYMBBJ

but not working, control never come back to .cs file

**Comment by jamesmontemagno** [comment]
You would need a code repo and fill out the form properly.
