### ISSUE TITLE
TimeStamp in iOS

### ISSUE THREAD

**Issue by fsaffioti** [jamesmontemagno/GeolocatorPlugin#98]
TimeStamp is not UTC in iOS
If I compare with DateTime.UtcNow is 1 hour before
Differently in Android is all right

sample
```
 var s = string.Format("Time: {0} \nUtc:{8}\nLat: {1} \nLong: {2} \n Altitude: {3} \nAltitude Accuracy: {4} \nAccuracy: {5} \n Heading: {6} \n Speed: {7}",
                                                              position.Timestamp, position.Latitude, position.Longitude,
                            position.Altitude, position.AltitudeAccuracy, position.Accuracy, position.Heading, position.Speed, DateTime.UtcNow);
 
labelGPS.Text = s;
 System.Diagnostics.Debug.WriteLine(s);
```
_I  also tried with position.Timestamp.UtcDateTime_

Sample Result

**Time: 6/6/2017 12:24:45 PM +00:00** 
**Utc:6/6/2017 1:24:45 PM**
Lat: 45.4346175631931 
Long: 10.9977534134043 
 Altitude: 58.390380859375 
Altitude Accuracy: 12 
Accuracy: 50 
 Heading: 0 
 Speed: 0

With old plugin Xam Mobile is right: its code is p.Timestamp = new DateTimeOffset ((DateTime)location.Timestamp);

different in this plugin is
position.Timestamp = new DateTimeOffset(newLocation.Timestamp.ToDateTime());

I have this issue with Iphone 5s  iOS version 10.3.2 and Iphone simulator

Region Italy
Language England
TimeZone Rome

**Comment by jamesmontemagno** [comment]
This was fixed in the beta versions.
